(* auto-generated, do not modify *)

open Runtime
open Objc

[@@@ocaml.warning "-33"]
open Foundation

let _PHContentEditingInputCancelledKey = new_string "PHContentEditingInputCancelledKey"
let _PHContentEditingInputErrorKey = new_string "PHContentEditingInputErrorKey"
let _PHContentEditingInputResultIsInCloudKey = new_string "PHContentEditingInputResultIsInCloudKey"
let _PHImageCancelledKey = new_string "PHImageCancelledKey"
let _PHImageErrorKey = new_string "PHImageErrorKey"
let _PHImageManagerMaximumSize = !@ (Foreign.foreign_value "PHImageManagerMaximumSize" CGSize.t)
let _PHImageResultIsDegradedKey = new_string "PHImageResultIsDegradedKey"
let _PHImageResultIsInCloudKey = new_string "PHImageResultIsInCloudKey"
let _PHImageResultRequestIDKey = new_string "PHImageResultRequestIDKey"
let _PHLivePhotoEditingErrorDomain = new_string "PHLivePhotoEditingErrorDomain"
let _PHLivePhotoInfoCancelledKey = new_string "PHLivePhotoInfoCancelledKey"
let _PHLivePhotoInfoErrorKey = new_string "PHLivePhotoInfoErrorKey"
let _PHLivePhotoInfoIsDegradedKey = new_string "PHLivePhotoInfoIsDegradedKey"
let _PHLivePhotoShouldRenderAtPlaybackTime = new_string "PHLivePhotoShouldRenderAtPlaybackTime"
let _PHLocalIdentifierNotFound = new_string "PHLocalIdentifierNotFound"
let _PHLocalIdentifiersErrorKey = new_string "PHLocalIdentifiersErrorKey"
let _PHPhotosErrorDomain = new_string "PHPhotosErrorDomain"
let _PHAccessLevelAddOnly = 1
let _PHAccessLevelReadWrite = 2
let _PHAssetBurstSelectionTypeAutoPick = 1
let _PHAssetBurstSelectionTypeNone = 0
let _PHAssetBurstSelectionTypeUserPick = 2
let _PHAssetCollectionSubtypeAlbumCloudShared = 101
let _PHAssetCollectionSubtypeAlbumImported = 6
let _PHAssetCollectionSubtypeAlbumMyPhotoStream = 100
let _PHAssetCollectionSubtypeAlbumRegular = 2
let _PHAssetCollectionSubtypeAlbumSyncedAlbum = 5
let _PHAssetCollectionSubtypeAlbumSyncedEvent = 3
let _PHAssetCollectionSubtypeAlbumSyncedFaces = 4
let _PHAssetCollectionSubtypeAny = LLong.(pred max_int)
let _PHAssetCollectionSubtypeSmartAlbumAllHidden = 205
let _PHAssetCollectionSubtypeSmartAlbumAnimated = 214
let _PHAssetCollectionSubtypeSmartAlbumBursts = 207
let _PHAssetCollectionSubtypeSmartAlbumDepthEffect = 212
let _PHAssetCollectionSubtypeSmartAlbumFavorites = 203
let _PHAssetCollectionSubtypeSmartAlbumGeneric = 200
let _PHAssetCollectionSubtypeSmartAlbumLivePhotos = 213
let _PHAssetCollectionSubtypeSmartAlbumLongExposures = 215
let _PHAssetCollectionSubtypeSmartAlbumPanoramas = 201
let _PHAssetCollectionSubtypeSmartAlbumRAW = 217
let _PHAssetCollectionSubtypeSmartAlbumRecentlyAdded = 206
let _PHAssetCollectionSubtypeSmartAlbumScreenshots = 211
let _PHAssetCollectionSubtypeSmartAlbumSelfPortraits = 210
let _PHAssetCollectionSubtypeSmartAlbumSlomoVideos = 208
let _PHAssetCollectionSubtypeSmartAlbumTimelapses = 204
let _PHAssetCollectionSubtypeSmartAlbumUnableToUpload = 216
let _PHAssetCollectionSubtypeSmartAlbumUserLibrary = 209
let _PHAssetCollectionSubtypeSmartAlbumVideos = 202
let _PHAssetCollectionTypeAlbum = 1
let _PHAssetCollectionTypeMoment = 3
let _PHAssetCollectionTypeSmartAlbum = 2
let _PHAssetEditOperationContent = 2
let _PHAssetEditOperationDelete = 1
let _PHAssetEditOperationProperties = 3
let _PHAssetMediaSubtypeNone = 0
let _PHAssetMediaSubtypePhotoDepthEffect = 16
let _PHAssetMediaSubtypePhotoHDR = 2
let _PHAssetMediaSubtypePhotoLive = 8
let _PHAssetMediaSubtypePhotoPanorama = 1
let _PHAssetMediaSubtypePhotoScreenshot = 4
let _PHAssetMediaSubtypeSpatialOverCapture = 32
let _PHAssetMediaSubtypeVideoHighFrameRate = 131072
let _PHAssetMediaSubtypeVideoStreamed = 65536
let _PHAssetMediaSubtypeVideoTimelapse = 262144
let _PHAssetMediaTypeAudio = 3
let _PHAssetMediaTypeImage = 1
let _PHAssetMediaTypeUnknown = 0
let _PHAssetMediaTypeVideo = 2
let _PHAssetPlaybackStyleImage = 1
let _PHAssetPlaybackStyleImageAnimated = 2
let _PHAssetPlaybackStyleLivePhoto = 3
let _PHAssetPlaybackStyleUnsupported = 0
let _PHAssetPlaybackStyleVideo = 4
let _PHAssetPlaybackStyleVideoLooping = 5
let _PHAssetResourceTypeAdjustmentBasePairedVideo = 11
let _PHAssetResourceTypeAdjustmentBasePhoto = 8
let _PHAssetResourceTypeAdjustmentBaseVideo = 12
let _PHAssetResourceTypeAdjustmentData = 7
let _PHAssetResourceTypeAlternatePhoto = 4
let _PHAssetResourceTypeAudio = 3
let _PHAssetResourceTypeFullSizePairedVideo = 10
let _PHAssetResourceTypeFullSizePhoto = 5
let _PHAssetResourceTypeFullSizeVideo = 6
let _PHAssetResourceTypeOriginalAdjustmentData = 16
let _PHAssetResourceTypePairedVideo = 9
let _PHAssetResourceTypePhoto = 1
let _PHAssetResourceTypeSpatialOverCapturePairedVideo = 15
let _PHAssetResourceTypeSpatialOverCapturePhoto = 13
let _PHAssetResourceTypeSpatialOverCaptureVideo = 14
let _PHAssetResourceTypeVideo = 2
let _PHAssetSourceTypeCloudShared = 2
let _PHAssetSourceTypeNone = 0
let _PHAssetSourceTypeUserLibrary = 1
let _PHAssetSourceTypeiTunesSynced = 4
let _PHAuthorizationStatusAuthorized = 3
let _PHAuthorizationStatusDenied = 2
let _PHAuthorizationStatusLimited = 4
let _PHAuthorizationStatusNotDetermined = 0
let _PHAuthorizationStatusRestricted = 1
let _PHCollectionEditOperationAddContent = 3
let _PHCollectionEditOperationCreateContent = 4
let _PHCollectionEditOperationDelete = 6
let _PHCollectionEditOperationDeleteContent = 1
let _PHCollectionEditOperationRearrangeContent = 5
let _PHCollectionEditOperationRemoveContent = 2
let _PHCollectionEditOperationRename = 7
let _PHCollectionListSubtypeAny = LLong.(pred max_int)
let _PHCollectionListSubtypeMomentListCluster = 1
let _PHCollectionListSubtypeMomentListYear = 2
let _PHCollectionListSubtypeRegularFolder = 100
let _PHCollectionListSubtypeSmartFolderEvents = 200
let _PHCollectionListSubtypeSmartFolderFaces = 201
let _PHCollectionListTypeFolder = 2
let _PHCollectionListTypeMomentList = 1
let _PHCollectionListTypeSmartFolder = 3
let _PHImageContentModeAspectFill = 1
let _PHImageContentModeAspectFit = 0
let _PHImageContentModeDefault = 0
let _PHImageRequestOptionsDeliveryModeFastFormat = 2
let _PHImageRequestOptionsDeliveryModeHighQualityFormat = 1
let _PHImageRequestOptionsDeliveryModeOpportunistic = 0
let _PHImageRequestOptionsResizeModeExact = 2
let _PHImageRequestOptionsResizeModeFast = 1
let _PHImageRequestOptionsResizeModeNone = 0
let _PHImageRequestOptionsVersionCurrent = 0
let _PHImageRequestOptionsVersionOriginal = 2
let _PHImageRequestOptionsVersionUnadjusted = 1
let _PHInvalidAssetResourceDataRequestID = 0
let _PHInvalidImageRequestID = 0
let _PHLivePhotoEditingErrorCodeAborted = 1
let _PHLivePhotoEditingErrorCodeUnknown = 0
let _PHLivePhotoFrameTypePhoto = 0
let _PHLivePhotoFrameTypeVideo = 1
let _PHLivePhotoRequestIDInvalid = 0
let _PHPhotosErrorAccessRestricted = 3310
let _PHPhotosErrorAccessUserDenied = 3311
let _PHPhotosErrorChangeNotSupported = 3300
let _PHPhotosErrorIdentifierNotFound = 3201
let _PHPhotosErrorInternalError = -1
let _PHPhotosErrorInvalid = -1
let _PHPhotosErrorInvalidResource = 3302
let _PHPhotosErrorLibraryInFileProviderSyncRoot = 5423
let _PHPhotosErrorLibraryVolumeOffline = 3114
let _PHPhotosErrorMissingResource = 3303
let _PHPhotosErrorMultipleIdentifiersFound = 3202
let _PHPhotosErrorNetworkAccessRequired = 3164
let _PHPhotosErrorNotEnoughSpace = 3305
let _PHPhotosErrorOperationInterrupted = 3301
let _PHPhotosErrorRelinquishingLibraryBundleToWriter = 3142
let _PHPhotosErrorRequestNotSupportedForAsset = 3306
let _PHPhotosErrorSwitchingSystemPhotoLibrary = 3143
let _PHPhotosErrorUserCancelled = 3072
let _PHVideoRequestOptionsDeliveryModeAutomatic = 0
let _PHVideoRequestOptionsDeliveryModeFastFormat = 3
let _PHVideoRequestOptionsDeliveryModeHighQualityFormat = 1
let _PHVideoRequestOptionsDeliveryModeMediumQualityFormat = 2
let _PHVideoRequestOptionsVersionCurrent = 0
let _PHVideoRequestOptionsVersionOriginal = 1
