(* auto-generated, do not modify *)

open Runtime
open Objc

[@@@ocaml.warning "-33"]
open CoreFoundation
open CoreFoundation_globals
open CoreGraphics
open CoreGraphics_globals
open CoreVideo
open CoreVideo_globals

let _VNAnimalIdentifierCat = new_string "VNAnimalIdentifierCat"
let _VNAnimalIdentifierDog = new_string "VNAnimalIdentifierDog"
let _VNBarcodeSymbologyAztec = new_string "VNBarcodeSymbologyAztec"
let _VNBarcodeSymbologyCodabar = new_string "VNBarcodeSymbologyCodabar"
let _VNBarcodeSymbologyCode128 = new_string "VNBarcodeSymbologyCode128"
let _VNBarcodeSymbologyCode39 = new_string "VNBarcodeSymbologyCode39"
let _VNBarcodeSymbologyCode39Checksum = new_string "VNBarcodeSymbologyCode39Checksum"
let _VNBarcodeSymbologyCode39FullASCII = new_string "VNBarcodeSymbologyCode39FullASCII"
let _VNBarcodeSymbologyCode39FullASCIIChecksum = new_string "VNBarcodeSymbologyCode39FullASCIIChecksum"
let _VNBarcodeSymbologyCode93 = new_string "VNBarcodeSymbologyCode93"
let _VNBarcodeSymbologyCode93i = new_string "VNBarcodeSymbologyCode93i"
let _VNBarcodeSymbologyDataMatrix = new_string "VNBarcodeSymbologyDataMatrix"
let _VNBarcodeSymbologyEAN13 = new_string "VNBarcodeSymbologyEAN13"
let _VNBarcodeSymbologyEAN8 = new_string "VNBarcodeSymbologyEAN8"
let _VNBarcodeSymbologyGS1DataBar = new_string "VNBarcodeSymbologyGS1DataBar"
let _VNBarcodeSymbologyGS1DataBarExpanded = new_string "VNBarcodeSymbologyGS1DataBarExpanded"
let _VNBarcodeSymbologyGS1DataBarLimited = new_string "VNBarcodeSymbologyGS1DataBarLimited"
let _VNBarcodeSymbologyI2of5 = new_string "VNBarcodeSymbologyI2of5"
let _VNBarcodeSymbologyI2of5Checksum = new_string "VNBarcodeSymbologyI2of5Checksum"
let _VNBarcodeSymbologyITF14 = new_string "VNBarcodeSymbologyITF14"
let _VNBarcodeSymbologyMicroPDF417 = new_string "VNBarcodeSymbologyMicroPDF417"
let _VNBarcodeSymbologyMicroQR = new_string "VNBarcodeSymbologyMicroQR"
let _VNBarcodeSymbologyPDF417 = new_string "VNBarcodeSymbologyPDF417"
let _VNBarcodeSymbologyQR = new_string "VNBarcodeSymbologyQR"
let _VNBarcodeSymbologyUPCE = new_string "VNBarcodeSymbologyUPCE"
let _VNBodyLandmarkKeyLeftAnkle = new_string "VNBodyLandmarkKeyLeftAnkle"
let _VNBodyLandmarkKeyLeftEar = new_string "VNBodyLandmarkKeyLeftEar"
let _VNBodyLandmarkKeyLeftElbow = new_string "VNBodyLandmarkKeyLeftElbow"
let _VNBodyLandmarkKeyLeftEye = new_string "VNBodyLandmarkKeyLeftEye"
let _VNBodyLandmarkKeyLeftHip = new_string "VNBodyLandmarkKeyLeftHip"
let _VNBodyLandmarkKeyLeftKnee = new_string "VNBodyLandmarkKeyLeftKnee"
let _VNBodyLandmarkKeyLeftShoulder = new_string "VNBodyLandmarkKeyLeftShoulder"
let _VNBodyLandmarkKeyLeftWrist = new_string "VNBodyLandmarkKeyLeftWrist"
let _VNBodyLandmarkKeyNeck = new_string "VNBodyLandmarkKeyNeck"
let _VNBodyLandmarkKeyNose = new_string "VNBodyLandmarkKeyNose"
let _VNBodyLandmarkKeyRightAnkle = new_string "VNBodyLandmarkKeyRightAnkle"
let _VNBodyLandmarkKeyRightEar = new_string "VNBodyLandmarkKeyRightEar"
let _VNBodyLandmarkKeyRightElbow = new_string "VNBodyLandmarkKeyRightElbow"
let _VNBodyLandmarkKeyRightEye = new_string "VNBodyLandmarkKeyRightEye"
let _VNBodyLandmarkKeyRightHip = new_string "VNBodyLandmarkKeyRightHip"
let _VNBodyLandmarkKeyRightKnee = new_string "VNBodyLandmarkKeyRightKnee"
let _VNBodyLandmarkKeyRightShoulder = new_string "VNBodyLandmarkKeyRightShoulder"
let _VNBodyLandmarkKeyRightWrist = new_string "VNBodyLandmarkKeyRightWrist"
let _VNBodyLandmarkKeyRoot = new_string "VNBodyLandmarkKeyRoot"
let _VNBodyLandmarkRegionKeyFace = new_string "VNBodyLandmarkRegionKeyFace"
let _VNBodyLandmarkRegionKeyLeftArm = new_string "VNBodyLandmarkRegionKeyLeftArm"
let _VNBodyLandmarkRegionKeyLeftLeg = new_string "VNBodyLandmarkRegionKeyLeftLeg"
let _VNBodyLandmarkRegionKeyRightArm = new_string "VNBodyLandmarkRegionKeyRightArm"
let _VNBodyLandmarkRegionKeyRightLeg = new_string "VNBodyLandmarkRegionKeyRightLeg"
let _VNBodyLandmarkRegionKeyTorso = new_string "VNBodyLandmarkRegionKeyTorso"
let _VNErrorDomain = new_string "VNErrorDomain"
let _VNHumanBodyPoseObservationJointNameLeftAnkle = new_string "VNHumanBodyPoseObservationJointNameLeftAnkle"
let _VNHumanBodyPoseObservationJointNameLeftEar = new_string "VNHumanBodyPoseObservationJointNameLeftEar"
let _VNHumanBodyPoseObservationJointNameLeftElbow = new_string "VNHumanBodyPoseObservationJointNameLeftElbow"
let _VNHumanBodyPoseObservationJointNameLeftEye = new_string "VNHumanBodyPoseObservationJointNameLeftEye"
let _VNHumanBodyPoseObservationJointNameLeftHip = new_string "VNHumanBodyPoseObservationJointNameLeftHip"
let _VNHumanBodyPoseObservationJointNameLeftKnee = new_string "VNHumanBodyPoseObservationJointNameLeftKnee"
let _VNHumanBodyPoseObservationJointNameLeftShoulder = new_string "VNHumanBodyPoseObservationJointNameLeftShoulder"
let _VNHumanBodyPoseObservationJointNameLeftWrist = new_string "VNHumanBodyPoseObservationJointNameLeftWrist"
let _VNHumanBodyPoseObservationJointNameNeck = new_string "VNHumanBodyPoseObservationJointNameNeck"
let _VNHumanBodyPoseObservationJointNameNose = new_string "VNHumanBodyPoseObservationJointNameNose"
let _VNHumanBodyPoseObservationJointNameRightAnkle = new_string "VNHumanBodyPoseObservationJointNameRightAnkle"
let _VNHumanBodyPoseObservationJointNameRightEar = new_string "VNHumanBodyPoseObservationJointNameRightEar"
let _VNHumanBodyPoseObservationJointNameRightElbow = new_string "VNHumanBodyPoseObservationJointNameRightElbow"
let _VNHumanBodyPoseObservationJointNameRightEye = new_string "VNHumanBodyPoseObservationJointNameRightEye"
let _VNHumanBodyPoseObservationJointNameRightHip = new_string "VNHumanBodyPoseObservationJointNameRightHip"
let _VNHumanBodyPoseObservationJointNameRightKnee = new_string "VNHumanBodyPoseObservationJointNameRightKnee"
let _VNHumanBodyPoseObservationJointNameRightShoulder = new_string "VNHumanBodyPoseObservationJointNameRightShoulder"
let _VNHumanBodyPoseObservationJointNameRightWrist = new_string "VNHumanBodyPoseObservationJointNameRightWrist"
let _VNHumanBodyPoseObservationJointNameRoot = new_string "VNHumanBodyPoseObservationJointNameRoot"
let _VNHumanBodyPoseObservationJointsGroupNameAll = new_string "VNHumanBodyPoseObservationJointsGroupNameAll"
let _VNHumanBodyPoseObservationJointsGroupNameFace = new_string "VNHumanBodyPoseObservationJointsGroupNameFace"
let _VNHumanBodyPoseObservationJointsGroupNameLeftArm = new_string "VNHumanBodyPoseObservationJointsGroupNameLeftArm"
let _VNHumanBodyPoseObservationJointsGroupNameLeftLeg = new_string "VNHumanBodyPoseObservationJointsGroupNameLeftLeg"
let _VNHumanBodyPoseObservationJointsGroupNameRightArm = new_string "VNHumanBodyPoseObservationJointsGroupNameRightArm"
let _VNHumanBodyPoseObservationJointsGroupNameRightLeg = new_string "VNHumanBodyPoseObservationJointsGroupNameRightLeg"
let _VNHumanBodyPoseObservationJointsGroupNameTorso = new_string "VNHumanBodyPoseObservationJointsGroupNameTorso"
let _VNHumanHandPoseObservationJointNameIndexDIP = new_string "VNHumanHandPoseObservationJointNameIndexDIP"
let _VNHumanHandPoseObservationJointNameIndexMCP = new_string "VNHumanHandPoseObservationJointNameIndexMCP"
let _VNHumanHandPoseObservationJointNameIndexPIP = new_string "VNHumanHandPoseObservationJointNameIndexPIP"
let _VNHumanHandPoseObservationJointNameIndexTip = new_string "VNHumanHandPoseObservationJointNameIndexTip"
let _VNHumanHandPoseObservationJointNameLittleDIP = new_string "VNHumanHandPoseObservationJointNameLittleDIP"
let _VNHumanHandPoseObservationJointNameLittleMCP = new_string "VNHumanHandPoseObservationJointNameLittleMCP"
let _VNHumanHandPoseObservationJointNameLittlePIP = new_string "VNHumanHandPoseObservationJointNameLittlePIP"
let _VNHumanHandPoseObservationJointNameLittleTip = new_string "VNHumanHandPoseObservationJointNameLittleTip"
let _VNHumanHandPoseObservationJointNameMiddleDIP = new_string "VNHumanHandPoseObservationJointNameMiddleDIP"
let _VNHumanHandPoseObservationJointNameMiddleMCP = new_string "VNHumanHandPoseObservationJointNameMiddleMCP"
let _VNHumanHandPoseObservationJointNameMiddlePIP = new_string "VNHumanHandPoseObservationJointNameMiddlePIP"
let _VNHumanHandPoseObservationJointNameMiddleTip = new_string "VNHumanHandPoseObservationJointNameMiddleTip"
let _VNHumanHandPoseObservationJointNameRingDIP = new_string "VNHumanHandPoseObservationJointNameRingDIP"
let _VNHumanHandPoseObservationJointNameRingMCP = new_string "VNHumanHandPoseObservationJointNameRingMCP"
let _VNHumanHandPoseObservationJointNameRingPIP = new_string "VNHumanHandPoseObservationJointNameRingPIP"
let _VNHumanHandPoseObservationJointNameRingTip = new_string "VNHumanHandPoseObservationJointNameRingTip"
let _VNHumanHandPoseObservationJointNameThumbCMC = new_string "VNHumanHandPoseObservationJointNameThumbCMC"
let _VNHumanHandPoseObservationJointNameThumbIP = new_string "VNHumanHandPoseObservationJointNameThumbIP"
let _VNHumanHandPoseObservationJointNameThumbMP = new_string "VNHumanHandPoseObservationJointNameThumbMP"
let _VNHumanHandPoseObservationJointNameThumbTip = new_string "VNHumanHandPoseObservationJointNameThumbTip"
let _VNHumanHandPoseObservationJointNameWrist = new_string "VNHumanHandPoseObservationJointNameWrist"
let _VNHumanHandPoseObservationJointsGroupNameAll = new_string "VNHumanHandPoseObservationJointsGroupNameAll"
let _VNHumanHandPoseObservationJointsGroupNameIndexFinger = new_string "VNHumanHandPoseObservationJointsGroupNameIndexFinger"
let _VNHumanHandPoseObservationJointsGroupNameLittleFinger = new_string "VNHumanHandPoseObservationJointsGroupNameLittleFinger"
let _VNHumanHandPoseObservationJointsGroupNameMiddleFinger = new_string "VNHumanHandPoseObservationJointsGroupNameMiddleFinger"
let _VNHumanHandPoseObservationJointsGroupNameRingFinger = new_string "VNHumanHandPoseObservationJointsGroupNameRingFinger"
let _VNHumanHandPoseObservationJointsGroupNameThumb = new_string "VNHumanHandPoseObservationJointsGroupNameThumb"
let _VNImageOptionCIContext = new_string "VNImageOptionCIContext"
let _VNImageOptionCameraIntrinsics = new_string "VNImageOptionCameraIntrinsics"
let _VNImageOptionProperties = new_string "VNImageOptionProperties"
let _VNNormalizedIdentityRect = !@ (Foreign.foreign_value "VNNormalizedIdentityRect" CGRect.t)
let _VNRecognizedPointGroupKeyAll = new_string "VNRecognizedPointGroupKeyAll"
let _VNVideoProcessingOptionFrameCadence = new_string "VNVideoProcessingOptionFrameCadence"
let _VNVideoProcessingOptionTimeInterval = new_string "VNVideoProcessingOptionTimeInterval"
let _VNVisionVersionNumber = !@ (Foreign.foreign_value "VNVisionVersionNumber" double)
let _VNChiralityLeft = -1
let _VNChiralityRight = 1
let _VNChiralityUnknown = 0
let _VNClassifyImageRequestRevision1 = 1
let _VNCoreMLRequestRevision1 = 1
let _VNDetectBarcodesRequestRevision1 = 1
let _VNDetectBarcodesRequestRevision2 = 2
let _VNDetectContourRequestRevision1 = 1
let _VNDetectDocumentSegmentationRequestRevision1 = 1
let _VNDetectFaceCaptureQualityRequestRevision1 = 1
let _VNDetectFaceCaptureQualityRequestRevision2 = 2
let _VNDetectFaceLandmarksRequestRevision1 = 1
let _VNDetectFaceLandmarksRequestRevision2 = 2
let _VNDetectFaceLandmarksRequestRevision3 = 3
let _VNDetectFaceRectanglesRequestRevision1 = 1
let _VNDetectFaceRectanglesRequestRevision2 = 2
let _VNDetectFaceRectanglesRequestRevision3 = 3
let _VNDetectHorizonRequestRevision1 = 1
let _VNDetectHumanBodyPoseRequestRevision1 = 1
let _VNDetectHumanHandPoseRequestRevision1 = 1
let _VNDetectHumanRectanglesRequestRevision1 = 1
let _VNDetectHumanRectanglesRequestRevision2 = 2
let _VNDetectRectanglesRequestRevision1 = 1
let _VNDetectTextRectanglesRequestRevision1 = 1
let _VNDetectTrajectoriesRequestRevision1 = 1
let _VNElementTypeDouble = 2
let _VNElementTypeFloat = 1
let _VNElementTypeUnknown = 0
let _VNErrorDataUnavailable = 17
let _VNErrorIOError = 6
let _VNErrorInternalError = 9
let _VNErrorInvalidArgument = 14
let _VNErrorInvalidFormat = 2
let _VNErrorInvalidImage = 13
let _VNErrorInvalidModel = 15
let _VNErrorInvalidOperation = 12
let _VNErrorInvalidOption = 5
let _VNErrorMissingOption = 7
let _VNErrorNotImplemented = 8
let _VNErrorOK = 0
let _VNErrorOperationFailed = 3
let _VNErrorOutOfBoundsError = 4
let _VNErrorOutOfMemory = 10
let _VNErrorRequestCancelled = 1
let _VNErrorTimeStampNotFound = 18
let _VNErrorUnknownError = 11
let _VNErrorUnsupportedRequest = 19
let _VNErrorUnsupportedRevision = 16
let _VNGenerateAttentionBasedSaliencyImageRequestRevision1 = 1
let _VNGenerateImageFeaturePrintRequestRevision1 = 1
let _VNGenerateObjectnessBasedSaliencyImageRequestRevision1 = 1
let _VNGenerateOpticalFlowRequestComputationAccuracyHigh = 2
let _VNGenerateOpticalFlowRequestComputationAccuracyLow = 0
let _VNGenerateOpticalFlowRequestComputationAccuracyMedium = 1
let _VNGenerateOpticalFlowRequestComputationAccuracyVeryHigh = 3
let _VNGenerateOpticalFlowRequestRevision1 = 1
let _VNGeneratePersonSegmentationRequestQualityLevelAccurate = 0
let _VNGeneratePersonSegmentationRequestQualityLevelBalanced = 1
let _VNGeneratePersonSegmentationRequestQualityLevelFast = 2
let _VNGeneratePersonSegmentationRequestRevision1 = 1
let _VNHomographicImageRegistrationRequestRevision1 = 1
let _VNImageCropAndScaleOptionCenterCrop = 0
let _VNImageCropAndScaleOptionScaleFill = 2
let _VNImageCropAndScaleOptionScaleFit = 1
let _VNRecognizeAnimalsRequestRevision1 = 1
let _VNRecognizeAnimalsRequestRevision2 = 2
let _VNRecognizeTextRequestRevision1 = 1
let _VNRecognizeTextRequestRevision2 = 2
let _VNRequestFaceLandmarksConstellation65Points = 1
let _VNRequestFaceLandmarksConstellation76Points = 2
let _VNRequestFaceLandmarksConstellationNotDefined = 0
let _VNRequestRevisionUnspecified = 0
let _VNRequestTextRecognitionLevelAccurate = 0
let _VNRequestTextRecognitionLevelFast = 1
let _VNRequestTrackingLevelAccurate = 0
let _VNRequestTrackingLevelFast = 1
let _VNTrackObjectRequestRevision1 = 1
let _VNTrackObjectRequestRevision2 = 2
let _VNTrackRectangleRequestRevision1 = 1
let _VNTranslationalImageRegistrationRequestRevision1 = 1
let _VNElementTypeSize = Foreign.foreign "VNElementTypeSize" (ullong @-> returning ullong)
let _VNImagePointForFaceLandmarkPoint = Foreign.foreign "VNImagePointForFaceLandmarkPoint" (double @-> CGRect.t @-> ullong @-> ullong @-> returning CGPoint.t)
let _VNImagePointForNormalizedPoint = Foreign.foreign "VNImagePointForNormalizedPoint" (CGPoint.t @-> ullong @-> ullong @-> returning CGPoint.t)
let _VNImagePointForNormalizedPointUsingRegionOfInterest = Foreign.foreign "VNImagePointForNormalizedPointUsingRegionOfInterest" (CGPoint.t @-> ullong @-> ullong @-> CGRect.t @-> returning CGPoint.t)
let _VNImageRectForNormalizedRect = Foreign.foreign "VNImageRectForNormalizedRect" (CGRect.t @-> ullong @-> ullong @-> returning CGRect.t)
let _VNImageRectForNormalizedRectUsingRegionOfInterest = Foreign.foreign "VNImageRectForNormalizedRectUsingRegionOfInterest" (CGRect.t @-> ullong @-> ullong @-> CGRect.t @-> returning CGRect.t)
let _VNNormalizedFaceBoundingBoxPointForLandmarkPoint = Foreign.foreign "VNNormalizedFaceBoundingBoxPointForLandmarkPoint" (double @-> CGRect.t @-> ullong @-> ullong @-> returning CGPoint.t)
let _VNNormalizedPointForImagePoint = Foreign.foreign "VNNormalizedPointForImagePoint" (CGPoint.t @-> ullong @-> ullong @-> returning CGPoint.t)
let _VNNormalizedPointForImagePointUsingRegionOfInterest = Foreign.foreign "VNNormalizedPointForImagePointUsingRegionOfInterest" (CGPoint.t @-> ullong @-> ullong @-> CGRect.t @-> returning CGPoint.t)
let _VNNormalizedRectForImageRect = Foreign.foreign "VNNormalizedRectForImageRect" (CGRect.t @-> ullong @-> ullong @-> returning CGRect.t)
let _VNNormalizedRectForImageRectUsingRegionOfInterest = Foreign.foreign "VNNormalizedRectForImageRectUsingRegionOfInterest" (CGRect.t @-> ullong @-> ullong @-> CGRect.t @-> returning CGRect.t)
let _VNNormalizedRectIsIdentityRect = Foreign.foreign "VNNormalizedRectIsIdentityRect" (CGRect.t @-> returning bool)
