(* auto-generated, do not modify *)

[@@@ocaml.warning "-33"]
open Runtime
open Objc

open CoreFoundation

let _NSAddedPersistentStoresKey = new_string "NSAddedPersistentStoresKey"
let _NSAffectedObjectsErrorKey = new_string "NSAffectedObjectsErrorKey"
let _NSAffectedStoresErrorKey = new_string "NSAffectedStoresErrorKey"
let _NSBinaryExternalRecordType = new_string "NSBinaryExternalRecordType"
let _NSBinaryStoreInsecureDecodingCompatibilityOption = new_string "NSBinaryStoreInsecureDecodingCompatibilityOption"
let _NSBinaryStoreSecureDecodingClasses = new_string "NSBinaryStoreSecureDecodingClasses"
let _NSBinaryStoreType = new_string "NSBinaryStoreType"
let _NSCoreDataCoreSpotlightDelegateIndexDidUpdateNotification = new_string "NSCoreDataCoreSpotlightDelegateIndexDidUpdateNotification"
let _NSCoreDataCoreSpotlightExporter = new_string "NSCoreDataCoreSpotlightExporter"
let _NSCoreDataVersionNumber = !@ (Foreign.foreign_value "NSCoreDataVersionNumber" double)
let _NSDeletedObjectIDsKey = new_string "NSDeletedObjectIDsKey"
let _NSDeletedObjectsKey = new_string "NSDeletedObjectsKey"
let _NSDetailedErrorsKey = new_string "NSDetailedErrorsKey"
let _NSEntityNameInPathKey = new_string "NSEntityNameInPathKey"
let _NSErrorMergePolicy = new_string "NSErrorMergePolicy"
let _NSExternalRecordExtensionOption = new_string "NSExternalRecordExtensionOption"
let _NSExternalRecordsDirectoryOption = new_string "NSExternalRecordsDirectoryOption"
let _NSExternalRecordsFileFormatOption = new_string "NSExternalRecordsFileFormatOption"
let _NSIgnorePersistentStoreVersioningOption = new_string "NSIgnorePersistentStoreVersioningOption"
let _NSInMemoryStoreType = new_string "NSInMemoryStoreType"
let _NSInferMappingModelAutomaticallyOption = new_string "NSInferMappingModelAutomaticallyOption"
let _NSInsertedObjectIDsKey = new_string "NSInsertedObjectIDsKey"
let _NSInsertedObjectsKey = new_string "NSInsertedObjectsKey"
let _NSInvalidatedAllObjectsKey = new_string "NSInvalidatedAllObjectsKey"
let _NSInvalidatedObjectIDsKey = new_string "NSInvalidatedObjectIDsKey"
let _NSInvalidatedObjectsKey = new_string "NSInvalidatedObjectsKey"
let _NSManagedObjectContextDidMergeChangesObjectIDsNotification = new_string "NSManagedObjectContextDidMergeChangesObjectIDsNotification"
let _NSManagedObjectContextDidSaveNotification = new_string "NSManagedObjectContextDidSaveNotification"
let _NSManagedObjectContextDidSaveObjectIDsNotification = new_string "NSManagedObjectContextDidSaveObjectIDsNotification"
let _NSManagedObjectContextObjectsDidChangeNotification = new_string "NSManagedObjectContextObjectsDidChangeNotification"
let _NSManagedObjectContextQueryGenerationKey = new_string "NSManagedObjectContextQueryGenerationKey"
let _NSManagedObjectContextWillSaveNotification = new_string "NSManagedObjectContextWillSaveNotification"
let _NSMergeByPropertyObjectTrumpMergePolicy = new_string "NSMergeByPropertyObjectTrumpMergePolicy"
let _NSMergeByPropertyStoreTrumpMergePolicy = new_string "NSMergeByPropertyStoreTrumpMergePolicy"
let _NSMigratePersistentStoresAutomaticallyOption = new_string "NSMigratePersistentStoresAutomaticallyOption"
let _NSMigrationDestinationObjectKey = new_string "NSMigrationDestinationObjectKey"
let _NSMigrationEntityMappingKey = new_string "NSMigrationEntityMappingKey"
let _NSMigrationEntityPolicyKey = new_string "NSMigrationEntityPolicyKey"
let _NSMigrationManagerKey = new_string "NSMigrationManagerKey"
let _NSMigrationPropertyMappingKey = new_string "NSMigrationPropertyMappingKey"
let _NSMigrationSourceObjectKey = new_string "NSMigrationSourceObjectKey"
let _NSModelPathKey = new_string "NSModelPathKey"
let _NSObjectURIKey = new_string "NSObjectURIKey"
let _NSOverwriteMergePolicy = new_string "NSOverwriteMergePolicy"
let _NSPersistentCloudKitContainerEventChangedNotification = new_string "NSPersistentCloudKitContainerEventChangedNotification"
let _NSPersistentCloudKitContainerEventUserInfoKey = new_string "NSPersistentCloudKitContainerEventUserInfoKey"
let _NSPersistentHistoryTokenKey = new_string "NSPersistentHistoryTokenKey"
let _NSPersistentHistoryTrackingKey = new_string "NSPersistentHistoryTrackingKey"
let _NSPersistentStoreConnectionPoolMaxSizeKey = new_string "NSPersistentStoreConnectionPoolMaxSizeKey"
let _NSPersistentStoreCoordinatorStoresDidChangeNotification = new_string "NSPersistentStoreCoordinatorStoresDidChangeNotification"
let _NSPersistentStoreCoordinatorStoresWillChangeNotification = new_string "NSPersistentStoreCoordinatorStoresWillChangeNotification"
let _NSPersistentStoreCoordinatorWillRemoveStoreNotification = new_string "NSPersistentStoreCoordinatorWillRemoveStoreNotification"
let _NSPersistentStoreDidImportUbiquitousContentChangesNotification = new_string "NSPersistentStoreDidImportUbiquitousContentChangesNotification"
let _NSPersistentStoreFileProtectionKey = new_string "NSPersistentStoreFileProtectionKey"
let _NSPersistentStoreForceDestroyOption = new_string "NSPersistentStoreForceDestroyOption"
let _NSPersistentStoreOSCompatibility = new_string "NSPersistentStoreOSCompatibility"
let _NSPersistentStoreRebuildFromUbiquitousContentOption = new_string "NSPersistentStoreRebuildFromUbiquitousContentOption"
let _NSPersistentStoreRemoteChangeNotification = new_string "NSPersistentStoreRemoteChangeNotification"
let _NSPersistentStoreRemoteChangeNotificationPostOptionKey = new_string "NSPersistentStoreRemoteChangeNotificationPostOptionKey"
let _NSPersistentStoreRemoveUbiquitousMetadataOption = new_string "NSPersistentStoreRemoveUbiquitousMetadataOption"
let _NSPersistentStoreSaveConflictsErrorKey = new_string "NSPersistentStoreSaveConflictsErrorKey"
let _NSPersistentStoreTimeoutOption = new_string "NSPersistentStoreTimeoutOption"
let _NSPersistentStoreURLKey = new_string "NSPersistentStoreURLKey"
let _NSPersistentStoreUbiquitousContainerIdentifierKey = new_string "NSPersistentStoreUbiquitousContainerIdentifierKey"
let _NSPersistentStoreUbiquitousContentNameKey = new_string "NSPersistentStoreUbiquitousContentNameKey"
let _NSPersistentStoreUbiquitousContentURLKey = new_string "NSPersistentStoreUbiquitousContentURLKey"
let _NSPersistentStoreUbiquitousPeerTokenOption = new_string "NSPersistentStoreUbiquitousPeerTokenOption"
let _NSPersistentStoreUbiquitousTransitionTypeKey = new_string "NSPersistentStoreUbiquitousTransitionTypeKey"
let _NSReadOnlyPersistentStoreOption = new_string "NSReadOnlyPersistentStoreOption"
let _NSRefreshedObjectIDsKey = new_string "NSRefreshedObjectIDsKey"
let _NSRefreshedObjectsKey = new_string "NSRefreshedObjectsKey"
let _NSRemovedPersistentStoresKey = new_string "NSRemovedPersistentStoresKey"
let _NSRollbackMergePolicy = new_string "NSRollbackMergePolicy"
let _NSSQLiteAnalyzeOption = new_string "NSSQLiteAnalyzeOption"
let _NSSQLiteErrorDomain = new_string "NSSQLiteErrorDomain"
let _NSSQLiteManualVacuumOption = new_string "NSSQLiteManualVacuumOption"
let _NSSQLitePragmasOption = new_string "NSSQLitePragmasOption"
let _NSSQLiteStoreType = new_string "NSSQLiteStoreType"
let _NSStoreModelVersionHashesKey = new_string "NSStoreModelVersionHashesKey"
let _NSStoreModelVersionIdentifiersKey = new_string "NSStoreModelVersionIdentifiersKey"
let _NSStorePathKey = new_string "NSStorePathKey"
let _NSStoreTypeKey = new_string "NSStoreTypeKey"
let _NSStoreUUIDInPathKey = new_string "NSStoreUUIDInPathKey"
let _NSStoreUUIDKey = new_string "NSStoreUUIDKey"
let _NSUUIDChangedPersistentStoresKey = new_string "NSUUIDChangedPersistentStoresKey"
let _NSUpdatedObjectIDsKey = new_string "NSUpdatedObjectIDsKey"
let _NSUpdatedObjectsKey = new_string "NSUpdatedObjectsKey"
let _NSValidateXMLStoreOption = new_string "NSValidateXMLStoreOption"
let _NSValidationKeyErrorKey = new_string "NSValidationKeyErrorKey"
let _NSValidationObjectErrorKey = new_string "NSValidationObjectErrorKey"
let _NSValidationPredicateErrorKey = new_string "NSValidationPredicateErrorKey"
let _NSValidationValueErrorKey = new_string "NSValidationValueErrorKey"
let _NSXMLExternalRecordType = new_string "NSXMLExternalRecordType"
let _NSXMLStoreType = new_string "NSXMLStoreType"
let _NSAddEntityMappingType = 2
let _NSBatchDeleteRequestType = 7
let _NSBatchDeleteResultTypeCount = 2
let _NSBatchDeleteResultTypeObjectIDs = 1
let _NSBatchDeleteResultTypeStatusOnly = 0
let _NSBatchInsertRequestResultTypeCount = 2
let _NSBatchInsertRequestResultTypeObjectIDs = 1
let _NSBatchInsertRequestResultTypeStatusOnly = 0
let _NSBatchInsertRequestType = 5
let _NSBatchUpdateRequestType = 6
let _NSBinaryDataAttributeType = 1000
let _NSBooleanAttributeType = 800
let _NSCascadeDeleteRule = 2
let _NSConfinementConcurrencyType = 0
let _NSCopyEntityMappingType = 4
let _NSCoreDataError = 134060
let _NSCoreDataVersionNumber10_10 = 526.000000
let _NSCoreDataVersionNumber10_10_2 = 526.100000
let _NSCoreDataVersionNumber10_10_3 = 526.200000
let _NSCoreDataVersionNumber10_11 = 640.000000
let _NSCoreDataVersionNumber10_11_3 = 641.300000
let _NSCoreDataVersionNumber10_4 = 46.000000
let _NSCoreDataVersionNumber10_4_3 = 77.000000
let _NSCoreDataVersionNumber10_5 = 185.000000
let _NSCoreDataVersionNumber10_5_3 = 186.000000
let _NSCoreDataVersionNumber10_6 = 246.000000
let _NSCoreDataVersionNumber10_6_2 = 250.000000
let _NSCoreDataVersionNumber10_6_3 = 251.000000
let _NSCoreDataVersionNumber10_7 = 358.400000
let _NSCoreDataVersionNumber10_7_2 = 358.120000
let _NSCoreDataVersionNumber10_7_3 = 358.130000
let _NSCoreDataVersionNumber10_7_4 = 358.140000
let _NSCoreDataVersionNumber10_8 = 407.500000
let _NSCoreDataVersionNumber10_8_2 = 407.700000
let _NSCoreDataVersionNumber10_9 = 481.000000
let _NSCoreDataVersionNumber10_9_2 = 481.100000
let _NSCoreDataVersionNumber10_9_3 = 481.300000
let _NSCoreDataVersionNumber_iPhoneOS_3_0 = 241.000000
let _NSCoreDataVersionNumber_iPhoneOS_3_1 = 248.000000
let _NSCoreDataVersionNumber_iPhoneOS_3_2 = 310.200000
let _NSCoreDataVersionNumber_iPhoneOS_4_0 = 320.500000
let _NSCoreDataVersionNumber_iPhoneOS_4_1 = 320.110000
let _NSCoreDataVersionNumber_iPhoneOS_4_2 = 320.150000
let _NSCoreDataVersionNumber_iPhoneOS_4_3 = 320.170000
let _NSCoreDataVersionNumber_iPhoneOS_5_0 = 386.100000
let _NSCoreDataVersionNumber_iPhoneOS_5_1 = 386.500000
let _NSCoreDataVersionNumber_iPhoneOS_6_0 = 419.000000
let _NSCoreDataVersionNumber_iPhoneOS_6_1 = 419.100000
let _NSCoreDataVersionNumber_iPhoneOS_7_0 = 479.100000
let _NSCoreDataVersionNumber_iPhoneOS_7_1 = 479.300000
let _NSCoreDataVersionNumber_iPhoneOS_8_0 = 519.000000
let _NSCoreDataVersionNumber_iPhoneOS_8_3 = 519.150000
let _NSCoreDataVersionNumber_iPhoneOS_9_0 = 640.000000
let _NSCoreDataVersionNumber_iPhoneOS_9_2 = 641.400000
let _NSCoreDataVersionNumber_iPhoneOS_9_3 = 641.600000
let _NSCountResultType = 4
let _NSCustomEntityMappingType = 1
let _NSDateAttributeType = 900
let _NSDecimalAttributeType = 400
let _NSDenyDeleteRule = 3
let _NSDictionaryResultType = 2
let _NSDoubleAttributeType = 500
let _NSEntityMigrationPolicyError = 134170
let _NSErrorMergePolicyType = 0
let _NSExternalRecordImportError = 134200
let _NSFetchIndexElementTypeBinary = 0
let _NSFetchIndexElementTypeRTree = 1
let _NSFetchRequestExpressionType = 50
let _NSFetchRequestType = 1
let _NSFetchedResultsChangeDelete = 2
let _NSFetchedResultsChangeInsert = 1
let _NSFetchedResultsChangeMove = 3
let _NSFetchedResultsChangeUpdate = 4
let _NSFloatAttributeType = 600
let _NSInferredMappingModelError = 134190
let _NSInteger16AttributeType = 100
let _NSInteger32AttributeType = 200
let _NSInteger64AttributeType = 300
let _NSMainQueueConcurrencyType = 2
let _NSManagedObjectConstraintMergeError = 133021
let _NSManagedObjectConstraintValidationError = 1551
let _NSManagedObjectContextLockingError = 132000
let _NSManagedObjectExternalRelationshipError = 133010
let _NSManagedObjectIDResultType = 1
let _NSManagedObjectMergeError = 133020
let _NSManagedObjectReferentialIntegrityError = 133000
let _NSManagedObjectResultType = 0
let _NSManagedObjectValidationError = 1550
let _NSMergeByPropertyObjectTrumpMergePolicyType = 2
let _NSMergeByPropertyStoreTrumpMergePolicyType = 1
let _NSMigrationCancelledError = 134120
let _NSMigrationConstraintViolationError = 134111
let _NSMigrationError = 134110
let _NSMigrationManagerDestinationStoreError = 134160
let _NSMigrationManagerSourceStoreError = 134150
let _NSMigrationMissingMappingModelError = 134140
let _NSMigrationMissingSourceModelError = 134130
let _NSNoActionDeleteRule = 0
let _NSNullifyDeleteRule = 1
let _NSObjectIDAttributeType = 2000
let _NSOverwriteMergePolicyType = 3
let _NSPersistentCloudKitContainerEventResultTypeCountEvents = 1
let _NSPersistentCloudKitContainerEventResultTypeEvents = 0
let _NSPersistentCloudKitContainerEventTypeExport = 2
let _NSPersistentCloudKitContainerEventTypeImport = 1
let _NSPersistentCloudKitContainerEventTypeSetup = 0
let _NSPersistentCloudKitContainerSchemaInitializationOptionsDryRun = 2
let _NSPersistentCloudKitContainerSchemaInitializationOptionsNone = 0
let _NSPersistentCloudKitContainerSchemaInitializationOptionsPrintSchema = 4
let _NSPersistentHistoryChangeTypeDelete = 2
let _NSPersistentHistoryChangeTypeInsert = 0
let _NSPersistentHistoryChangeTypeUpdate = 1
let _NSPersistentHistoryResultTypeChangesOnly = 4
let _NSPersistentHistoryResultTypeCount = 2
let _NSPersistentHistoryResultTypeObjectIDs = 1
let _NSPersistentHistoryResultTypeStatusOnly = 0
let _NSPersistentHistoryResultTypeTransactionsAndChanges = 5
let _NSPersistentHistoryResultTypeTransactionsOnly = 3
let _NSPersistentHistoryTokenExpiredError = 134301
let _NSPersistentStoreCoordinatorLockingError = 132010
let _NSPersistentStoreIncompatibleSchemaError = 134020
let _NSPersistentStoreIncompatibleVersionHashError = 134100
let _NSPersistentStoreIncompleteSaveError = 134040
let _NSPersistentStoreInvalidTypeError = 134000
let _NSPersistentStoreOpenError = 134080
let _NSPersistentStoreOperationError = 134070
let _NSPersistentStoreSaveConflictsError = 134050
let _NSPersistentStoreSaveError = 134030
let _NSPersistentStoreTimeoutError = 134090
let _NSPersistentStoreTypeMismatchError = 134010
let _NSPersistentStoreUbiquitousTransitionTypeAccountAdded = 1
let _NSPersistentStoreUbiquitousTransitionTypeAccountRemoved = 2
let _NSPersistentStoreUbiquitousTransitionTypeContentRemoved = 3
let _NSPersistentStoreUbiquitousTransitionTypeInitialImportCompleted = 4
let _NSPersistentStoreUnsupportedRequestTypeError = 134091
let _NSPrivateQueueConcurrencyType = 1
let _NSRemoveEntityMappingType = 3
let _NSRollbackMergePolicyType = 4
let _NSSQLiteError = 134180
let _NSSaveRequestType = 2
let _NSSnapshotEventMergePolicy = 64
let _NSSnapshotEventRefresh = 32
let _NSSnapshotEventRollback = 16
let _NSSnapshotEventUndoDeletion = 4
let _NSSnapshotEventUndoInsertion = 2
let _NSSnapshotEventUndoUpdate = 8
let _NSStatusOnlyResultType = 0
let _NSStringAttributeType = 700
let _NSTransformEntityMappingType = 5
let _NSTransformableAttributeType = 1800
let _NSURIAttributeType = 1200
let _NSUUIDAttributeType = 1100
let _NSUndefinedAttributeType = 0
let _NSUndefinedEntityMappingType = 0
let _NSUpdatedObjectIDsResultType = 1
let _NSUpdatedObjectsCountResultType = 2
let _NSValidationDateTooLateError = 1630
let _NSValidationDateTooSoonError = 1640
let _NSValidationInvalidDateError = 1650
let _NSValidationInvalidURIError = 1690
let _NSValidationMissingMandatoryPropertyError = 1570
let _NSValidationMultipleErrorsError = 1560
let _NSValidationNumberTooLargeError = 1610
let _NSValidationNumberTooSmallError = 1620
let _NSValidationRelationshipDeniedDeleteError = 1600
let _NSValidationRelationshipExceedsMaximumCountError = 1590
let _NSValidationRelationshipLacksMinimumCountError = 1580
let _NSValidationStringPatternMatchingError = 1680
let _NSValidationStringTooLongError = 1660
let _NSValidationStringTooShortError = 1670
