(* auto-generated, do not modify *)

open Runtime
open Objc

[@@@ocaml.warning "-33"]
open Foundation
open CoreAnimation

module CVDisplayLinkRef = struct
  let t = (ptr CVDisplayLink.t)
end

module CVMetalTextureCacheRef = struct
  let t = (ptr CVMetalTextureCache.t)
end

module CVOpenGLBufferPoolRef = struct
  let t = (ptr CVOpenGLBufferPool.t)
end

module CVOpenGLTextureCacheRef = struct
  let t = (ptr CVOpenGLTextureCache.t)
end

module CVPixelBufferPoolRef = struct
  let t = (ptr CVPixelBufferPool.t)
end

module CVBuffer = struct
  let t : [`CVBuffer] structure typ = structure "CVBuffer"
end
module CVBufferRef = struct
  let t = (ptr CVBuffer.t)
end

let kCVBufferMovieTimeKey = !@ (Foreign.foreign_value "kCVBufferMovieTimeKey" (ptr CFString.t))
let kCVBufferNonPropagatedAttachmentsKey = !@ (Foreign.foreign_value "kCVBufferNonPropagatedAttachmentsKey" (ptr CFString.t))
let kCVBufferPropagatedAttachmentsKey = !@ (Foreign.foreign_value "kCVBufferPropagatedAttachmentsKey" (ptr CFString.t))
let kCVBufferTimeScaleKey = !@ (Foreign.foreign_value "kCVBufferTimeScaleKey" (ptr CFString.t))
let kCVBufferTimeValueKey = !@ (Foreign.foreign_value "kCVBufferTimeValueKey" (ptr CFString.t))
let kCVImageBufferAlphaChannelIsOpaque = !@ (Foreign.foreign_value "kCVImageBufferAlphaChannelIsOpaque" (ptr CFString.t))
let kCVImageBufferAlphaChannelModeKey = !@ (Foreign.foreign_value "kCVImageBufferAlphaChannelModeKey" (ptr CFString.t))
let kCVImageBufferAlphaChannelMode_PremultipliedAlpha = !@ (Foreign.foreign_value "kCVImageBufferAlphaChannelMode_PremultipliedAlpha" (ptr CFString.t))
let kCVImageBufferAlphaChannelMode_StraightAlpha = !@ (Foreign.foreign_value "kCVImageBufferAlphaChannelMode_StraightAlpha" (ptr CFString.t))
let kCVImageBufferAmbientViewingEnvironmentKey = !@ (Foreign.foreign_value "kCVImageBufferAmbientViewingEnvironmentKey" (ptr CFString.t))
let kCVImageBufferCGColorSpaceKey = !@ (Foreign.foreign_value "kCVImageBufferCGColorSpaceKey" (ptr CFString.t))
let kCVImageBufferChromaLocationBottomFieldKey = !@ (Foreign.foreign_value "kCVImageBufferChromaLocationBottomFieldKey" (ptr CFString.t))
let kCVImageBufferChromaLocationTopFieldKey = !@ (Foreign.foreign_value "kCVImageBufferChromaLocationTopFieldKey" (ptr CFString.t))
let kCVImageBufferChromaLocation_Bottom = !@ (Foreign.foreign_value "kCVImageBufferChromaLocation_Bottom" (ptr CFString.t))
let kCVImageBufferChromaLocation_BottomLeft = !@ (Foreign.foreign_value "kCVImageBufferChromaLocation_BottomLeft" (ptr CFString.t))
let kCVImageBufferChromaLocation_Center = !@ (Foreign.foreign_value "kCVImageBufferChromaLocation_Center" (ptr CFString.t))
let kCVImageBufferChromaLocation_DV420 = !@ (Foreign.foreign_value "kCVImageBufferChromaLocation_DV420" (ptr CFString.t))
let kCVImageBufferChromaLocation_Left = !@ (Foreign.foreign_value "kCVImageBufferChromaLocation_Left" (ptr CFString.t))
let kCVImageBufferChromaLocation_Top = !@ (Foreign.foreign_value "kCVImageBufferChromaLocation_Top" (ptr CFString.t))
let kCVImageBufferChromaLocation_TopLeft = !@ (Foreign.foreign_value "kCVImageBufferChromaLocation_TopLeft" (ptr CFString.t))
let kCVImageBufferChromaSubsamplingKey = !@ (Foreign.foreign_value "kCVImageBufferChromaSubsamplingKey" (ptr CFString.t))
let kCVImageBufferChromaSubsampling_411 = !@ (Foreign.foreign_value "kCVImageBufferChromaSubsampling_411" (ptr CFString.t))
let kCVImageBufferChromaSubsampling_420 = !@ (Foreign.foreign_value "kCVImageBufferChromaSubsampling_420" (ptr CFString.t))
let kCVImageBufferChromaSubsampling_422 = !@ (Foreign.foreign_value "kCVImageBufferChromaSubsampling_422" (ptr CFString.t))
let kCVImageBufferCleanApertureHeightKey = !@ (Foreign.foreign_value "kCVImageBufferCleanApertureHeightKey" (ptr CFString.t))
let kCVImageBufferCleanApertureHorizontalOffsetKey = !@ (Foreign.foreign_value "kCVImageBufferCleanApertureHorizontalOffsetKey" (ptr CFString.t))
let kCVImageBufferCleanApertureKey = !@ (Foreign.foreign_value "kCVImageBufferCleanApertureKey" (ptr CFString.t))
let kCVImageBufferCleanApertureVerticalOffsetKey = !@ (Foreign.foreign_value "kCVImageBufferCleanApertureVerticalOffsetKey" (ptr CFString.t))
let kCVImageBufferCleanApertureWidthKey = !@ (Foreign.foreign_value "kCVImageBufferCleanApertureWidthKey" (ptr CFString.t))
let kCVImageBufferColorPrimariesKey = !@ (Foreign.foreign_value "kCVImageBufferColorPrimariesKey" (ptr CFString.t))
let kCVImageBufferColorPrimaries_DCI_P3 = !@ (Foreign.foreign_value "kCVImageBufferColorPrimaries_DCI_P3" (ptr CFString.t))
let kCVImageBufferColorPrimaries_EBU_3213 = !@ (Foreign.foreign_value "kCVImageBufferColorPrimaries_EBU_3213" (ptr CFString.t))
let kCVImageBufferColorPrimaries_ITU_R_2020 = !@ (Foreign.foreign_value "kCVImageBufferColorPrimaries_ITU_R_2020" (ptr CFString.t))
let kCVImageBufferColorPrimaries_ITU_R_709_2 = !@ (Foreign.foreign_value "kCVImageBufferColorPrimaries_ITU_R_709_2" (ptr CFString.t))
let kCVImageBufferColorPrimaries_P22 = !@ (Foreign.foreign_value "kCVImageBufferColorPrimaries_P22" (ptr CFString.t))
let kCVImageBufferColorPrimaries_P3_D65 = !@ (Foreign.foreign_value "kCVImageBufferColorPrimaries_P3_D65" (ptr CFString.t))
let kCVImageBufferColorPrimaries_SMPTE_C = !@ (Foreign.foreign_value "kCVImageBufferColorPrimaries_SMPTE_C" (ptr CFString.t))
let kCVImageBufferContentLightLevelInfoKey = !@ (Foreign.foreign_value "kCVImageBufferContentLightLevelInfoKey" (ptr CFString.t))
let kCVImageBufferDisplayDimensionsKey = !@ (Foreign.foreign_value "kCVImageBufferDisplayDimensionsKey" (ptr CFString.t))
let kCVImageBufferDisplayHeightKey = !@ (Foreign.foreign_value "kCVImageBufferDisplayHeightKey" (ptr CFString.t))
let kCVImageBufferDisplayWidthKey = !@ (Foreign.foreign_value "kCVImageBufferDisplayWidthKey" (ptr CFString.t))
let kCVImageBufferFieldCountKey = !@ (Foreign.foreign_value "kCVImageBufferFieldCountKey" (ptr CFString.t))
let kCVImageBufferFieldDetailKey = !@ (Foreign.foreign_value "kCVImageBufferFieldDetailKey" (ptr CFString.t))
let kCVImageBufferFieldDetailSpatialFirstLineEarly = !@ (Foreign.foreign_value "kCVImageBufferFieldDetailSpatialFirstLineEarly" (ptr CFString.t))
let kCVImageBufferFieldDetailSpatialFirstLineLate = !@ (Foreign.foreign_value "kCVImageBufferFieldDetailSpatialFirstLineLate" (ptr CFString.t))
let kCVImageBufferFieldDetailTemporalBottomFirst = !@ (Foreign.foreign_value "kCVImageBufferFieldDetailTemporalBottomFirst" (ptr CFString.t))
let kCVImageBufferFieldDetailTemporalTopFirst = !@ (Foreign.foreign_value "kCVImageBufferFieldDetailTemporalTopFirst" (ptr CFString.t))
let kCVImageBufferGammaLevelKey = !@ (Foreign.foreign_value "kCVImageBufferGammaLevelKey" (ptr CFString.t))
let kCVImageBufferICCProfileKey = !@ (Foreign.foreign_value "kCVImageBufferICCProfileKey" (ptr CFString.t))
let kCVImageBufferMasteringDisplayColorVolumeKey = !@ (Foreign.foreign_value "kCVImageBufferMasteringDisplayColorVolumeKey" (ptr CFString.t))
let kCVImageBufferPixelAspectRatioHorizontalSpacingKey = !@ (Foreign.foreign_value "kCVImageBufferPixelAspectRatioHorizontalSpacingKey" (ptr CFString.t))
let kCVImageBufferPixelAspectRatioKey = !@ (Foreign.foreign_value "kCVImageBufferPixelAspectRatioKey" (ptr CFString.t))
let kCVImageBufferPixelAspectRatioVerticalSpacingKey = !@ (Foreign.foreign_value "kCVImageBufferPixelAspectRatioVerticalSpacingKey" (ptr CFString.t))
let kCVImageBufferPreferredCleanApertureKey = !@ (Foreign.foreign_value "kCVImageBufferPreferredCleanApertureKey" (ptr CFString.t))
let kCVImageBufferRegionOfInterestKey = !@ (Foreign.foreign_value "kCVImageBufferRegionOfInterestKey" (ptr CFString.t))
let kCVImageBufferTransferFunctionKey = !@ (Foreign.foreign_value "kCVImageBufferTransferFunctionKey" (ptr CFString.t))
let kCVImageBufferTransferFunction_EBU_3213 = !@ (Foreign.foreign_value "kCVImageBufferTransferFunction_EBU_3213" (ptr CFString.t))
let kCVImageBufferTransferFunction_ITU_R_2020 = !@ (Foreign.foreign_value "kCVImageBufferTransferFunction_ITU_R_2020" (ptr CFString.t))
let kCVImageBufferTransferFunction_ITU_R_2100_HLG = !@ (Foreign.foreign_value "kCVImageBufferTransferFunction_ITU_R_2100_HLG" (ptr CFString.t))
let kCVImageBufferTransferFunction_ITU_R_709_2 = !@ (Foreign.foreign_value "kCVImageBufferTransferFunction_ITU_R_709_2" (ptr CFString.t))
let kCVImageBufferTransferFunction_Linear = !@ (Foreign.foreign_value "kCVImageBufferTransferFunction_Linear" (ptr CFString.t))
let kCVImageBufferTransferFunction_SMPTE_240M_1995 = !@ (Foreign.foreign_value "kCVImageBufferTransferFunction_SMPTE_240M_1995" (ptr CFString.t))
let kCVImageBufferTransferFunction_SMPTE_C = !@ (Foreign.foreign_value "kCVImageBufferTransferFunction_SMPTE_C" (ptr CFString.t))
let kCVImageBufferTransferFunction_SMPTE_ST_2084_PQ = !@ (Foreign.foreign_value "kCVImageBufferTransferFunction_SMPTE_ST_2084_PQ" (ptr CFString.t))
let kCVImageBufferTransferFunction_SMPTE_ST_428_1 = !@ (Foreign.foreign_value "kCVImageBufferTransferFunction_SMPTE_ST_428_1" (ptr CFString.t))
let kCVImageBufferTransferFunction_UseGamma = !@ (Foreign.foreign_value "kCVImageBufferTransferFunction_UseGamma" (ptr CFString.t))
let kCVImageBufferTransferFunction_sRGB = !@ (Foreign.foreign_value "kCVImageBufferTransferFunction_sRGB" (ptr CFString.t))
let kCVImageBufferYCbCrMatrixKey = !@ (Foreign.foreign_value "kCVImageBufferYCbCrMatrixKey" (ptr CFString.t))
let kCVImageBufferYCbCrMatrix_DCI_P3 = !@ (Foreign.foreign_value "kCVImageBufferYCbCrMatrix_DCI_P3" (ptr CFString.t))
let kCVImageBufferYCbCrMatrix_ITU_R_2020 = !@ (Foreign.foreign_value "kCVImageBufferYCbCrMatrix_ITU_R_2020" (ptr CFString.t))
let kCVImageBufferYCbCrMatrix_ITU_R_601_4 = !@ (Foreign.foreign_value "kCVImageBufferYCbCrMatrix_ITU_R_601_4" (ptr CFString.t))
let kCVImageBufferYCbCrMatrix_ITU_R_709_2 = !@ (Foreign.foreign_value "kCVImageBufferYCbCrMatrix_ITU_R_709_2" (ptr CFString.t))
let kCVImageBufferYCbCrMatrix_P3_D65 = !@ (Foreign.foreign_value "kCVImageBufferYCbCrMatrix_P3_D65" (ptr CFString.t))
let kCVImageBufferYCbCrMatrix_SMPTE_240M_1995 = !@ (Foreign.foreign_value "kCVImageBufferYCbCrMatrix_SMPTE_240M_1995" (ptr CFString.t))
let kCVIndefiniteTime = !@ (Foreign.foreign_value "kCVIndefiniteTime" CVTime.t)
let kCVMetalTextureCacheMaximumTextureAgeKey = !@ (Foreign.foreign_value "kCVMetalTextureCacheMaximumTextureAgeKey" (ptr CFString.t))
let kCVMetalTextureStorageMode = !@ (Foreign.foreign_value "kCVMetalTextureStorageMode" (ptr CFString.t))
let kCVMetalTextureUsage = !@ (Foreign.foreign_value "kCVMetalTextureUsage" (ptr CFString.t))
let kCVOpenGLBufferHeight = !@ (Foreign.foreign_value "kCVOpenGLBufferHeight" (ptr CFString.t))
let kCVOpenGLBufferInternalFormat = !@ (Foreign.foreign_value "kCVOpenGLBufferInternalFormat" (ptr CFString.t))
let kCVOpenGLBufferMaximumMipmapLevel = !@ (Foreign.foreign_value "kCVOpenGLBufferMaximumMipmapLevel" (ptr CFString.t))
let kCVOpenGLBufferPoolMaximumBufferAgeKey = !@ (Foreign.foreign_value "kCVOpenGLBufferPoolMaximumBufferAgeKey" (ptr CFString.t))
let kCVOpenGLBufferPoolMinimumBufferCountKey = !@ (Foreign.foreign_value "kCVOpenGLBufferPoolMinimumBufferCountKey" (ptr CFString.t))
let kCVOpenGLBufferTarget = !@ (Foreign.foreign_value "kCVOpenGLBufferTarget" (ptr CFString.t))
let kCVOpenGLBufferWidth = !@ (Foreign.foreign_value "kCVOpenGLBufferWidth" (ptr CFString.t))
let kCVOpenGLTextureCacheChromaSamplingModeAutomatic = !@ (Foreign.foreign_value "kCVOpenGLTextureCacheChromaSamplingModeAutomatic" (ptr CFString.t))
let kCVOpenGLTextureCacheChromaSamplingModeBestPerformance = !@ (Foreign.foreign_value "kCVOpenGLTextureCacheChromaSamplingModeBestPerformance" (ptr CFString.t))
let kCVOpenGLTextureCacheChromaSamplingModeHighestQuality = !@ (Foreign.foreign_value "kCVOpenGLTextureCacheChromaSamplingModeHighestQuality" (ptr CFString.t))
let kCVOpenGLTextureCacheChromaSamplingModeKey = !@ (Foreign.foreign_value "kCVOpenGLTextureCacheChromaSamplingModeKey" (ptr CFString.t))
let kCVPixelBufferBytesPerRowAlignmentKey = !@ (Foreign.foreign_value "kCVPixelBufferBytesPerRowAlignmentKey" (ptr CFString.t))
let kCVPixelBufferCGBitmapContextCompatibilityKey = !@ (Foreign.foreign_value "kCVPixelBufferCGBitmapContextCompatibilityKey" (ptr CFString.t))
let kCVPixelBufferCGImageCompatibilityKey = !@ (Foreign.foreign_value "kCVPixelBufferCGImageCompatibilityKey" (ptr CFString.t))
let kCVPixelBufferExtendedPixelsBottomKey = !@ (Foreign.foreign_value "kCVPixelBufferExtendedPixelsBottomKey" (ptr CFString.t))
let kCVPixelBufferExtendedPixelsLeftKey = !@ (Foreign.foreign_value "kCVPixelBufferExtendedPixelsLeftKey" (ptr CFString.t))
let kCVPixelBufferExtendedPixelsRightKey = !@ (Foreign.foreign_value "kCVPixelBufferExtendedPixelsRightKey" (ptr CFString.t))
let kCVPixelBufferExtendedPixelsTopKey = !@ (Foreign.foreign_value "kCVPixelBufferExtendedPixelsTopKey" (ptr CFString.t))
let kCVPixelBufferHeightKey = !@ (Foreign.foreign_value "kCVPixelBufferHeightKey" (ptr CFString.t))
let kCVPixelBufferIOSurfaceCoreAnimationCompatibilityKey = !@ (Foreign.foreign_value "kCVPixelBufferIOSurfaceCoreAnimationCompatibilityKey" (ptr CFString.t))
let kCVPixelBufferIOSurfaceOpenGLESFBOCompatibilityKey = !@ (Foreign.foreign_value "kCVPixelBufferIOSurfaceOpenGLESFBOCompatibilityKey" (ptr CFString.t))
let kCVPixelBufferIOSurfaceOpenGLESTextureCompatibilityKey = !@ (Foreign.foreign_value "kCVPixelBufferIOSurfaceOpenGLESTextureCompatibilityKey" (ptr CFString.t))
let kCVPixelBufferIOSurfaceOpenGLFBOCompatibilityKey = !@ (Foreign.foreign_value "kCVPixelBufferIOSurfaceOpenGLFBOCompatibilityKey" (ptr CFString.t))
let kCVPixelBufferIOSurfaceOpenGLTextureCompatibilityKey = !@ (Foreign.foreign_value "kCVPixelBufferIOSurfaceOpenGLTextureCompatibilityKey" (ptr CFString.t))
let kCVPixelBufferIOSurfacePropertiesKey = !@ (Foreign.foreign_value "kCVPixelBufferIOSurfacePropertiesKey" (ptr CFString.t))
let kCVPixelBufferMemoryAllocatorKey = !@ (Foreign.foreign_value "kCVPixelBufferMemoryAllocatorKey" (ptr CFString.t))
let kCVPixelBufferMetalCompatibilityKey = !@ (Foreign.foreign_value "kCVPixelBufferMetalCompatibilityKey" (ptr CFString.t))
let kCVPixelBufferOpenGLCompatibilityKey = !@ (Foreign.foreign_value "kCVPixelBufferOpenGLCompatibilityKey" (ptr CFString.t))
let kCVPixelBufferOpenGLESCompatibilityKey = !@ (Foreign.foreign_value "kCVPixelBufferOpenGLESCompatibilityKey" (ptr CFString.t))
let kCVPixelBufferOpenGLESTextureCacheCompatibilityKey = !@ (Foreign.foreign_value "kCVPixelBufferOpenGLESTextureCacheCompatibilityKey" (ptr CFString.t))
let kCVPixelBufferOpenGLTextureCacheCompatibilityKey = !@ (Foreign.foreign_value "kCVPixelBufferOpenGLTextureCacheCompatibilityKey" (ptr CFString.t))
let kCVPixelBufferPixelFormatTypeKey = !@ (Foreign.foreign_value "kCVPixelBufferPixelFormatTypeKey" (ptr CFString.t))
let kCVPixelBufferPlaneAlignmentKey = !@ (Foreign.foreign_value "kCVPixelBufferPlaneAlignmentKey" (ptr CFString.t))
let kCVPixelBufferPoolAllocationThresholdKey = !@ (Foreign.foreign_value "kCVPixelBufferPoolAllocationThresholdKey" (ptr CFString.t))
let kCVPixelBufferPoolFreeBufferNotification = !@ (Foreign.foreign_value "kCVPixelBufferPoolFreeBufferNotification" (ptr CFString.t))
let kCVPixelBufferPoolMaximumBufferAgeKey = !@ (Foreign.foreign_value "kCVPixelBufferPoolMaximumBufferAgeKey" (ptr CFString.t))
let kCVPixelBufferPoolMinimumBufferCountKey = !@ (Foreign.foreign_value "kCVPixelBufferPoolMinimumBufferCountKey" (ptr CFString.t))
let kCVPixelBufferProResRAWKey_BlackLevel = !@ (Foreign.foreign_value "kCVPixelBufferProResRAWKey_BlackLevel" (ptr CFString.t))
let kCVPixelBufferProResRAWKey_ColorMatrix = !@ (Foreign.foreign_value "kCVPixelBufferProResRAWKey_ColorMatrix" (ptr CFString.t))
let kCVPixelBufferProResRAWKey_GainFactor = !@ (Foreign.foreign_value "kCVPixelBufferProResRAWKey_GainFactor" (ptr CFString.t))
let kCVPixelBufferProResRAWKey_MetadataExtension = !@ (Foreign.foreign_value "kCVPixelBufferProResRAWKey_MetadataExtension" (ptr CFString.t))
let kCVPixelBufferProResRAWKey_RecommendedCrop = !@ (Foreign.foreign_value "kCVPixelBufferProResRAWKey_RecommendedCrop" (ptr CFString.t))
let kCVPixelBufferProResRAWKey_SenselSitingOffsets = !@ (Foreign.foreign_value "kCVPixelBufferProResRAWKey_SenselSitingOffsets" (ptr CFString.t))
let kCVPixelBufferProResRAWKey_WhiteBalanceBlueFactor = !@ (Foreign.foreign_value "kCVPixelBufferProResRAWKey_WhiteBalanceBlueFactor" (ptr CFString.t))
let kCVPixelBufferProResRAWKey_WhiteBalanceCCT = !@ (Foreign.foreign_value "kCVPixelBufferProResRAWKey_WhiteBalanceCCT" (ptr CFString.t))
let kCVPixelBufferProResRAWKey_WhiteBalanceRedFactor = !@ (Foreign.foreign_value "kCVPixelBufferProResRAWKey_WhiteBalanceRedFactor" (ptr CFString.t))
let kCVPixelBufferProResRAWKey_WhiteLevel = !@ (Foreign.foreign_value "kCVPixelBufferProResRAWKey_WhiteLevel" (ptr CFString.t))
let kCVPixelBufferVersatileBayerKey_BayerPattern = !@ (Foreign.foreign_value "kCVPixelBufferVersatileBayerKey_BayerPattern" (ptr CFString.t))
let kCVPixelBufferWidthKey = !@ (Foreign.foreign_value "kCVPixelBufferWidthKey" (ptr CFString.t))
let kCVPixelFormatBitsPerBlock = !@ (Foreign.foreign_value "kCVPixelFormatBitsPerBlock" (ptr CFString.t))
let kCVPixelFormatBlackBlock = !@ (Foreign.foreign_value "kCVPixelFormatBlackBlock" (ptr CFString.t))
let kCVPixelFormatBlockHeight = !@ (Foreign.foreign_value "kCVPixelFormatBlockHeight" (ptr CFString.t))
let kCVPixelFormatBlockHorizontalAlignment = !@ (Foreign.foreign_value "kCVPixelFormatBlockHorizontalAlignment" (ptr CFString.t))
let kCVPixelFormatBlockVerticalAlignment = !@ (Foreign.foreign_value "kCVPixelFormatBlockVerticalAlignment" (ptr CFString.t))
let kCVPixelFormatBlockWidth = !@ (Foreign.foreign_value "kCVPixelFormatBlockWidth" (ptr CFString.t))
let kCVPixelFormatCGBitmapContextCompatibility = !@ (Foreign.foreign_value "kCVPixelFormatCGBitmapContextCompatibility" (ptr CFString.t))
let kCVPixelFormatCGBitmapInfo = !@ (Foreign.foreign_value "kCVPixelFormatCGBitmapInfo" (ptr CFString.t))
let kCVPixelFormatCGImageCompatibility = !@ (Foreign.foreign_value "kCVPixelFormatCGImageCompatibility" (ptr CFString.t))
let kCVPixelFormatCodecType = !@ (Foreign.foreign_value "kCVPixelFormatCodecType" (ptr CFString.t))
let kCVPixelFormatComponentRange = !@ (Foreign.foreign_value "kCVPixelFormatComponentRange" (ptr CFString.t))
let kCVPixelFormatComponentRange_FullRange = !@ (Foreign.foreign_value "kCVPixelFormatComponentRange_FullRange" (ptr CFString.t))
let kCVPixelFormatComponentRange_VideoRange = !@ (Foreign.foreign_value "kCVPixelFormatComponentRange_VideoRange" (ptr CFString.t))
let kCVPixelFormatComponentRange_WideRange = !@ (Foreign.foreign_value "kCVPixelFormatComponentRange_WideRange" (ptr CFString.t))
let kCVPixelFormatConstant = !@ (Foreign.foreign_value "kCVPixelFormatConstant" (ptr CFString.t))
let kCVPixelFormatContainsAlpha = !@ (Foreign.foreign_value "kCVPixelFormatContainsAlpha" (ptr CFString.t))
let kCVPixelFormatContainsGrayscale = !@ (Foreign.foreign_value "kCVPixelFormatContainsGrayscale" (ptr CFString.t))
let kCVPixelFormatContainsRGB = !@ (Foreign.foreign_value "kCVPixelFormatContainsRGB" (ptr CFString.t))
let kCVPixelFormatContainsYCbCr = !@ (Foreign.foreign_value "kCVPixelFormatContainsYCbCr" (ptr CFString.t))
let kCVPixelFormatFillExtendedPixelsCallback = !@ (Foreign.foreign_value "kCVPixelFormatFillExtendedPixelsCallback" (ptr CFString.t))
let kCVPixelFormatFourCC = !@ (Foreign.foreign_value "kCVPixelFormatFourCC" (ptr CFString.t))
let kCVPixelFormatHorizontalSubsampling = !@ (Foreign.foreign_value "kCVPixelFormatHorizontalSubsampling" (ptr CFString.t))
let kCVPixelFormatName = !@ (Foreign.foreign_value "kCVPixelFormatName" (ptr CFString.t))
let kCVPixelFormatOpenGLCompatibility = !@ (Foreign.foreign_value "kCVPixelFormatOpenGLCompatibility" (ptr CFString.t))
let kCVPixelFormatOpenGLESCompatibility = !@ (Foreign.foreign_value "kCVPixelFormatOpenGLESCompatibility" (ptr CFString.t))
let kCVPixelFormatOpenGLFormat = !@ (Foreign.foreign_value "kCVPixelFormatOpenGLFormat" (ptr CFString.t))
let kCVPixelFormatOpenGLInternalFormat = !@ (Foreign.foreign_value "kCVPixelFormatOpenGLInternalFormat" (ptr CFString.t))
let kCVPixelFormatOpenGLType = !@ (Foreign.foreign_value "kCVPixelFormatOpenGLType" (ptr CFString.t))
let kCVPixelFormatPlanes = !@ (Foreign.foreign_value "kCVPixelFormatPlanes" (ptr CFString.t))
let kCVPixelFormatQDCompatibility = !@ (Foreign.foreign_value "kCVPixelFormatQDCompatibility" (ptr CFString.t))
let kCVPixelFormatVerticalSubsampling = !@ (Foreign.foreign_value "kCVPixelFormatVerticalSubsampling" (ptr CFString.t))
let kCVZeroTime = !@ (Foreign.foreign_value "kCVZeroTime" CVTime.t)
let _COREVIDEO_DECLARE_NULLABILITY = 1
let _COREVIDEO_FALSE = 0
let _COREVIDEO_INCLUDED_IOSURFACE_HEADER_FILE = 1
let _COREVIDEO_SUPPORTS_COLORSPACE = 1
let _COREVIDEO_SUPPORTS_DIRECT3D = 0
let _COREVIDEO_SUPPORTS_DISPLAYLINK = 1
let _COREVIDEO_SUPPORTS_GLES_TEX_IMAGE_IOSURFACE = 1
let _COREVIDEO_SUPPORTS_IOSURFACE = 1
let _COREVIDEO_SUPPORTS_IOSURFACE_PREFETCH = 1
let _COREVIDEO_SUPPORTS_METAL = 1
let _COREVIDEO_SUPPORTS_OPENGL = 1
let _COREVIDEO_SUPPORTS_OPENGLES = 0
let _COREVIDEO_SUPPORTS_PERMANENT_ALLOCATOR = 0
let _COREVIDEO_SUPPORTS_PREFETCH = 1
let _COREVIDEO_TRUE = 1
let _COREVIDEO_USE_DERIVED_ENUMS_FOR_CONSTANTS = 1
let _COREVIDEO_USE_IOSURFACEREF = 0
let kCVAttachmentMode_ShouldNotPropagate = 0
let kCVAttachmentMode_ShouldPropagate = 1
let kCVPixelBufferLock_ReadOnly = 1
let kCVPixelBufferPoolFlushExcessBuffers = 1
let kCVPixelFormatType_128RGBAFloat = 1380410945
let kCVPixelFormatType_14Bayer_BGGR = 1650943796
let kCVPixelFormatType_14Bayer_GBRG = 1734505012
let kCVPixelFormatType_14Bayer_GRBG = 1735549492
let kCVPixelFormatType_14Bayer_RGGB = 1919379252
let kCVPixelFormatType_16BE555 = 16
let kCVPixelFormatType_16BE565 = 1110783541
let kCVPixelFormatType_16Gray = 1647392359
let kCVPixelFormatType_16LE555 = 1278555445
let kCVPixelFormatType_16LE5551 = 892679473
let kCVPixelFormatType_16LE565 = 1278555701
let kCVPixelFormatType_16VersatileBayer = 1651519798
let kCVPixelFormatType_1IndexedGray_WhiteIsZero = 33
let kCVPixelFormatType_1Monochrome = 1
let kCVPixelFormatType_24BGR = 842285639
let kCVPixelFormatType_24RGB = 24
let kCVPixelFormatType_2Indexed = 2
let kCVPixelFormatType_2IndexedGray_WhiteIsZero = 34
let kCVPixelFormatType_30RGB = 1378955371
let kCVPixelFormatType_30RGBLEPackedWideGamut = 1999843442
let kCVPixelFormatType_32ABGR = 1094862674
let kCVPixelFormatType_32ARGB = 32
let kCVPixelFormatType_32AlphaGray = 1647522401
let kCVPixelFormatType_32BGRA = 1111970369
let kCVPixelFormatType_32RGBA = 1380401729
let kCVPixelFormatType_40ARGBLEWideGamut = 1999908961
let kCVPixelFormatType_40ARGBLEWideGamutPremultiplied = 1999908973
let kCVPixelFormatType_420YpCbCr10BiPlanarFullRange = 2019963440
let kCVPixelFormatType_420YpCbCr10BiPlanarVideoRange = 2016686640
let kCVPixelFormatType_420YpCbCr8BiPlanarFullRange = 875704422
let kCVPixelFormatType_420YpCbCr8BiPlanarVideoRange = 875704438
let kCVPixelFormatType_420YpCbCr8Planar = 2033463856
let kCVPixelFormatType_420YpCbCr8PlanarFullRange = 1714696752
let kCVPixelFormatType_420YpCbCr8VideoRange_8A_TriPlanar = 1982882104
let kCVPixelFormatType_422YpCbCr10 = 1983000880
let kCVPixelFormatType_422YpCbCr10BiPlanarFullRange = 2019963442
let kCVPixelFormatType_422YpCbCr10BiPlanarVideoRange = 2016686642
let kCVPixelFormatType_422YpCbCr16 = 1983000886
let kCVPixelFormatType_422YpCbCr16BiPlanarVideoRange = 1937125938
let kCVPixelFormatType_422YpCbCr8 = 846624121
let kCVPixelFormatType_422YpCbCr8BiPlanarFullRange = 875704934
let kCVPixelFormatType_422YpCbCr8BiPlanarVideoRange = 875704950
let kCVPixelFormatType_422YpCbCr8FullRange = 2037741158
let kCVPixelFormatType_422YpCbCr8_yuvs = 2037741171
let kCVPixelFormatType_422YpCbCr_4A_8BiPlanar = 1630697081
let kCVPixelFormatType_4444AYpCbCr16 = 2033463606
let kCVPixelFormatType_4444AYpCbCr8 = 2033463352
let kCVPixelFormatType_4444YpCbCrA8 = 1983131704
let kCVPixelFormatType_4444YpCbCrA8R = 1916022840
let kCVPixelFormatType_444YpCbCr10 = 1983131952
let kCVPixelFormatType_444YpCbCr10BiPlanarFullRange = 2019963956
let kCVPixelFormatType_444YpCbCr10BiPlanarVideoRange = 2016687156
let kCVPixelFormatType_444YpCbCr16BiPlanarVideoRange = 1937126452
let kCVPixelFormatType_444YpCbCr16VideoRange_16A_TriPlanar = 1932812659
let kCVPixelFormatType_444YpCbCr8 = 1983066168
let kCVPixelFormatType_444YpCbCr8BiPlanarFullRange = 875836518
let kCVPixelFormatType_444YpCbCr8BiPlanarVideoRange = 875836534
let kCVPixelFormatType_48RGB = 1647589490
let kCVPixelFormatType_4Indexed = 4
let kCVPixelFormatType_4IndexedGray_WhiteIsZero = 36
let kCVPixelFormatType_64ARGB = 1647719521
let kCVPixelFormatType_64RGBAHalf = 1380411457
let kCVPixelFormatType_64RGBALE = 1815491698
let kCVPixelFormatType_64RGBA_DownscaledProResRAW = 1651521076
let kCVPixelFormatType_8Indexed = 8
let kCVPixelFormatType_8IndexedGray_WhiteIsZero = 40
let kCVPixelFormatType_ARGB2101010LEPacked = 1815162994
let kCVPixelFormatType_DepthFloat16 = 1751410032
let kCVPixelFormatType_DepthFloat32 = 1717855600
let kCVPixelFormatType_DisparityFloat16 = 1751411059
let kCVPixelFormatType_DisparityFloat32 = 1717856627
let kCVPixelFormatType_Lossless_32BGRA = 641877825
let kCVPixelFormatType_Lossless_420YpCbCr10PackedBiPlanarVideoRange = 645428784
let kCVPixelFormatType_Lossless_420YpCbCr8BiPlanarFullRange = 641230384
let kCVPixelFormatType_Lossless_420YpCbCr8BiPlanarVideoRange = 641234480
let kCVPixelFormatType_Lossless_422YpCbCr10PackedBiPlanarVideoRange = 645428786
let kCVPixelFormatType_Lossy_32BGRA = 759318337
let kCVPixelFormatType_Lossy_420YpCbCr10PackedBiPlanarVideoRange = 762869296
let kCVPixelFormatType_Lossy_420YpCbCr8BiPlanarFullRange = 758670896
let kCVPixelFormatType_Lossy_420YpCbCr8BiPlanarVideoRange = 758674992
let kCVPixelFormatType_Lossy_422YpCbCr10PackedBiPlanarVideoRange = 762869298
let kCVPixelFormatType_OneComponent10 = 1278226736
let kCVPixelFormatType_OneComponent12 = 1278226738
let kCVPixelFormatType_OneComponent16 = 1278226742
let kCVPixelFormatType_OneComponent16Half = 1278226536
let kCVPixelFormatType_OneComponent32Float = 1278226534
let kCVPixelFormatType_OneComponent8 = 1278226488
let kCVPixelFormatType_TwoComponent16 = 843264310
let kCVPixelFormatType_TwoComponent16Half = 843264104
let kCVPixelFormatType_TwoComponent32Float = 843264102
let kCVPixelFormatType_TwoComponent8 = 843264056
let kCVReturnAllocationFailed = -6662
let kCVReturnDisplayLinkAlreadyRunning = -6671
let kCVReturnDisplayLinkCallbacksNotSet = -6673
let kCVReturnDisplayLinkNotRunning = -6672
let kCVReturnError = -6660
let kCVReturnFirst = -6660
let kCVReturnInvalidArgument = -6661
let kCVReturnInvalidDisplay = -6670
let kCVReturnInvalidPixelBufferAttributes = -6682
let kCVReturnInvalidPixelFormat = -6680
let kCVReturnInvalidPoolAttributes = -6691
let kCVReturnInvalidSize = -6681
let kCVReturnLast = -6699
let kCVReturnPixelBufferNotMetalCompatible = -6684
let kCVReturnPixelBufferNotOpenGLCompatible = -6683
let kCVReturnPoolAllocationFailed = -6690
let kCVReturnRetry = -6692
let kCVReturnSuccess = 0
let kCVReturnUnsupported = -6663
let kCVReturnWouldExceedAllocationThreshold = -6689
let kCVSMPTETimeRunning = 2
let kCVSMPTETimeType24 = 0
let kCVSMPTETimeType25 = 1
let kCVSMPTETimeType2997 = 4
let kCVSMPTETimeType2997Drop = 5
let kCVSMPTETimeType30 = 3
let kCVSMPTETimeType30Drop = 2
let kCVSMPTETimeType5994 = 7
let kCVSMPTETimeType60 = 6
let kCVSMPTETimeValid = 1
let kCVTimeIsIndefinite = 1
let kCVTimeStampBottomField = 131072
let kCVTimeStampHostTimeValid = 2
let kCVTimeStampIsInterlaced = 196608
let kCVTimeStampRateScalarValid = 16
let kCVTimeStampSMPTETimeValid = 4
let kCVTimeStampTopField = 65536
let kCVTimeStampVideoHostTimeValid = 3
let kCVTimeStampVideoRefreshPeriodValid = 8
let kCVTimeStampVideoTimeValid = 1
let kCVVersatileBayer_BayerPattern_BGGR = 3
let kCVVersatileBayer_BayerPattern_GBRG = 2
let kCVVersatileBayer_BayerPattern_GRBG = 1
let kCVVersatileBayer_BayerPattern_RGGB = 0
let _CVBufferCopyAttachment = Foreign.foreign "CVBufferCopyAttachment" ((ptr CVBuffer.t) @-> (ptr CFString.t) @-> (ptr uint) @-> returning id)
let _CVBufferCopyAttachments = Foreign.foreign "CVBufferCopyAttachments" ((ptr CVBuffer.t) @-> uint @-> returning (ptr CFDictionary.t))
let _CVBufferGetAttachment = Foreign.foreign "CVBufferGetAttachment" ((ptr CVBuffer.t) @-> (ptr CFString.t) @-> (ptr uint) @-> returning id)
let _CVBufferGetAttachments = Foreign.foreign "CVBufferGetAttachments" ((ptr CVBuffer.t) @-> uint @-> returning (ptr CFDictionary.t))
let _CVBufferHasAttachment = Foreign.foreign "CVBufferHasAttachment" ((ptr CVBuffer.t) @-> (ptr CFString.t) @-> returning bool)
let _CVBufferPropagateAttachments = Foreign.foreign "CVBufferPropagateAttachments" ((ptr CVBuffer.t) @-> (ptr CVBuffer.t) @-> returning void)
let _CVBufferRelease = Foreign.foreign "CVBufferRelease" ((ptr CVBuffer.t) @-> returning void)
let _CVBufferRemoveAllAttachments = Foreign.foreign "CVBufferRemoveAllAttachments" ((ptr CVBuffer.t) @-> returning void)
let _CVBufferRemoveAttachment = Foreign.foreign "CVBufferRemoveAttachment" ((ptr CVBuffer.t) @-> (ptr CFString.t) @-> returning void)
let _CVBufferRetain = Foreign.foreign "CVBufferRetain" ((ptr CVBuffer.t) @-> returning (ptr CVBuffer.t))
let _CVBufferSetAttachment = Foreign.foreign "CVBufferSetAttachment" ((ptr CVBuffer.t) @-> (ptr CFString.t) @-> id @-> uint @-> returning void)
let _CVBufferSetAttachments = Foreign.foreign "CVBufferSetAttachments" ((ptr CVBuffer.t) @-> (ptr CFDictionary.t) @-> uint @-> returning void)
let _CVColorPrimariesGetIntegerCodePointForString = Foreign.foreign "CVColorPrimariesGetIntegerCodePointForString" ((ptr CFString.t) @-> returning int)
let _CVColorPrimariesGetStringForIntegerCodePoint = Foreign.foreign "CVColorPrimariesGetStringForIntegerCodePoint" (int @-> returning (ptr CFString.t))
let _CVDisplayLinkCreateWithActiveCGDisplays = Foreign.foreign "CVDisplayLinkCreateWithActiveCGDisplays" ((ptr (ptr CVDisplayLink.t)) @-> returning int)
let _CVDisplayLinkCreateWithCGDisplay = Foreign.foreign "CVDisplayLinkCreateWithCGDisplay" (uint @-> (ptr (ptr CVDisplayLink.t)) @-> returning int)
let _CVDisplayLinkCreateWithCGDisplays = Foreign.foreign "CVDisplayLinkCreateWithCGDisplays" ((ptr uint) @-> llong @-> (ptr (ptr CVDisplayLink.t)) @-> returning int)
let _CVDisplayLinkCreateWithOpenGLDisplayMask = Foreign.foreign "CVDisplayLinkCreateWithOpenGLDisplayMask" (uint @-> (ptr (ptr CVDisplayLink.t)) @-> returning int)
let _CVDisplayLinkGetActualOutputVideoRefreshPeriod = Foreign.foreign "CVDisplayLinkGetActualOutputVideoRefreshPeriod" ((ptr CVDisplayLink.t) @-> returning double)
let _CVDisplayLinkGetCurrentCGDisplay = Foreign.foreign "CVDisplayLinkGetCurrentCGDisplay" ((ptr CVDisplayLink.t) @-> returning uint)
let _CVDisplayLinkGetCurrentTime = Foreign.foreign "CVDisplayLinkGetCurrentTime" ((ptr CVDisplayLink.t) @-> (ptr CVTimeStamp.t) @-> returning int)
let _CVDisplayLinkGetNominalOutputVideoRefreshPeriod = Foreign.foreign "CVDisplayLinkGetNominalOutputVideoRefreshPeriod" ((ptr CVDisplayLink.t) @-> returning CVTime.t)
let _CVDisplayLinkGetOutputVideoLatency = Foreign.foreign "CVDisplayLinkGetOutputVideoLatency" ((ptr CVDisplayLink.t) @-> returning CVTime.t)
let _CVDisplayLinkGetTypeID = Foreign.foreign "CVDisplayLinkGetTypeID" (void @-> returning ullong)
let _CVDisplayLinkIsRunning = Foreign.foreign "CVDisplayLinkIsRunning" ((ptr CVDisplayLink.t) @-> returning bool)
let _CVDisplayLinkRelease = Foreign.foreign "CVDisplayLinkRelease" ((ptr CVDisplayLink.t) @-> returning void)
let _CVDisplayLinkRetain = Foreign.foreign "CVDisplayLinkRetain" ((ptr CVDisplayLink.t) @-> returning (ptr CVDisplayLink.t))
let _CVDisplayLinkSetCurrentCGDisplay = Foreign.foreign "CVDisplayLinkSetCurrentCGDisplay" ((ptr CVDisplayLink.t) @-> uint @-> returning int)
let _CVDisplayLinkSetCurrentCGDisplayFromOpenGLContext = Foreign.foreign "CVDisplayLinkSetCurrentCGDisplayFromOpenGLContext" ((ptr CVDisplayLink.t) @-> (ptr CGLContextObject.t) @-> (ptr CGLPixelFormatObject.t) @-> returning int)
let _CVDisplayLinkSetOutputCallback = Foreign.foreign "CVDisplayLinkSetOutputCallback" ((ptr CVDisplayLink.t) @-> Foreign.funptr ((ptr CVDisplayLink.t) @-> (ptr CVTimeStamp.t) @-> (ptr CVTimeStamp.t) @-> ullong @-> (ptr ullong) @-> (ptr void) @-> returning int) @-> (ptr void) @-> returning int)
let _CVDisplayLinkSetOutputHandler = Foreign.foreign "CVDisplayLinkSetOutputHandler" ((ptr CVDisplayLink.t) @-> Foreign.funptr ((ptr CVDisplayLink.t) @-> (ptr CVTimeStamp.t) @-> (ptr CVTimeStamp.t) @-> ullong @-> (ptr ullong) @-> returning int) @-> returning int)
let _CVDisplayLinkStart = Foreign.foreign "CVDisplayLinkStart" ((ptr CVDisplayLink.t) @-> returning int)
let _CVDisplayLinkStop = Foreign.foreign "CVDisplayLinkStop" ((ptr CVDisplayLink.t) @-> returning int)
let _CVDisplayLinkTranslateTime = Foreign.foreign "CVDisplayLinkTranslateTime" ((ptr CVDisplayLink.t) @-> (ptr CVTimeStamp.t) @-> (ptr CVTimeStamp.t) @-> returning int)
let _CVGetCurrentHostTime = Foreign.foreign "CVGetCurrentHostTime" (void @-> returning ullong)
let _CVGetHostClockFrequency = Foreign.foreign "CVGetHostClockFrequency" (void @-> returning double)
let _CVGetHostClockMinimumTimeDelta = Foreign.foreign "CVGetHostClockMinimumTimeDelta" (void @-> returning uint)
let _CVImageBufferCreateColorSpaceFromAttachments = Foreign.foreign "CVImageBufferCreateColorSpaceFromAttachments" ((ptr CFDictionary.t) @-> returning (ptr CGColorSpace.t))
let _CVImageBufferGetCleanRect = Foreign.foreign "CVImageBufferGetCleanRect" ((ptr CVBuffer.t) @-> returning CGRect.t)
let _CVImageBufferGetColorSpace = Foreign.foreign "CVImageBufferGetColorSpace" ((ptr CVBuffer.t) @-> returning (ptr CGColorSpace.t))
let _CVImageBufferGetDisplaySize = Foreign.foreign "CVImageBufferGetDisplaySize" ((ptr CVBuffer.t) @-> returning CGSize.t)
let _CVImageBufferGetEncodedSize = Foreign.foreign "CVImageBufferGetEncodedSize" ((ptr CVBuffer.t) @-> returning CGSize.t)
let _CVImageBufferIsFlipped = Foreign.foreign "CVImageBufferIsFlipped" ((ptr CVBuffer.t) @-> returning bool)
let _CVIsCompressedPixelFormatAvailable = Foreign.foreign "CVIsCompressedPixelFormatAvailable" (uint @-> returning bool)
let _CVMetalTextureCacheCreate = Foreign.foreign "CVMetalTextureCacheCreate" ((ptr CFAllocator.t) @-> (ptr CFDictionary.t) @-> id @-> (ptr CFDictionary.t) @-> (ptr (ptr CVMetalTextureCache.t)) @-> returning int)
let _CVMetalTextureCacheCreateTextureFromImage = Foreign.foreign "CVMetalTextureCacheCreateTextureFromImage" ((ptr CFAllocator.t) @-> (ptr CVMetalTextureCache.t) @-> (ptr CVBuffer.t) @-> (ptr CFDictionary.t) @-> ullong @-> ullong @-> ullong @-> ullong @-> (ptr (ptr CVBuffer.t)) @-> returning int)
let _CVMetalTextureCacheFlush = Foreign.foreign "CVMetalTextureCacheFlush" ((ptr CVMetalTextureCache.t) @-> ullong @-> returning void)
let _CVMetalTextureCacheGetTypeID = Foreign.foreign "CVMetalTextureCacheGetTypeID" (void @-> returning ullong)
let _CVMetalTextureGetCleanTexCoords = Foreign.foreign "CVMetalTextureGetCleanTexCoords" ((ptr CVBuffer.t) @-> (ptr float) @-> (ptr float) @-> (ptr float) @-> (ptr float) @-> returning void)
let _CVMetalTextureGetTexture = Foreign.foreign "CVMetalTextureGetTexture" ((ptr CVBuffer.t) @-> returning id)
let _CVMetalTextureGetTypeID = Foreign.foreign "CVMetalTextureGetTypeID" (void @-> returning ullong)
let _CVMetalTextureIsFlipped = Foreign.foreign "CVMetalTextureIsFlipped" ((ptr CVBuffer.t) @-> returning bool)
let _CVOpenGLBufferAttach = Foreign.foreign "CVOpenGLBufferAttach" ((ptr CVBuffer.t) @-> (ptr CGLContextObject.t) @-> uint @-> int @-> int @-> returning int)
let _CVOpenGLBufferCreate = Foreign.foreign "CVOpenGLBufferCreate" ((ptr CFAllocator.t) @-> ullong @-> ullong @-> (ptr CFDictionary.t) @-> (ptr (ptr CVBuffer.t)) @-> returning int)
let _CVOpenGLBufferGetAttributes = Foreign.foreign "CVOpenGLBufferGetAttributes" ((ptr CVBuffer.t) @-> returning (ptr CFDictionary.t))
let _CVOpenGLBufferGetTypeID = Foreign.foreign "CVOpenGLBufferGetTypeID" (void @-> returning ullong)
let _CVOpenGLBufferPoolCreate = Foreign.foreign "CVOpenGLBufferPoolCreate" ((ptr CFAllocator.t) @-> (ptr CFDictionary.t) @-> (ptr CFDictionary.t) @-> (ptr (ptr CVOpenGLBufferPool.t)) @-> returning int)
let _CVOpenGLBufferPoolCreateOpenGLBuffer = Foreign.foreign "CVOpenGLBufferPoolCreateOpenGLBuffer" ((ptr CFAllocator.t) @-> (ptr CVOpenGLBufferPool.t) @-> (ptr (ptr CVBuffer.t)) @-> returning int)
let _CVOpenGLBufferPoolGetAttributes = Foreign.foreign "CVOpenGLBufferPoolGetAttributes" ((ptr CVOpenGLBufferPool.t) @-> returning (ptr CFDictionary.t))
let _CVOpenGLBufferPoolGetOpenGLBufferAttributes = Foreign.foreign "CVOpenGLBufferPoolGetOpenGLBufferAttributes" ((ptr CVOpenGLBufferPool.t) @-> returning (ptr CFDictionary.t))
let _CVOpenGLBufferPoolGetTypeID = Foreign.foreign "CVOpenGLBufferPoolGetTypeID" (void @-> returning ullong)
let _CVOpenGLBufferPoolRelease = Foreign.foreign "CVOpenGLBufferPoolRelease" ((ptr CVOpenGLBufferPool.t) @-> returning void)
let _CVOpenGLBufferPoolRetain = Foreign.foreign "CVOpenGLBufferPoolRetain" ((ptr CVOpenGLBufferPool.t) @-> returning (ptr CVOpenGLBufferPool.t))
let _CVOpenGLBufferRelease = Foreign.foreign "CVOpenGLBufferRelease" ((ptr CVBuffer.t) @-> returning void)
let _CVOpenGLBufferRetain = Foreign.foreign "CVOpenGLBufferRetain" ((ptr CVBuffer.t) @-> returning (ptr CVBuffer.t))
let _CVOpenGLTextureCacheCreate = Foreign.foreign "CVOpenGLTextureCacheCreate" ((ptr CFAllocator.t) @-> (ptr CFDictionary.t) @-> (ptr CGLContextObject.t) @-> (ptr CGLPixelFormatObject.t) @-> (ptr CFDictionary.t) @-> (ptr (ptr CVOpenGLTextureCache.t)) @-> returning int)
let _CVOpenGLTextureCacheCreateTextureFromImage = Foreign.foreign "CVOpenGLTextureCacheCreateTextureFromImage" ((ptr CFAllocator.t) @-> (ptr CVOpenGLTextureCache.t) @-> (ptr CVBuffer.t) @-> (ptr CFDictionary.t) @-> (ptr (ptr CVBuffer.t)) @-> returning int)
let _CVOpenGLTextureCacheFlush = Foreign.foreign "CVOpenGLTextureCacheFlush" ((ptr CVOpenGLTextureCache.t) @-> ullong @-> returning void)
let _CVOpenGLTextureCacheGetTypeID = Foreign.foreign "CVOpenGLTextureCacheGetTypeID" (void @-> returning ullong)
let _CVOpenGLTextureCacheRelease = Foreign.foreign "CVOpenGLTextureCacheRelease" ((ptr CVOpenGLTextureCache.t) @-> returning void)
let _CVOpenGLTextureCacheRetain = Foreign.foreign "CVOpenGLTextureCacheRetain" ((ptr CVOpenGLTextureCache.t) @-> returning (ptr CVOpenGLTextureCache.t))
let _CVOpenGLTextureGetCleanTexCoords = Foreign.foreign "CVOpenGLTextureGetCleanTexCoords" ((ptr CVBuffer.t) @-> (ptr float) @-> (ptr float) @-> (ptr float) @-> (ptr float) @-> returning void)
let _CVOpenGLTextureGetName = Foreign.foreign "CVOpenGLTextureGetName" ((ptr CVBuffer.t) @-> returning uint)
let _CVOpenGLTextureGetTarget = Foreign.foreign "CVOpenGLTextureGetTarget" ((ptr CVBuffer.t) @-> returning uint)
let _CVOpenGLTextureGetTypeID = Foreign.foreign "CVOpenGLTextureGetTypeID" (void @-> returning ullong)
let _CVOpenGLTextureIsFlipped = Foreign.foreign "CVOpenGLTextureIsFlipped" ((ptr CVBuffer.t) @-> returning bool)
let _CVOpenGLTextureRelease = Foreign.foreign "CVOpenGLTextureRelease" ((ptr CVBuffer.t) @-> returning void)
let _CVOpenGLTextureRetain = Foreign.foreign "CVOpenGLTextureRetain" ((ptr CVBuffer.t) @-> returning (ptr CVBuffer.t))
let _CVPixelBufferCopyCreationAttributes = Foreign.foreign "CVPixelBufferCopyCreationAttributes" ((ptr CVBuffer.t) @-> returning (ptr CFDictionary.t))
let _CVPixelBufferCreate = Foreign.foreign "CVPixelBufferCreate" ((ptr CFAllocator.t) @-> ullong @-> ullong @-> uint @-> (ptr CFDictionary.t) @-> (ptr (ptr CVBuffer.t)) @-> returning int)
let _CVPixelBufferCreateResolvedAttributesDictionary = Foreign.foreign "CVPixelBufferCreateResolvedAttributesDictionary" ((ptr CFAllocator.t) @-> (ptr CFArray.t) @-> (ptr (ptr CFDictionary.t)) @-> returning int)
let _CVPixelBufferCreateWithBytes = Foreign.foreign "CVPixelBufferCreateWithBytes" ((ptr CFAllocator.t) @-> ullong @-> ullong @-> uint @-> (ptr void) @-> ullong @-> Foreign.funptr ((ptr void) @-> (ptr void) @-> returning void) @-> (ptr void) @-> (ptr CFDictionary.t) @-> (ptr (ptr CVBuffer.t)) @-> returning int)
let _CVPixelBufferCreateWithIOSurface = Foreign.foreign "CVPixelBufferCreateWithIOSurface" ((ptr CFAllocator.t) @-> (ptr IOSurface.t) @-> (ptr CFDictionary.t) @-> (ptr (ptr CVBuffer.t)) @-> returning int)
let _CVPixelBufferCreateWithPlanarBytes = Foreign.foreign "CVPixelBufferCreateWithPlanarBytes" ((ptr CFAllocator.t) @-> ullong @-> ullong @-> uint @-> (ptr void) @-> ullong @-> ullong @-> (ptr (ptr void)) @-> (ptr ullong) @-> (ptr ullong) @-> (ptr ullong) @-> Foreign.funptr ((ptr void) @-> (ptr void) @-> ullong @-> ullong @-> (ptr (ptr void)) @-> returning void) @-> (ptr void) @-> (ptr CFDictionary.t) @-> (ptr (ptr CVBuffer.t)) @-> returning int)
let _CVPixelBufferFillExtendedPixels = Foreign.foreign "CVPixelBufferFillExtendedPixels" ((ptr CVBuffer.t) @-> returning int)
let _CVPixelBufferGetBaseAddress = Foreign.foreign "CVPixelBufferGetBaseAddress" ((ptr CVBuffer.t) @-> returning (ptr void))
let _CVPixelBufferGetBaseAddressOfPlane = Foreign.foreign "CVPixelBufferGetBaseAddressOfPlane" ((ptr CVBuffer.t) @-> ullong @-> returning (ptr void))
let _CVPixelBufferGetBytesPerRow = Foreign.foreign "CVPixelBufferGetBytesPerRow" ((ptr CVBuffer.t) @-> returning ullong)
let _CVPixelBufferGetBytesPerRowOfPlane = Foreign.foreign "CVPixelBufferGetBytesPerRowOfPlane" ((ptr CVBuffer.t) @-> ullong @-> returning ullong)
let _CVPixelBufferGetDataSize = Foreign.foreign "CVPixelBufferGetDataSize" ((ptr CVBuffer.t) @-> returning ullong)
let _CVPixelBufferGetExtendedPixels = Foreign.foreign "CVPixelBufferGetExtendedPixels" ((ptr CVBuffer.t) @-> (ptr ullong) @-> (ptr ullong) @-> (ptr ullong) @-> (ptr ullong) @-> returning void)
let _CVPixelBufferGetHeight = Foreign.foreign "CVPixelBufferGetHeight" ((ptr CVBuffer.t) @-> returning ullong)
let _CVPixelBufferGetHeightOfPlane = Foreign.foreign "CVPixelBufferGetHeightOfPlane" ((ptr CVBuffer.t) @-> ullong @-> returning ullong)
let _CVPixelBufferGetIOSurface = Foreign.foreign "CVPixelBufferGetIOSurface" ((ptr CVBuffer.t) @-> returning (ptr IOSurface.t))
let _CVPixelBufferGetPixelFormatType = Foreign.foreign "CVPixelBufferGetPixelFormatType" ((ptr CVBuffer.t) @-> returning uint)
let _CVPixelBufferGetPlaneCount = Foreign.foreign "CVPixelBufferGetPlaneCount" ((ptr CVBuffer.t) @-> returning ullong)
let _CVPixelBufferGetTypeID = Foreign.foreign "CVPixelBufferGetTypeID" (void @-> returning ullong)
let _CVPixelBufferGetWidth = Foreign.foreign "CVPixelBufferGetWidth" ((ptr CVBuffer.t) @-> returning ullong)
let _CVPixelBufferGetWidthOfPlane = Foreign.foreign "CVPixelBufferGetWidthOfPlane" ((ptr CVBuffer.t) @-> ullong @-> returning ullong)
let _CVPixelBufferIsPlanar = Foreign.foreign "CVPixelBufferIsPlanar" ((ptr CVBuffer.t) @-> returning bool)
let _CVPixelBufferLockBaseAddress = Foreign.foreign "CVPixelBufferLockBaseAddress" ((ptr CVBuffer.t) @-> ullong @-> returning int)
let _CVPixelBufferPoolCreate = Foreign.foreign "CVPixelBufferPoolCreate" ((ptr CFAllocator.t) @-> (ptr CFDictionary.t) @-> (ptr CFDictionary.t) @-> (ptr (ptr CVPixelBufferPool.t)) @-> returning int)
let _CVPixelBufferPoolCreatePixelBuffer = Foreign.foreign "CVPixelBufferPoolCreatePixelBuffer" ((ptr CFAllocator.t) @-> (ptr CVPixelBufferPool.t) @-> (ptr (ptr CVBuffer.t)) @-> returning int)
let _CVPixelBufferPoolCreatePixelBufferWithAuxAttributes = Foreign.foreign "CVPixelBufferPoolCreatePixelBufferWithAuxAttributes" ((ptr CFAllocator.t) @-> (ptr CVPixelBufferPool.t) @-> (ptr CFDictionary.t) @-> (ptr (ptr CVBuffer.t)) @-> returning int)
let _CVPixelBufferPoolFlush = Foreign.foreign "CVPixelBufferPoolFlush" ((ptr CVPixelBufferPool.t) @-> ullong @-> returning void)
let _CVPixelBufferPoolGetAttributes = Foreign.foreign "CVPixelBufferPoolGetAttributes" ((ptr CVPixelBufferPool.t) @-> returning (ptr CFDictionary.t))
let _CVPixelBufferPoolGetPixelBufferAttributes = Foreign.foreign "CVPixelBufferPoolGetPixelBufferAttributes" ((ptr CVPixelBufferPool.t) @-> returning (ptr CFDictionary.t))
let _CVPixelBufferPoolGetTypeID = Foreign.foreign "CVPixelBufferPoolGetTypeID" (void @-> returning ullong)
let _CVPixelBufferPoolRelease = Foreign.foreign "CVPixelBufferPoolRelease" ((ptr CVPixelBufferPool.t) @-> returning void)
let _CVPixelBufferPoolRetain = Foreign.foreign "CVPixelBufferPoolRetain" ((ptr CVPixelBufferPool.t) @-> returning (ptr CVPixelBufferPool.t))
let _CVPixelBufferRelease = Foreign.foreign "CVPixelBufferRelease" ((ptr CVBuffer.t) @-> returning void)
let _CVPixelBufferRetain = Foreign.foreign "CVPixelBufferRetain" ((ptr CVBuffer.t) @-> returning (ptr CVBuffer.t))
let _CVPixelBufferUnlockBaseAddress = Foreign.foreign "CVPixelBufferUnlockBaseAddress" ((ptr CVBuffer.t) @-> ullong @-> returning int)
let _CVPixelFormatDescriptionArrayCreateWithAllPixelFormatTypes = Foreign.foreign "CVPixelFormatDescriptionArrayCreateWithAllPixelFormatTypes" ((ptr CFAllocator.t) @-> returning (ptr CFArray.t))
let _CVPixelFormatDescriptionCreateWithPixelFormatType = Foreign.foreign "CVPixelFormatDescriptionCreateWithPixelFormatType" ((ptr CFAllocator.t) @-> uint @-> returning (ptr CFDictionary.t))
let _CVPixelFormatDescriptionRegisterDescriptionWithPixelFormatType = Foreign.foreign "CVPixelFormatDescriptionRegisterDescriptionWithPixelFormatType" ((ptr CFDictionary.t) @-> uint @-> returning void)
let _CVTransferFunctionGetIntegerCodePointForString = Foreign.foreign "CVTransferFunctionGetIntegerCodePointForString" ((ptr CFString.t) @-> returning int)
let _CVTransferFunctionGetStringForIntegerCodePoint = Foreign.foreign "CVTransferFunctionGetStringForIntegerCodePoint" (int @-> returning (ptr CFString.t))
let _CVYCbCrMatrixGetIntegerCodePointForString = Foreign.foreign "CVYCbCrMatrixGetIntegerCodePointForString" ((ptr CFString.t) @-> returning int)
let _CVYCbCrMatrixGetStringForIntegerCodePoint = Foreign.foreign "CVYCbCrMatrixGetStringForIntegerCodePoint" (int @-> returning (ptr CFString.t))
