(* auto-generated, do not modify *)

[@@@ocaml.warning "-33"]
open Runtime
open Objc

module CFAllocatorRef = struct
  let t = (ptr CFAllocator.t)
end

module CFArrayRef = struct
  let t = (ptr CFArray.t)
end

module CFAttributedStringRef = struct
  let t = (ptr CFAttributedString.t)
end

module CFBagRef = struct
  let t = (ptr CFBag.t)
end

module CFBinaryHeapRef = struct
  let t = (ptr CFBinaryHeap.t)
end

module CFBitVectorRef = struct
  let t = (ptr CFBitVector.t)
end

module CFBooleanRef = struct
  let t = (ptr CFBoolean.t)
end

module CFBundleRef = struct
  let t = (ptr CFBundle.t)
end

module CFCalendarRef = struct
  let t = (ptr CFCalendar.t)
end

module CFCharacterSetRef = struct
  let t = (ptr CFCharacterSet.t)
end

module CFDataRef = struct
  let t = (ptr CFData.t)
end

module CFDateFormatterRef = struct
  let t = (ptr CFDateFormatter.t)
end

module CFDateRef = struct
  let t = (ptr CFDate.t)
end

module CFDictionaryRef = struct
  let t = (ptr CFDictionary.t)
end

module CFErrorRef = struct
  let t = (ptr CFError.t)
end

module CFFileDescriptorRef = struct
  let t = (ptr CFFileDescriptor.t)
end

module CFFileSecurityRef = struct
  let t = (ptr CFFileSecurity.t)
end

module CFLocaleRef = struct
  let t = (ptr CFLocale.t)
end

module CFMachPortRef = struct
  let t = (ptr CFMachPort.t)
end

module CFMessagePortRef = struct
  let t = (ptr CFMessagePort.t)
end

module CFMutableArrayRef = struct
  let t = (ptr CFArray.t)
end

module CFMutableAttributedStringRef = struct
  let t = (ptr CFAttributedString.t)
end

module CFMutableBagRef = struct
  let t = (ptr CFBag.t)
end

module CFMutableBitVectorRef = struct
  let t = (ptr CFBitVector.t)
end

module CFMutableCharacterSetRef = struct
  let t = (ptr CFCharacterSet.t)
end

module CFMutableDataRef = struct
  let t = (ptr CFData.t)
end

module CFMutableDictionaryRef = struct
  let t = (ptr CFDictionary.t)
end

module CFMutableSetRef = struct
  let t = (ptr CFSet.t)
end

module CFMutableStringRef = struct
  let t = (ptr CFString.t)
end

module CFNotificationCenterRef = struct
  let t = (ptr CFNotificationCenter.t)
end

module CFNullRef = struct
  let t = (ptr CFNull.t)
end

module CFNumberFormatterRef = struct
  let t = (ptr CFNumberFormatter.t)
end

module CFNumberRef = struct
  let t = (ptr CFNumber.t)
end

module CFPlugInInstanceRef = struct
  let t = (ptr CFPlugInInstance.t)
end

module CFPlugInRef = struct
  let t = (ptr CFBundle.t)
end

module CFReadStreamRef = struct
  let t = (ptr CFReadStream.t)
end

module CFRunLoopObserverRef = struct
  let t = (ptr CFRunLoopObserver.t)
end

module CFRunLoopRef = struct
  let t = (ptr CFRunLoop.t)
end

module CFRunLoopSourceRef = struct
  let t = (ptr CFRunLoopSource.t)
end

module CFRunLoopTimerRef = struct
  let t = (ptr CFRunLoopTimer.t)
end

module CFSetRef = struct
  let t = (ptr CFSet.t)
end

module CFSocketRef = struct
  let t = (ptr CFSocket.t)
end

module CFStringRef = struct
  let t = (ptr CFString.t)
end

module CFStringTokenizerRef = struct
  let t = (ptr CFStringTokenizer.t)
end

module CFTimeZoneRef = struct
  let t = (ptr CFTimeZone.t)
end

module CFTreeRef = struct
  let t = (ptr CFTree.t)
end

module CFURLEnumeratorRef = struct
  let t = (ptr CFURLEnumerator.t)
end

module CFURLRef = struct
  let t = (ptr CFURL.t)
end

module CFUUIDRef = struct
  let t = (ptr CFUUID.t)
end

module CFUserNotificationRef = struct
  let t = (ptr CFUserNotification.t)
end

module CFWriteStreamRef = struct
  let t = (ptr CFWriteStream.t)
end

module CFXMLNodeRef = struct
  let t = (ptr CFXMLNode.t)
end

module CFXMLParserRef = struct
  let t = (ptr CFXMLParser.t)
end

module CFTypeRef = struct
  let t = (ptr void)
end

let kCFAbsoluteTimeIntervalSince1904 = foreign_value_or_null "kCFAbsoluteTimeIntervalSince1904" double
let kCFAbsoluteTimeIntervalSince1970 = foreign_value_or_null "kCFAbsoluteTimeIntervalSince1970" double
let kCFAllocatorDefault = foreign_value_or_null "kCFAllocatorDefault" (ptr CFAllocator.t)
let kCFAllocatorMalloc = foreign_value_or_null "kCFAllocatorMalloc" (ptr CFAllocator.t)
let kCFAllocatorMallocZone = foreign_value_or_null "kCFAllocatorMallocZone" (ptr CFAllocator.t)
let kCFAllocatorNull = foreign_value_or_null "kCFAllocatorNull" (ptr CFAllocator.t)
let kCFAllocatorSystemDefault = foreign_value_or_null "kCFAllocatorSystemDefault" (ptr CFAllocator.t)
let kCFAllocatorUseContext = foreign_value_or_null "kCFAllocatorUseContext" (ptr CFAllocator.t)
let kCFBooleanFalse = foreign_value_or_null "kCFBooleanFalse" (ptr CFBoolean.t)
let kCFBooleanTrue = foreign_value_or_null "kCFBooleanTrue" (ptr CFBoolean.t)
let kCFBuddhistCalendar = foreign_value_or_null "kCFBuddhistCalendar" (ptr CFString.t)
let kCFBundleDevelopmentRegionKey = foreign_value_or_null "kCFBundleDevelopmentRegionKey" (ptr CFString.t)
let kCFBundleExecutableKey = foreign_value_or_null "kCFBundleExecutableKey" (ptr CFString.t)
let kCFBundleIdentifierKey = foreign_value_or_null "kCFBundleIdentifierKey" (ptr CFString.t)
let kCFBundleInfoDictionaryVersionKey = foreign_value_or_null "kCFBundleInfoDictionaryVersionKey" (ptr CFString.t)
let kCFBundleLocalizationsKey = foreign_value_or_null "kCFBundleLocalizationsKey" (ptr CFString.t)
let kCFBundleNameKey = foreign_value_or_null "kCFBundleNameKey" (ptr CFString.t)
let kCFBundleVersionKey = foreign_value_or_null "kCFBundleVersionKey" (ptr CFString.t)
let kCFChineseCalendar = foreign_value_or_null "kCFChineseCalendar" (ptr CFString.t)
let kCFCopyStringBagCallBacks = foreign_value_or_null "kCFCopyStringBagCallBacks" CFBagCallBacks.t
let kCFCopyStringDictionaryKeyCallBacks = foreign_value_or_null "kCFCopyStringDictionaryKeyCallBacks" CFDictionaryKeyCallBacks.t
let kCFCopyStringSetCallBacks = foreign_value_or_null "kCFCopyStringSetCallBacks" CFSetCallBacks.t
let kCFCoreFoundationVersionNumber = foreign_value_or_null "kCFCoreFoundationVersionNumber" double
let kCFDateFormatterAMSymbol = foreign_value_or_null "kCFDateFormatterAMSymbol" (ptr CFString.t)
let kCFDateFormatterCalendar = foreign_value_or_null "kCFDateFormatterCalendar" (ptr CFString.t)
let kCFDateFormatterCalendarName = foreign_value_or_null "kCFDateFormatterCalendarName" (ptr CFString.t)
let kCFDateFormatterDefaultDate = foreign_value_or_null "kCFDateFormatterDefaultDate" (ptr CFString.t)
let kCFDateFormatterDefaultFormat = foreign_value_or_null "kCFDateFormatterDefaultFormat" (ptr CFString.t)
let kCFDateFormatterDoesRelativeDateFormattingKey = foreign_value_or_null "kCFDateFormatterDoesRelativeDateFormattingKey" (ptr CFString.t)
let kCFDateFormatterEraSymbols = foreign_value_or_null "kCFDateFormatterEraSymbols" (ptr CFString.t)
let kCFDateFormatterGregorianStartDate = foreign_value_or_null "kCFDateFormatterGregorianStartDate" (ptr CFString.t)
let kCFDateFormatterIsLenient = foreign_value_or_null "kCFDateFormatterIsLenient" (ptr CFString.t)
let kCFDateFormatterLongEraSymbols = foreign_value_or_null "kCFDateFormatterLongEraSymbols" (ptr CFString.t)
let kCFDateFormatterMonthSymbols = foreign_value_or_null "kCFDateFormatterMonthSymbols" (ptr CFString.t)
let kCFDateFormatterPMSymbol = foreign_value_or_null "kCFDateFormatterPMSymbol" (ptr CFString.t)
let kCFDateFormatterQuarterSymbols = foreign_value_or_null "kCFDateFormatterQuarterSymbols" (ptr CFString.t)
let kCFDateFormatterShortMonthSymbols = foreign_value_or_null "kCFDateFormatterShortMonthSymbols" (ptr CFString.t)
let kCFDateFormatterShortQuarterSymbols = foreign_value_or_null "kCFDateFormatterShortQuarterSymbols" (ptr CFString.t)
let kCFDateFormatterShortStandaloneMonthSymbols = foreign_value_or_null "kCFDateFormatterShortStandaloneMonthSymbols" (ptr CFString.t)
let kCFDateFormatterShortStandaloneQuarterSymbols = foreign_value_or_null "kCFDateFormatterShortStandaloneQuarterSymbols" (ptr CFString.t)
let kCFDateFormatterShortStandaloneWeekdaySymbols = foreign_value_or_null "kCFDateFormatterShortStandaloneWeekdaySymbols" (ptr CFString.t)
let kCFDateFormatterShortWeekdaySymbols = foreign_value_or_null "kCFDateFormatterShortWeekdaySymbols" (ptr CFString.t)
let kCFDateFormatterStandaloneMonthSymbols = foreign_value_or_null "kCFDateFormatterStandaloneMonthSymbols" (ptr CFString.t)
let kCFDateFormatterStandaloneQuarterSymbols = foreign_value_or_null "kCFDateFormatterStandaloneQuarterSymbols" (ptr CFString.t)
let kCFDateFormatterStandaloneWeekdaySymbols = foreign_value_or_null "kCFDateFormatterStandaloneWeekdaySymbols" (ptr CFString.t)
let kCFDateFormatterTimeZone = foreign_value_or_null "kCFDateFormatterTimeZone" (ptr CFString.t)
let kCFDateFormatterTwoDigitStartDate = foreign_value_or_null "kCFDateFormatterTwoDigitStartDate" (ptr CFString.t)
let kCFDateFormatterVeryShortMonthSymbols = foreign_value_or_null "kCFDateFormatterVeryShortMonthSymbols" (ptr CFString.t)
let kCFDateFormatterVeryShortStandaloneMonthSymbols = foreign_value_or_null "kCFDateFormatterVeryShortStandaloneMonthSymbols" (ptr CFString.t)
let kCFDateFormatterVeryShortStandaloneWeekdaySymbols = foreign_value_or_null "kCFDateFormatterVeryShortStandaloneWeekdaySymbols" (ptr CFString.t)
let kCFDateFormatterVeryShortWeekdaySymbols = foreign_value_or_null "kCFDateFormatterVeryShortWeekdaySymbols" (ptr CFString.t)
let kCFDateFormatterWeekdaySymbols = foreign_value_or_null "kCFDateFormatterWeekdaySymbols" (ptr CFString.t)
let kCFErrorDescriptionKey = foreign_value_or_null "kCFErrorDescriptionKey" (ptr CFString.t)
let kCFErrorDomainCocoa = foreign_value_or_null "kCFErrorDomainCocoa" (ptr CFString.t)
let kCFErrorDomainMach = foreign_value_or_null "kCFErrorDomainMach" (ptr CFString.t)
let kCFErrorDomainOSStatus = foreign_value_or_null "kCFErrorDomainOSStatus" (ptr CFString.t)
let kCFErrorDomainPOSIX = foreign_value_or_null "kCFErrorDomainPOSIX" (ptr CFString.t)
let kCFErrorFilePathKey = foreign_value_or_null "kCFErrorFilePathKey" (ptr CFString.t)
let kCFErrorLocalizedDescriptionKey = foreign_value_or_null "kCFErrorLocalizedDescriptionKey" (ptr CFString.t)
let kCFErrorLocalizedFailureKey = foreign_value_or_null "kCFErrorLocalizedFailureKey" (ptr CFString.t)
let kCFErrorLocalizedFailureReasonKey = foreign_value_or_null "kCFErrorLocalizedFailureReasonKey" (ptr CFString.t)
let kCFErrorLocalizedRecoverySuggestionKey = foreign_value_or_null "kCFErrorLocalizedRecoverySuggestionKey" (ptr CFString.t)
let kCFErrorURLKey = foreign_value_or_null "kCFErrorURLKey" (ptr CFString.t)
let kCFErrorUnderlyingErrorKey = foreign_value_or_null "kCFErrorUnderlyingErrorKey" (ptr CFString.t)
let kCFGregorianCalendar = foreign_value_or_null "kCFGregorianCalendar" (ptr CFString.t)
let kCFHebrewCalendar = foreign_value_or_null "kCFHebrewCalendar" (ptr CFString.t)
let kCFISO8601Calendar = foreign_value_or_null "kCFISO8601Calendar" (ptr CFString.t)
let kCFIndianCalendar = foreign_value_or_null "kCFIndianCalendar" (ptr CFString.t)
let kCFIslamicCalendar = foreign_value_or_null "kCFIslamicCalendar" (ptr CFString.t)
let kCFIslamicCivilCalendar = foreign_value_or_null "kCFIslamicCivilCalendar" (ptr CFString.t)
let kCFIslamicTabularCalendar = foreign_value_or_null "kCFIslamicTabularCalendar" (ptr CFString.t)
let kCFIslamicUmmAlQuraCalendar = foreign_value_or_null "kCFIslamicUmmAlQuraCalendar" (ptr CFString.t)
let kCFJapaneseCalendar = foreign_value_or_null "kCFJapaneseCalendar" (ptr CFString.t)
let kCFLocaleAlternateQuotationBeginDelimiterKey = foreign_value_or_null "kCFLocaleAlternateQuotationBeginDelimiterKey" (ptr CFString.t)
let kCFLocaleAlternateQuotationEndDelimiterKey = foreign_value_or_null "kCFLocaleAlternateQuotationEndDelimiterKey" (ptr CFString.t)
let kCFLocaleCalendar = foreign_value_or_null "kCFLocaleCalendar" (ptr CFString.t)
let kCFLocaleCalendarIdentifier = foreign_value_or_null "kCFLocaleCalendarIdentifier" (ptr CFString.t)
let kCFLocaleCollationIdentifier = foreign_value_or_null "kCFLocaleCollationIdentifier" (ptr CFString.t)
let kCFLocaleCollatorIdentifier = foreign_value_or_null "kCFLocaleCollatorIdentifier" (ptr CFString.t)
let kCFLocaleCountryCode = foreign_value_or_null "kCFLocaleCountryCode" (ptr CFString.t)
let kCFLocaleCurrencyCode = foreign_value_or_null "kCFLocaleCurrencyCode" (ptr CFString.t)
let kCFLocaleCurrencySymbol = foreign_value_or_null "kCFLocaleCurrencySymbol" (ptr CFString.t)
let kCFLocaleCurrentLocaleDidChangeNotification = foreign_value_or_null "kCFLocaleCurrentLocaleDidChangeNotification" (ptr CFString.t)
let kCFLocaleDecimalSeparator = foreign_value_or_null "kCFLocaleDecimalSeparator" (ptr CFString.t)
let kCFLocaleExemplarCharacterSet = foreign_value_or_null "kCFLocaleExemplarCharacterSet" (ptr CFString.t)
let kCFLocaleGroupingSeparator = foreign_value_or_null "kCFLocaleGroupingSeparator" (ptr CFString.t)
let kCFLocaleIdentifier = foreign_value_or_null "kCFLocaleIdentifier" (ptr CFString.t)
let kCFLocaleLanguageCode = foreign_value_or_null "kCFLocaleLanguageCode" (ptr CFString.t)
let kCFLocaleMeasurementSystem = foreign_value_or_null "kCFLocaleMeasurementSystem" (ptr CFString.t)
let kCFLocaleQuotationBeginDelimiterKey = foreign_value_or_null "kCFLocaleQuotationBeginDelimiterKey" (ptr CFString.t)
let kCFLocaleQuotationEndDelimiterKey = foreign_value_or_null "kCFLocaleQuotationEndDelimiterKey" (ptr CFString.t)
let kCFLocaleScriptCode = foreign_value_or_null "kCFLocaleScriptCode" (ptr CFString.t)
let kCFLocaleUsesMetricSystem = foreign_value_or_null "kCFLocaleUsesMetricSystem" (ptr CFString.t)
let kCFLocaleVariantCode = foreign_value_or_null "kCFLocaleVariantCode" (ptr CFString.t)
let kCFNull = foreign_value_or_null "kCFNull" (ptr CFNull.t)
let kCFNumberFormatterAlwaysShowDecimalSeparator = foreign_value_or_null "kCFNumberFormatterAlwaysShowDecimalSeparator" (ptr CFString.t)
let kCFNumberFormatterCurrencyCode = foreign_value_or_null "kCFNumberFormatterCurrencyCode" (ptr CFString.t)
let kCFNumberFormatterCurrencyDecimalSeparator = foreign_value_or_null "kCFNumberFormatterCurrencyDecimalSeparator" (ptr CFString.t)
let kCFNumberFormatterCurrencyGroupingSeparator = foreign_value_or_null "kCFNumberFormatterCurrencyGroupingSeparator" (ptr CFString.t)
let kCFNumberFormatterCurrencySymbol = foreign_value_or_null "kCFNumberFormatterCurrencySymbol" (ptr CFString.t)
let kCFNumberFormatterDecimalSeparator = foreign_value_or_null "kCFNumberFormatterDecimalSeparator" (ptr CFString.t)
let kCFNumberFormatterDefaultFormat = foreign_value_or_null "kCFNumberFormatterDefaultFormat" (ptr CFString.t)
let kCFNumberFormatterExponentSymbol = foreign_value_or_null "kCFNumberFormatterExponentSymbol" (ptr CFString.t)
let kCFNumberFormatterFormatWidth = foreign_value_or_null "kCFNumberFormatterFormatWidth" (ptr CFString.t)
let kCFNumberFormatterGroupingSeparator = foreign_value_or_null "kCFNumberFormatterGroupingSeparator" (ptr CFString.t)
let kCFNumberFormatterGroupingSize = foreign_value_or_null "kCFNumberFormatterGroupingSize" (ptr CFString.t)
let kCFNumberFormatterInfinitySymbol = foreign_value_or_null "kCFNumberFormatterInfinitySymbol" (ptr CFString.t)
let kCFNumberFormatterInternationalCurrencySymbol = foreign_value_or_null "kCFNumberFormatterInternationalCurrencySymbol" (ptr CFString.t)
let kCFNumberFormatterIsLenient = foreign_value_or_null "kCFNumberFormatterIsLenient" (ptr CFString.t)
let kCFNumberFormatterMaxFractionDigits = foreign_value_or_null "kCFNumberFormatterMaxFractionDigits" (ptr CFString.t)
let kCFNumberFormatterMaxIntegerDigits = foreign_value_or_null "kCFNumberFormatterMaxIntegerDigits" (ptr CFString.t)
let kCFNumberFormatterMaxSignificantDigits = foreign_value_or_null "kCFNumberFormatterMaxSignificantDigits" (ptr CFString.t)
let kCFNumberFormatterMinFractionDigits = foreign_value_or_null "kCFNumberFormatterMinFractionDigits" (ptr CFString.t)
let kCFNumberFormatterMinIntegerDigits = foreign_value_or_null "kCFNumberFormatterMinIntegerDigits" (ptr CFString.t)
let kCFNumberFormatterMinSignificantDigits = foreign_value_or_null "kCFNumberFormatterMinSignificantDigits" (ptr CFString.t)
let kCFNumberFormatterMinusSign = foreign_value_or_null "kCFNumberFormatterMinusSign" (ptr CFString.t)
let kCFNumberFormatterMultiplier = foreign_value_or_null "kCFNumberFormatterMultiplier" (ptr CFString.t)
let kCFNumberFormatterNaNSymbol = foreign_value_or_null "kCFNumberFormatterNaNSymbol" (ptr CFString.t)
let kCFNumberFormatterNegativePrefix = foreign_value_or_null "kCFNumberFormatterNegativePrefix" (ptr CFString.t)
let kCFNumberFormatterNegativeSuffix = foreign_value_or_null "kCFNumberFormatterNegativeSuffix" (ptr CFString.t)
let kCFNumberFormatterPaddingCharacter = foreign_value_or_null "kCFNumberFormatterPaddingCharacter" (ptr CFString.t)
let kCFNumberFormatterPaddingPosition = foreign_value_or_null "kCFNumberFormatterPaddingPosition" (ptr CFString.t)
let kCFNumberFormatterPerMillSymbol = foreign_value_or_null "kCFNumberFormatterPerMillSymbol" (ptr CFString.t)
let kCFNumberFormatterPercentSymbol = foreign_value_or_null "kCFNumberFormatterPercentSymbol" (ptr CFString.t)
let kCFNumberFormatterPlusSign = foreign_value_or_null "kCFNumberFormatterPlusSign" (ptr CFString.t)
let kCFNumberFormatterPositivePrefix = foreign_value_or_null "kCFNumberFormatterPositivePrefix" (ptr CFString.t)
let kCFNumberFormatterPositiveSuffix = foreign_value_or_null "kCFNumberFormatterPositiveSuffix" (ptr CFString.t)
let kCFNumberFormatterRoundingIncrement = foreign_value_or_null "kCFNumberFormatterRoundingIncrement" (ptr CFString.t)
let kCFNumberFormatterRoundingMode = foreign_value_or_null "kCFNumberFormatterRoundingMode" (ptr CFString.t)
let kCFNumberFormatterSecondaryGroupingSize = foreign_value_or_null "kCFNumberFormatterSecondaryGroupingSize" (ptr CFString.t)
let kCFNumberFormatterUseGroupingSeparator = foreign_value_or_null "kCFNumberFormatterUseGroupingSeparator" (ptr CFString.t)
let kCFNumberFormatterUseSignificantDigits = foreign_value_or_null "kCFNumberFormatterUseSignificantDigits" (ptr CFString.t)
let kCFNumberFormatterZeroSymbol = foreign_value_or_null "kCFNumberFormatterZeroSymbol" (ptr CFString.t)
let kCFNumberNaN = foreign_value_or_null "kCFNumberNaN" (ptr CFNumber.t)
let kCFNumberNegativeInfinity = foreign_value_or_null "kCFNumberNegativeInfinity" (ptr CFNumber.t)
let kCFNumberPositiveInfinity = foreign_value_or_null "kCFNumberPositiveInfinity" (ptr CFNumber.t)
let kCFPersianCalendar = foreign_value_or_null "kCFPersianCalendar" (ptr CFString.t)
let kCFPlugInDynamicRegisterFunctionKey = foreign_value_or_null "kCFPlugInDynamicRegisterFunctionKey" (ptr CFString.t)
let kCFPlugInDynamicRegistrationKey = foreign_value_or_null "kCFPlugInDynamicRegistrationKey" (ptr CFString.t)
let kCFPlugInFactoriesKey = foreign_value_or_null "kCFPlugInFactoriesKey" (ptr CFString.t)
let kCFPlugInTypesKey = foreign_value_or_null "kCFPlugInTypesKey" (ptr CFString.t)
let kCFPlugInUnloadFunctionKey = foreign_value_or_null "kCFPlugInUnloadFunctionKey" (ptr CFString.t)
let kCFPreferencesAnyApplication = foreign_value_or_null "kCFPreferencesAnyApplication" (ptr CFString.t)
let kCFPreferencesAnyHost = foreign_value_or_null "kCFPreferencesAnyHost" (ptr CFString.t)
let kCFPreferencesAnyUser = foreign_value_or_null "kCFPreferencesAnyUser" (ptr CFString.t)
let kCFPreferencesCurrentApplication = foreign_value_or_null "kCFPreferencesCurrentApplication" (ptr CFString.t)
let kCFPreferencesCurrentHost = foreign_value_or_null "kCFPreferencesCurrentHost" (ptr CFString.t)
let kCFPreferencesCurrentUser = foreign_value_or_null "kCFPreferencesCurrentUser" (ptr CFString.t)
let kCFRepublicOfChinaCalendar = foreign_value_or_null "kCFRepublicOfChinaCalendar" (ptr CFString.t)
let kCFRunLoopCommonModes = foreign_value_or_null "kCFRunLoopCommonModes" (ptr CFString.t)
let kCFRunLoopDefaultMode = foreign_value_or_null "kCFRunLoopDefaultMode" (ptr CFString.t)
let kCFSocketCommandKey = foreign_value_or_null "kCFSocketCommandKey" (ptr CFString.t)
let kCFSocketErrorKey = foreign_value_or_null "kCFSocketErrorKey" (ptr CFString.t)
let kCFSocketNameKey = foreign_value_or_null "kCFSocketNameKey" (ptr CFString.t)
let kCFSocketRegisterCommand = foreign_value_or_null "kCFSocketRegisterCommand" (ptr CFString.t)
let kCFSocketResultKey = foreign_value_or_null "kCFSocketResultKey" (ptr CFString.t)
let kCFSocketRetrieveCommand = foreign_value_or_null "kCFSocketRetrieveCommand" (ptr CFString.t)
let kCFSocketValueKey = foreign_value_or_null "kCFSocketValueKey" (ptr CFString.t)
let kCFStreamErrorDomainSOCKS = foreign_value_or_null "kCFStreamErrorDomainSOCKS" int
let kCFStreamErrorDomainSSL = foreign_value_or_null "kCFStreamErrorDomainSSL" int
let kCFStreamPropertyAppendToFile = foreign_value_or_null "kCFStreamPropertyAppendToFile" (ptr CFString.t)
let kCFStreamPropertyDataWritten = foreign_value_or_null "kCFStreamPropertyDataWritten" (ptr CFString.t)
let kCFStreamPropertyFileCurrentOffset = foreign_value_or_null "kCFStreamPropertyFileCurrentOffset" (ptr CFString.t)
let kCFStreamPropertySOCKSPassword = foreign_value_or_null "kCFStreamPropertySOCKSPassword" (ptr CFString.t)
let kCFStreamPropertySOCKSProxy = foreign_value_or_null "kCFStreamPropertySOCKSProxy" (ptr CFString.t)
let kCFStreamPropertySOCKSProxyHost = foreign_value_or_null "kCFStreamPropertySOCKSProxyHost" (ptr CFString.t)
let kCFStreamPropertySOCKSProxyPort = foreign_value_or_null "kCFStreamPropertySOCKSProxyPort" (ptr CFString.t)
let kCFStreamPropertySOCKSUser = foreign_value_or_null "kCFStreamPropertySOCKSUser" (ptr CFString.t)
let kCFStreamPropertySOCKSVersion = foreign_value_or_null "kCFStreamPropertySOCKSVersion" (ptr CFString.t)
let kCFStreamPropertyShouldCloseNativeSocket = foreign_value_or_null "kCFStreamPropertyShouldCloseNativeSocket" (ptr CFString.t)
let kCFStreamPropertySocketNativeHandle = foreign_value_or_null "kCFStreamPropertySocketNativeHandle" (ptr CFString.t)
let kCFStreamPropertySocketRemoteHostName = foreign_value_or_null "kCFStreamPropertySocketRemoteHostName" (ptr CFString.t)
let kCFStreamPropertySocketRemotePortNumber = foreign_value_or_null "kCFStreamPropertySocketRemotePortNumber" (ptr CFString.t)
let kCFStreamPropertySocketSecurityLevel = foreign_value_or_null "kCFStreamPropertySocketSecurityLevel" (ptr CFString.t)
let kCFStreamSocketSOCKSVersion4 = foreign_value_or_null "kCFStreamSocketSOCKSVersion4" (ptr CFString.t)
let kCFStreamSocketSOCKSVersion5 = foreign_value_or_null "kCFStreamSocketSOCKSVersion5" (ptr CFString.t)
let kCFStreamSocketSecurityLevelNegotiatedSSL = foreign_value_or_null "kCFStreamSocketSecurityLevelNegotiatedSSL" (ptr CFString.t)
let kCFStreamSocketSecurityLevelNone = foreign_value_or_null "kCFStreamSocketSecurityLevelNone" (ptr CFString.t)
let kCFStreamSocketSecurityLevelSSLv2 = foreign_value_or_null "kCFStreamSocketSecurityLevelSSLv2" (ptr CFString.t)
let kCFStreamSocketSecurityLevelSSLv3 = foreign_value_or_null "kCFStreamSocketSecurityLevelSSLv3" (ptr CFString.t)
let kCFStreamSocketSecurityLevelTLSv1 = foreign_value_or_null "kCFStreamSocketSecurityLevelTLSv1" (ptr CFString.t)
let kCFStringBinaryHeapCallBacks = foreign_value_or_null "kCFStringBinaryHeapCallBacks" CFBinaryHeapCallBacks.t
let kCFStringTransformFullwidthHalfwidth = foreign_value_or_null "kCFStringTransformFullwidthHalfwidth" (ptr CFString.t)
let kCFStringTransformHiraganaKatakana = foreign_value_or_null "kCFStringTransformHiraganaKatakana" (ptr CFString.t)
let kCFStringTransformLatinArabic = foreign_value_or_null "kCFStringTransformLatinArabic" (ptr CFString.t)
let kCFStringTransformLatinCyrillic = foreign_value_or_null "kCFStringTransformLatinCyrillic" (ptr CFString.t)
let kCFStringTransformLatinGreek = foreign_value_or_null "kCFStringTransformLatinGreek" (ptr CFString.t)
let kCFStringTransformLatinHangul = foreign_value_or_null "kCFStringTransformLatinHangul" (ptr CFString.t)
let kCFStringTransformLatinHebrew = foreign_value_or_null "kCFStringTransformLatinHebrew" (ptr CFString.t)
let kCFStringTransformLatinHiragana = foreign_value_or_null "kCFStringTransformLatinHiragana" (ptr CFString.t)
let kCFStringTransformLatinKatakana = foreign_value_or_null "kCFStringTransformLatinKatakana" (ptr CFString.t)
let kCFStringTransformLatinThai = foreign_value_or_null "kCFStringTransformLatinThai" (ptr CFString.t)
let kCFStringTransformMandarinLatin = foreign_value_or_null "kCFStringTransformMandarinLatin" (ptr CFString.t)
let kCFStringTransformStripCombiningMarks = foreign_value_or_null "kCFStringTransformStripCombiningMarks" (ptr CFString.t)
let kCFStringTransformStripDiacritics = foreign_value_or_null "kCFStringTransformStripDiacritics" (ptr CFString.t)
let kCFStringTransformToLatin = foreign_value_or_null "kCFStringTransformToLatin" (ptr CFString.t)
let kCFStringTransformToUnicodeName = foreign_value_or_null "kCFStringTransformToUnicodeName" (ptr CFString.t)
let kCFStringTransformToXMLHex = foreign_value_or_null "kCFStringTransformToXMLHex" (ptr CFString.t)
let kCFTimeZoneSystemTimeZoneDidChangeNotification = foreign_value_or_null "kCFTimeZoneSystemTimeZoneDidChangeNotification" (ptr CFString.t)
let kCFTypeArrayCallBacks = foreign_value_or_null "kCFTypeArrayCallBacks" CFArrayCallBacks.t
let kCFTypeBagCallBacks = foreign_value_or_null "kCFTypeBagCallBacks" CFBagCallBacks.t
let kCFTypeDictionaryKeyCallBacks = foreign_value_or_null "kCFTypeDictionaryKeyCallBacks" CFDictionaryKeyCallBacks.t
let kCFTypeDictionaryValueCallBacks = foreign_value_or_null "kCFTypeDictionaryValueCallBacks" CFDictionaryValueCallBacks.t
let kCFTypeSetCallBacks = foreign_value_or_null "kCFTypeSetCallBacks" CFSetCallBacks.t
let kCFURLAddedToDirectoryDateKey = foreign_value_or_null "kCFURLAddedToDirectoryDateKey" (ptr CFString.t)
let kCFURLApplicationIsScriptableKey = foreign_value_or_null "kCFURLApplicationIsScriptableKey" (ptr CFString.t)
let kCFURLAttributeModificationDateKey = foreign_value_or_null "kCFURLAttributeModificationDateKey" (ptr CFString.t)
let kCFURLCanonicalPathKey = foreign_value_or_null "kCFURLCanonicalPathKey" (ptr CFString.t)
let kCFURLContentAccessDateKey = foreign_value_or_null "kCFURLContentAccessDateKey" (ptr CFString.t)
let kCFURLContentModificationDateKey = foreign_value_or_null "kCFURLContentModificationDateKey" (ptr CFString.t)
let kCFURLCreationDateKey = foreign_value_or_null "kCFURLCreationDateKey" (ptr CFString.t)
let kCFURLCustomIconKey = foreign_value_or_null "kCFURLCustomIconKey" (ptr CFString.t)
let kCFURLDocumentIdentifierKey = foreign_value_or_null "kCFURLDocumentIdentifierKey" (ptr CFString.t)
let kCFURLEffectiveIconKey = foreign_value_or_null "kCFURLEffectiveIconKey" (ptr CFString.t)
let kCFURLFileAllocatedSizeKey = foreign_value_or_null "kCFURLFileAllocatedSizeKey" (ptr CFString.t)
let kCFURLFileContentIdentifierKey = foreign_value_or_null "kCFURLFileContentIdentifierKey" (ptr CFString.t)
let kCFURLFileDirectoryContents = foreign_value_or_null "kCFURLFileDirectoryContents" (ptr CFString.t)
let kCFURLFileExists = foreign_value_or_null "kCFURLFileExists" (ptr CFString.t)
let kCFURLFileLastModificationTime = foreign_value_or_null "kCFURLFileLastModificationTime" (ptr CFString.t)
let kCFURLFileLength = foreign_value_or_null "kCFURLFileLength" (ptr CFString.t)
let kCFURLFileOwnerID = foreign_value_or_null "kCFURLFileOwnerID" (ptr CFString.t)
let kCFURLFilePOSIXMode = foreign_value_or_null "kCFURLFilePOSIXMode" (ptr CFString.t)
let kCFURLFileProtectionComplete = foreign_value_or_null "kCFURLFileProtectionComplete" (ptr CFString.t)
let kCFURLFileProtectionCompleteUnlessOpen = foreign_value_or_null "kCFURLFileProtectionCompleteUnlessOpen" (ptr CFString.t)
let kCFURLFileProtectionCompleteUntilFirstUserAuthentication = foreign_value_or_null "kCFURLFileProtectionCompleteUntilFirstUserAuthentication" (ptr CFString.t)
let kCFURLFileProtectionKey = foreign_value_or_null "kCFURLFileProtectionKey" (ptr CFString.t)
let kCFURLFileProtectionNone = foreign_value_or_null "kCFURLFileProtectionNone" (ptr CFString.t)
let kCFURLFileResourceIdentifierKey = foreign_value_or_null "kCFURLFileResourceIdentifierKey" (ptr CFString.t)
let kCFURLFileResourceTypeBlockSpecial = foreign_value_or_null "kCFURLFileResourceTypeBlockSpecial" (ptr CFString.t)
let kCFURLFileResourceTypeCharacterSpecial = foreign_value_or_null "kCFURLFileResourceTypeCharacterSpecial" (ptr CFString.t)
let kCFURLFileResourceTypeDirectory = foreign_value_or_null "kCFURLFileResourceTypeDirectory" (ptr CFString.t)
let kCFURLFileResourceTypeKey = foreign_value_or_null "kCFURLFileResourceTypeKey" (ptr CFString.t)
let kCFURLFileResourceTypeNamedPipe = foreign_value_or_null "kCFURLFileResourceTypeNamedPipe" (ptr CFString.t)
let kCFURLFileResourceTypeRegular = foreign_value_or_null "kCFURLFileResourceTypeRegular" (ptr CFString.t)
let kCFURLFileResourceTypeSocket = foreign_value_or_null "kCFURLFileResourceTypeSocket" (ptr CFString.t)
let kCFURLFileResourceTypeSymbolicLink = foreign_value_or_null "kCFURLFileResourceTypeSymbolicLink" (ptr CFString.t)
let kCFURLFileResourceTypeUnknown = foreign_value_or_null "kCFURLFileResourceTypeUnknown" (ptr CFString.t)
let kCFURLFileSecurityKey = foreign_value_or_null "kCFURLFileSecurityKey" (ptr CFString.t)
let kCFURLFileSizeKey = foreign_value_or_null "kCFURLFileSizeKey" (ptr CFString.t)
let kCFURLGenerationIdentifierKey = foreign_value_or_null "kCFURLGenerationIdentifierKey" (ptr CFString.t)
let kCFURLHTTPStatusCode = foreign_value_or_null "kCFURLHTTPStatusCode" (ptr CFString.t)
let kCFURLHTTPStatusLine = foreign_value_or_null "kCFURLHTTPStatusLine" (ptr CFString.t)
let kCFURLHasHiddenExtensionKey = foreign_value_or_null "kCFURLHasHiddenExtensionKey" (ptr CFString.t)
let kCFURLIsAliasFileKey = foreign_value_or_null "kCFURLIsAliasFileKey" (ptr CFString.t)
let kCFURLIsApplicationKey = foreign_value_or_null "kCFURLIsApplicationKey" (ptr CFString.t)
let kCFURLIsDirectoryKey = foreign_value_or_null "kCFURLIsDirectoryKey" (ptr CFString.t)
let kCFURLIsExcludedFromBackupKey = foreign_value_or_null "kCFURLIsExcludedFromBackupKey" (ptr CFString.t)
let kCFURLIsExecutableKey = foreign_value_or_null "kCFURLIsExecutableKey" (ptr CFString.t)
let kCFURLIsHiddenKey = foreign_value_or_null "kCFURLIsHiddenKey" (ptr CFString.t)
let kCFURLIsMountTriggerKey = foreign_value_or_null "kCFURLIsMountTriggerKey" (ptr CFString.t)
let kCFURLIsPackageKey = foreign_value_or_null "kCFURLIsPackageKey" (ptr CFString.t)
let kCFURLIsPurgeableKey = foreign_value_or_null "kCFURLIsPurgeableKey" (ptr CFString.t)
let kCFURLIsReadableKey = foreign_value_or_null "kCFURLIsReadableKey" (ptr CFString.t)
let kCFURLIsRegularFileKey = foreign_value_or_null "kCFURLIsRegularFileKey" (ptr CFString.t)
let kCFURLIsSparseKey = foreign_value_or_null "kCFURLIsSparseKey" (ptr CFString.t)
let kCFURLIsSymbolicLinkKey = foreign_value_or_null "kCFURLIsSymbolicLinkKey" (ptr CFString.t)
let kCFURLIsSystemImmutableKey = foreign_value_or_null "kCFURLIsSystemImmutableKey" (ptr CFString.t)
let kCFURLIsUbiquitousItemKey = foreign_value_or_null "kCFURLIsUbiquitousItemKey" (ptr CFString.t)
let kCFURLIsUserImmutableKey = foreign_value_or_null "kCFURLIsUserImmutableKey" (ptr CFString.t)
let kCFURLIsVolumeKey = foreign_value_or_null "kCFURLIsVolumeKey" (ptr CFString.t)
let kCFURLIsWritableKey = foreign_value_or_null "kCFURLIsWritableKey" (ptr CFString.t)
let kCFURLKeysOfUnsetValuesKey = foreign_value_or_null "kCFURLKeysOfUnsetValuesKey" (ptr CFString.t)
let kCFURLLabelColorKey = foreign_value_or_null "kCFURLLabelColorKey" (ptr CFString.t)
let kCFURLLabelNumberKey = foreign_value_or_null "kCFURLLabelNumberKey" (ptr CFString.t)
let kCFURLLinkCountKey = foreign_value_or_null "kCFURLLinkCountKey" (ptr CFString.t)
let kCFURLLocalizedLabelKey = foreign_value_or_null "kCFURLLocalizedLabelKey" (ptr CFString.t)
let kCFURLLocalizedNameKey = foreign_value_or_null "kCFURLLocalizedNameKey" (ptr CFString.t)
let kCFURLLocalizedTypeDescriptionKey = foreign_value_or_null "kCFURLLocalizedTypeDescriptionKey" (ptr CFString.t)
let kCFURLMayHaveExtendedAttributesKey = foreign_value_or_null "kCFURLMayHaveExtendedAttributesKey" (ptr CFString.t)
let kCFURLMayShareFileContentKey = foreign_value_or_null "kCFURLMayShareFileContentKey" (ptr CFString.t)
let kCFURLNameKey = foreign_value_or_null "kCFURLNameKey" (ptr CFString.t)
let kCFURLParentDirectoryURLKey = foreign_value_or_null "kCFURLParentDirectoryURLKey" (ptr CFString.t)
let kCFURLPathKey = foreign_value_or_null "kCFURLPathKey" (ptr CFString.t)
let kCFURLPreferredIOBlockSizeKey = foreign_value_or_null "kCFURLPreferredIOBlockSizeKey" (ptr CFString.t)
let kCFURLQuarantinePropertiesKey = foreign_value_or_null "kCFURLQuarantinePropertiesKey" (ptr CFString.t)
let kCFURLTagNamesKey = foreign_value_or_null "kCFURLTagNamesKey" (ptr CFString.t)
let kCFURLTotalFileAllocatedSizeKey = foreign_value_or_null "kCFURLTotalFileAllocatedSizeKey" (ptr CFString.t)
let kCFURLTotalFileSizeKey = foreign_value_or_null "kCFURLTotalFileSizeKey" (ptr CFString.t)
let kCFURLTypeIdentifierKey = foreign_value_or_null "kCFURLTypeIdentifierKey" (ptr CFString.t)
let kCFURLUbiquitousItemDownloadingErrorKey = foreign_value_or_null "kCFURLUbiquitousItemDownloadingErrorKey" (ptr CFString.t)
let kCFURLUbiquitousItemDownloadingStatusCurrent = foreign_value_or_null "kCFURLUbiquitousItemDownloadingStatusCurrent" (ptr CFString.t)
let kCFURLUbiquitousItemDownloadingStatusDownloaded = foreign_value_or_null "kCFURLUbiquitousItemDownloadingStatusDownloaded" (ptr CFString.t)
let kCFURLUbiquitousItemDownloadingStatusKey = foreign_value_or_null "kCFURLUbiquitousItemDownloadingStatusKey" (ptr CFString.t)
let kCFURLUbiquitousItemDownloadingStatusNotDownloaded = foreign_value_or_null "kCFURLUbiquitousItemDownloadingStatusNotDownloaded" (ptr CFString.t)
let kCFURLUbiquitousItemHasUnresolvedConflictsKey = foreign_value_or_null "kCFURLUbiquitousItemHasUnresolvedConflictsKey" (ptr CFString.t)
let kCFURLUbiquitousItemIsDownloadedKey = foreign_value_or_null "kCFURLUbiquitousItemIsDownloadedKey" (ptr CFString.t)
let kCFURLUbiquitousItemIsDownloadingKey = foreign_value_or_null "kCFURLUbiquitousItemIsDownloadingKey" (ptr CFString.t)
let kCFURLUbiquitousItemIsExcludedFromSyncKey = foreign_value_or_null "kCFURLUbiquitousItemIsExcludedFromSyncKey" (ptr CFString.t)
let kCFURLUbiquitousItemIsUploadedKey = foreign_value_or_null "kCFURLUbiquitousItemIsUploadedKey" (ptr CFString.t)
let kCFURLUbiquitousItemIsUploadingKey = foreign_value_or_null "kCFURLUbiquitousItemIsUploadingKey" (ptr CFString.t)
let kCFURLUbiquitousItemPercentDownloadedKey = foreign_value_or_null "kCFURLUbiquitousItemPercentDownloadedKey" (ptr CFString.t)
let kCFURLUbiquitousItemPercentUploadedKey = foreign_value_or_null "kCFURLUbiquitousItemPercentUploadedKey" (ptr CFString.t)
let kCFURLUbiquitousItemUploadingErrorKey = foreign_value_or_null "kCFURLUbiquitousItemUploadingErrorKey" (ptr CFString.t)
let kCFURLVolumeAvailableCapacityForImportantUsageKey = foreign_value_or_null "kCFURLVolumeAvailableCapacityForImportantUsageKey" (ptr CFString.t)
let kCFURLVolumeAvailableCapacityForOpportunisticUsageKey = foreign_value_or_null "kCFURLVolumeAvailableCapacityForOpportunisticUsageKey" (ptr CFString.t)
let kCFURLVolumeAvailableCapacityKey = foreign_value_or_null "kCFURLVolumeAvailableCapacityKey" (ptr CFString.t)
let kCFURLVolumeCreationDateKey = foreign_value_or_null "kCFURLVolumeCreationDateKey" (ptr CFString.t)
let kCFURLVolumeIdentifierKey = foreign_value_or_null "kCFURLVolumeIdentifierKey" (ptr CFString.t)
let kCFURLVolumeIsAutomountedKey = foreign_value_or_null "kCFURLVolumeIsAutomountedKey" (ptr CFString.t)
let kCFURLVolumeIsBrowsableKey = foreign_value_or_null "kCFURLVolumeIsBrowsableKey" (ptr CFString.t)
let kCFURLVolumeIsEjectableKey = foreign_value_or_null "kCFURLVolumeIsEjectableKey" (ptr CFString.t)
let kCFURLVolumeIsEncryptedKey = foreign_value_or_null "kCFURLVolumeIsEncryptedKey" (ptr CFString.t)
let kCFURLVolumeIsInternalKey = foreign_value_or_null "kCFURLVolumeIsInternalKey" (ptr CFString.t)
let kCFURLVolumeIsJournalingKey = foreign_value_or_null "kCFURLVolumeIsJournalingKey" (ptr CFString.t)
let kCFURLVolumeIsLocalKey = foreign_value_or_null "kCFURLVolumeIsLocalKey" (ptr CFString.t)
let kCFURLVolumeIsReadOnlyKey = foreign_value_or_null "kCFURLVolumeIsReadOnlyKey" (ptr CFString.t)
let kCFURLVolumeIsRemovableKey = foreign_value_or_null "kCFURLVolumeIsRemovableKey" (ptr CFString.t)
let kCFURLVolumeIsRootFileSystemKey = foreign_value_or_null "kCFURLVolumeIsRootFileSystemKey" (ptr CFString.t)
let kCFURLVolumeLocalizedFormatDescriptionKey = foreign_value_or_null "kCFURLVolumeLocalizedFormatDescriptionKey" (ptr CFString.t)
let kCFURLVolumeLocalizedNameKey = foreign_value_or_null "kCFURLVolumeLocalizedNameKey" (ptr CFString.t)
let kCFURLVolumeMaximumFileSizeKey = foreign_value_or_null "kCFURLVolumeMaximumFileSizeKey" (ptr CFString.t)
let kCFURLVolumeNameKey = foreign_value_or_null "kCFURLVolumeNameKey" (ptr CFString.t)
let kCFURLVolumeResourceCountKey = foreign_value_or_null "kCFURLVolumeResourceCountKey" (ptr CFString.t)
let kCFURLVolumeSupportsAccessPermissionsKey = foreign_value_or_null "kCFURLVolumeSupportsAccessPermissionsKey" (ptr CFString.t)
let kCFURLVolumeSupportsAdvisoryFileLockingKey = foreign_value_or_null "kCFURLVolumeSupportsAdvisoryFileLockingKey" (ptr CFString.t)
let kCFURLVolumeSupportsCasePreservedNamesKey = foreign_value_or_null "kCFURLVolumeSupportsCasePreservedNamesKey" (ptr CFString.t)
let kCFURLVolumeSupportsCaseSensitiveNamesKey = foreign_value_or_null "kCFURLVolumeSupportsCaseSensitiveNamesKey" (ptr CFString.t)
let kCFURLVolumeSupportsCompressionKey = foreign_value_or_null "kCFURLVolumeSupportsCompressionKey" (ptr CFString.t)
let kCFURLVolumeSupportsExclusiveRenamingKey = foreign_value_or_null "kCFURLVolumeSupportsExclusiveRenamingKey" (ptr CFString.t)
let kCFURLVolumeSupportsExtendedSecurityKey = foreign_value_or_null "kCFURLVolumeSupportsExtendedSecurityKey" (ptr CFString.t)
let kCFURLVolumeSupportsFileCloningKey = foreign_value_or_null "kCFURLVolumeSupportsFileCloningKey" (ptr CFString.t)
let kCFURLVolumeSupportsFileProtectionKey = foreign_value_or_null "kCFURLVolumeSupportsFileProtectionKey" (ptr CFString.t)
let kCFURLVolumeSupportsHardLinksKey = foreign_value_or_null "kCFURLVolumeSupportsHardLinksKey" (ptr CFString.t)
let kCFURLVolumeSupportsImmutableFilesKey = foreign_value_or_null "kCFURLVolumeSupportsImmutableFilesKey" (ptr CFString.t)
let kCFURLVolumeSupportsJournalingKey = foreign_value_or_null "kCFURLVolumeSupportsJournalingKey" (ptr CFString.t)
let kCFURLVolumeSupportsPersistentIDsKey = foreign_value_or_null "kCFURLVolumeSupportsPersistentIDsKey" (ptr CFString.t)
let kCFURLVolumeSupportsRenamingKey = foreign_value_or_null "kCFURLVolumeSupportsRenamingKey" (ptr CFString.t)
let kCFURLVolumeSupportsRootDirectoryDatesKey = foreign_value_or_null "kCFURLVolumeSupportsRootDirectoryDatesKey" (ptr CFString.t)
let kCFURLVolumeSupportsSparseFilesKey = foreign_value_or_null "kCFURLVolumeSupportsSparseFilesKey" (ptr CFString.t)
let kCFURLVolumeSupportsSwapRenamingKey = foreign_value_or_null "kCFURLVolumeSupportsSwapRenamingKey" (ptr CFString.t)
let kCFURLVolumeSupportsSymbolicLinksKey = foreign_value_or_null "kCFURLVolumeSupportsSymbolicLinksKey" (ptr CFString.t)
let kCFURLVolumeSupportsVolumeSizesKey = foreign_value_or_null "kCFURLVolumeSupportsVolumeSizesKey" (ptr CFString.t)
let kCFURLVolumeSupportsZeroRunsKey = foreign_value_or_null "kCFURLVolumeSupportsZeroRunsKey" (ptr CFString.t)
let kCFURLVolumeTotalCapacityKey = foreign_value_or_null "kCFURLVolumeTotalCapacityKey" (ptr CFString.t)
let kCFURLVolumeURLForRemountingKey = foreign_value_or_null "kCFURLVolumeURLForRemountingKey" (ptr CFString.t)
let kCFURLVolumeURLKey = foreign_value_or_null "kCFURLVolumeURLKey" (ptr CFString.t)
let kCFURLVolumeUUIDStringKey = foreign_value_or_null "kCFURLVolumeUUIDStringKey" (ptr CFString.t)
let kCFUserNotificationAlertHeaderKey = foreign_value_or_null "kCFUserNotificationAlertHeaderKey" (ptr CFString.t)
let kCFUserNotificationAlertMessageKey = foreign_value_or_null "kCFUserNotificationAlertMessageKey" (ptr CFString.t)
let kCFUserNotificationAlertTopMostKey = foreign_value_or_null "kCFUserNotificationAlertTopMostKey" (ptr CFString.t)
let kCFUserNotificationAlternateButtonTitleKey = foreign_value_or_null "kCFUserNotificationAlternateButtonTitleKey" (ptr CFString.t)
let kCFUserNotificationCheckBoxTitlesKey = foreign_value_or_null "kCFUserNotificationCheckBoxTitlesKey" (ptr CFString.t)
let kCFUserNotificationDefaultButtonTitleKey = foreign_value_or_null "kCFUserNotificationDefaultButtonTitleKey" (ptr CFString.t)
let kCFUserNotificationIconURLKey = foreign_value_or_null "kCFUserNotificationIconURLKey" (ptr CFString.t)
let kCFUserNotificationKeyboardTypesKey = foreign_value_or_null "kCFUserNotificationKeyboardTypesKey" (ptr CFString.t)
let kCFUserNotificationLocalizationURLKey = foreign_value_or_null "kCFUserNotificationLocalizationURLKey" (ptr CFString.t)
let kCFUserNotificationOtherButtonTitleKey = foreign_value_or_null "kCFUserNotificationOtherButtonTitleKey" (ptr CFString.t)
let kCFUserNotificationPopUpSelectionKey = foreign_value_or_null "kCFUserNotificationPopUpSelectionKey" (ptr CFString.t)
let kCFUserNotificationPopUpTitlesKey = foreign_value_or_null "kCFUserNotificationPopUpTitlesKey" (ptr CFString.t)
let kCFUserNotificationProgressIndicatorValueKey = foreign_value_or_null "kCFUserNotificationProgressIndicatorValueKey" (ptr CFString.t)
let kCFUserNotificationSoundURLKey = foreign_value_or_null "kCFUserNotificationSoundURLKey" (ptr CFString.t)
let kCFUserNotificationTextFieldTitlesKey = foreign_value_or_null "kCFUserNotificationTextFieldTitlesKey" (ptr CFString.t)
let kCFUserNotificationTextFieldValuesKey = foreign_value_or_null "kCFUserNotificationTextFieldValuesKey" (ptr CFString.t)
let kCFXMLTreeErrorDescription = foreign_value_or_null "kCFXMLTreeErrorDescription" (ptr CFString.t)
let kCFXMLTreeErrorLineNumber = foreign_value_or_null "kCFXMLTreeErrorLineNumber" (ptr CFString.t)
let kCFXMLTreeErrorLocation = foreign_value_or_null "kCFXMLTreeErrorLocation" (ptr CFString.t)
let kCFXMLTreeErrorStatusCode = foreign_value_or_null "kCFXMLTreeErrorStatusCode" (ptr CFString.t)
let _CFByteOrderBigEndian = 2
let _CFByteOrderLittleEndian = 1
let _CFByteOrderUnknown = 0
let _CFNotificationSuspensionBehaviorCoalesce = 2
let _CFNotificationSuspensionBehaviorDeliverImmediately = 4
let _CFNotificationSuspensionBehaviorDrop = 1
let _CFNotificationSuspensionBehaviorHold = 3
let _CF_USE_OSBYTEORDER_H = 1
let _COREFOUNDATION_CFPLUGINCOM_SEPARATE = 1
let _E_ABORT = -2147483641
let _E_ACCESSDENIED = -2147483639
let _E_FAIL = -2147483640
let _E_HANDLE = -2147483642
let _E_INVALIDARG = -2147483645
let _E_NOINTERFACE = -2147483644
let _E_NOTIMPL = -2147483647
let _E_OUTOFMEMORY = -2147483646
let _E_POINTER = -2147483643
let _E_UNEXPECTED = -2147418113
let _FALSE = 0
let _ISA_PTRAUTH_DISCRIMINATOR = 27361
let _SEVERITY_ERROR = 1
let _SEVERITY_SUCCESS = 0
let _S_FALSE = 1
let _S_OK = 0
let _TRUE = 1
let kCFBookmarkResolutionWithoutMountingMask = 512
let kCFBookmarkResolutionWithoutUIMask = 256
let kCFBundleExecutableArchitectureARM64 = 16777228
let kCFBundleExecutableArchitectureI386 = 7
let kCFBundleExecutableArchitecturePPC = 18
let kCFBundleExecutableArchitecturePPC64 = 16777234
let kCFBundleExecutableArchitectureX86_64 = 16777223
let kCFCalendarComponentsWrap = 1
let kCFCalendarUnitDay = 16
let kCFCalendarUnitEra = 2
let kCFCalendarUnitHour = 32
let kCFCalendarUnitMinute = 64
let kCFCalendarUnitMonth = 8
let kCFCalendarUnitQuarter = 2048
let kCFCalendarUnitSecond = 128
let kCFCalendarUnitWeek = 256
let kCFCalendarUnitWeekOfMonth = 4096
let kCFCalendarUnitWeekOfYear = 8192
let kCFCalendarUnitWeekday = 512
let kCFCalendarUnitWeekdayOrdinal = 1024
let kCFCalendarUnitYear = 4
let kCFCalendarUnitYearForWeekOfYear = 16384
let kCFCharacterSetAlphaNumeric = 10
let kCFCharacterSetCapitalizedLetter = 13
let kCFCharacterSetControl = 1
let kCFCharacterSetDecimalDigit = 4
let kCFCharacterSetDecomposable = 9
let kCFCharacterSetIllegal = 12
let kCFCharacterSetLetter = 5
let kCFCharacterSetLowercaseLetter = 6
let kCFCharacterSetNewline = 15
let kCFCharacterSetNonBase = 8
let kCFCharacterSetPunctuation = 11
let kCFCharacterSetSymbol = 14
let kCFCharacterSetUppercaseLetter = 7
let kCFCharacterSetWhitespace = 2
let kCFCharacterSetWhitespaceAndNewline = 3
let kCFCompareAnchored = 8
let kCFCompareBackwards = 4
let kCFCompareCaseInsensitive = 1
let kCFCompareDiacriticInsensitive = 128
let kCFCompareEqualTo = 0
let kCFCompareForcedOrdering = 512
let kCFCompareGreaterThan = 1
let kCFCompareLessThan = -1
let kCFCompareLocalized = 32
let kCFCompareNonliteral = 16
let kCFCompareNumerically = 64
let kCFCompareWidthInsensitive = 256
let kCFCoreFoundationVersionNumber10_0 = 196.400000
let kCFCoreFoundationVersionNumber10_0_3 = 196.500000
let kCFCoreFoundationVersionNumber10_1 = 226.000000
let kCFCoreFoundationVersionNumber10_10 = 1151.160000
let kCFCoreFoundationVersionNumber10_10_1 = 1151.160000
let kCFCoreFoundationVersionNumber10_10_2 = 1152
let kCFCoreFoundationVersionNumber10_10_3 = 1153.180000
let kCFCoreFoundationVersionNumber10_10_4 = 1153.180000
let kCFCoreFoundationVersionNumber10_10_5 = 1153.180000
let kCFCoreFoundationVersionNumber10_10_Max = 1199
let kCFCoreFoundationVersionNumber10_11 = 1253
let kCFCoreFoundationVersionNumber10_11_1 = 1255.100000
let kCFCoreFoundationVersionNumber10_11_2 = 1256.140000
let kCFCoreFoundationVersionNumber10_11_3 = 1256.140000
let kCFCoreFoundationVersionNumber10_11_4 = 1258.100000
let kCFCoreFoundationVersionNumber10_11_Max = 1299
let kCFCoreFoundationVersionNumber10_1_1 = 226.000000
let kCFCoreFoundationVersionNumber10_1_2 = 227.200000
let kCFCoreFoundationVersionNumber10_1_3 = 227.200000
let kCFCoreFoundationVersionNumber10_1_4 = 227.300000
let kCFCoreFoundationVersionNumber10_2 = 263.000000
let kCFCoreFoundationVersionNumber10_2_1 = 263.100000
let kCFCoreFoundationVersionNumber10_2_2 = 263.100000
let kCFCoreFoundationVersionNumber10_2_3 = 263.300000
let kCFCoreFoundationVersionNumber10_2_4 = 263.300000
let kCFCoreFoundationVersionNumber10_2_5 = 263.500000
let kCFCoreFoundationVersionNumber10_2_6 = 263.500000
let kCFCoreFoundationVersionNumber10_2_7 = 263.500000
let kCFCoreFoundationVersionNumber10_2_8 = 263.500000
let kCFCoreFoundationVersionNumber10_3 = 299.000000
let kCFCoreFoundationVersionNumber10_3_1 = 299.000000
let kCFCoreFoundationVersionNumber10_3_2 = 299.000000
let kCFCoreFoundationVersionNumber10_3_3 = 299.300000
let kCFCoreFoundationVersionNumber10_3_4 = 299.310000
let kCFCoreFoundationVersionNumber10_3_5 = 299.310000
let kCFCoreFoundationVersionNumber10_3_6 = 299.320000
let kCFCoreFoundationVersionNumber10_3_7 = 299.330000
let kCFCoreFoundationVersionNumber10_3_8 = 299.330000
let kCFCoreFoundationVersionNumber10_3_9 = 299.350000
let kCFCoreFoundationVersionNumber10_4 = 368.000000
let kCFCoreFoundationVersionNumber10_4_1 = 368.100000
let kCFCoreFoundationVersionNumber10_4_10 = 368.280000
let kCFCoreFoundationVersionNumber10_4_11 = 368.310000
let kCFCoreFoundationVersionNumber10_4_2 = 368.110000
let kCFCoreFoundationVersionNumber10_4_3 = 368.180000
let kCFCoreFoundationVersionNumber10_4_4_Intel = 368.260000
let kCFCoreFoundationVersionNumber10_4_4_PowerPC = 368.250000
let kCFCoreFoundationVersionNumber10_4_5_Intel = 368.260000
let kCFCoreFoundationVersionNumber10_4_5_PowerPC = 368.250000
let kCFCoreFoundationVersionNumber10_4_6_Intel = 368.260000
let kCFCoreFoundationVersionNumber10_4_6_PowerPC = 368.250000
let kCFCoreFoundationVersionNumber10_4_7 = 368.270000
let kCFCoreFoundationVersionNumber10_4_8 = 368.270000
let kCFCoreFoundationVersionNumber10_4_9 = 368.280000
let kCFCoreFoundationVersionNumber10_5 = 476.000000
let kCFCoreFoundationVersionNumber10_5_1 = 476.000000
let kCFCoreFoundationVersionNumber10_5_2 = 476.100000
let kCFCoreFoundationVersionNumber10_5_3 = 476.130000
let kCFCoreFoundationVersionNumber10_5_4 = 476.140000
let kCFCoreFoundationVersionNumber10_5_5 = 476.150000
let kCFCoreFoundationVersionNumber10_5_6 = 476.170000
let kCFCoreFoundationVersionNumber10_5_7 = 476.180000
let kCFCoreFoundationVersionNumber10_5_8 = 476.190000
let kCFCoreFoundationVersionNumber10_6 = 550.000000
let kCFCoreFoundationVersionNumber10_6_1 = 550.000000
let kCFCoreFoundationVersionNumber10_6_2 = 550.130000
let kCFCoreFoundationVersionNumber10_6_3 = 550.190000
let kCFCoreFoundationVersionNumber10_6_4 = 550.290000
let kCFCoreFoundationVersionNumber10_6_5 = 550.420000
let kCFCoreFoundationVersionNumber10_6_6 = 550.420000
let kCFCoreFoundationVersionNumber10_6_7 = 550.420000
let kCFCoreFoundationVersionNumber10_6_8 = 550.430000
let kCFCoreFoundationVersionNumber10_7 = 635.000000
let kCFCoreFoundationVersionNumber10_7_1 = 635.000000
let kCFCoreFoundationVersionNumber10_7_2 = 635.150000
let kCFCoreFoundationVersionNumber10_7_3 = 635.190000
let kCFCoreFoundationVersionNumber10_7_4 = 635.210000
let kCFCoreFoundationVersionNumber10_7_5 = 635.210000
let kCFCoreFoundationVersionNumber10_8 = 744.000000
let kCFCoreFoundationVersionNumber10_8_1 = 744.000000
let kCFCoreFoundationVersionNumber10_8_2 = 744.120000
let kCFCoreFoundationVersionNumber10_8_3 = 744.180000
let kCFCoreFoundationVersionNumber10_8_4 = 744.190000
let kCFCoreFoundationVersionNumber10_9 = 855.110000
let kCFCoreFoundationVersionNumber10_9_1 = 855.110000
let kCFCoreFoundationVersionNumber10_9_2 = 855.140000
let kCFDataSearchAnchored = 2
let kCFDataSearchBackwards = 1
let kCFDateFormatterFullStyle = 4
let kCFDateFormatterLongStyle = 3
let kCFDateFormatterMediumStyle = 2
let kCFDateFormatterNoStyle = 0
let kCFDateFormatterShortStyle = 1
let kCFFileDescriptorReadCallBack = 1
let kCFFileDescriptorWriteCallBack = 2
let kCFFileSecurityClearAccessControlList = 32
let kCFFileSecurityClearGroup = 2
let kCFFileSecurityClearGroupUUID = 16
let kCFFileSecurityClearMode = 4
let kCFFileSecurityClearOwner = 1
let kCFFileSecurityClearOwnerUUID = 8
let kCFGregorianAllUnits = 16777215
let kCFGregorianUnitsDays = 4
let kCFGregorianUnitsHours = 8
let kCFGregorianUnitsMinutes = 16
let kCFGregorianUnitsMonths = 2
let kCFGregorianUnitsSeconds = 32
let kCFGregorianUnitsYears = 1
let kCFISO8601DateFormatWithColonSeparatorInTime = 512
let kCFISO8601DateFormatWithColonSeparatorInTimeZone = 1024
let kCFISO8601DateFormatWithDashSeparatorInDate = 256
let kCFISO8601DateFormatWithDay = 16
let kCFISO8601DateFormatWithFractionalSeconds = 2048
let kCFISO8601DateFormatWithFullDate = 275
let kCFISO8601DateFormatWithFullTime = 1632
let kCFISO8601DateFormatWithInternetDateTime = 1907
let kCFISO8601DateFormatWithMonth = 2
let kCFISO8601DateFormatWithSpaceBetweenDateAndTime = 128
let kCFISO8601DateFormatWithTime = 32
let kCFISO8601DateFormatWithTimeZone = 64
let kCFISO8601DateFormatWithWeekOfYear = 4
let kCFISO8601DateFormatWithYear = 1
let kCFLocaleLanguageDirectionBottomToTop = 4
let kCFLocaleLanguageDirectionLeftToRight = 1
let kCFLocaleLanguageDirectionRightToLeft = 2
let kCFLocaleLanguageDirectionTopToBottom = 3
let kCFLocaleLanguageDirectionUnknown = 0
let kCFMessagePortBecameInvalidError = -5
let kCFMessagePortIsInvalid = -3
let kCFMessagePortReceiveTimeout = -2
let kCFMessagePortSendTimeout = -1
let kCFMessagePortSuccess = 0
let kCFMessagePortTransportError = -4
let kCFNotFound = -1
let kCFNotificationDeliverImmediately = 1
let kCFNotificationPostToAllSessions = 2
let kCFNumberCFIndexType = 14
let kCFNumberCGFloatType = 16
let kCFNumberCharType = 7
let kCFNumberDoubleType = 13
let kCFNumberFloat32Type = 5
let kCFNumberFloat64Type = 6
let kCFNumberFloatType = 12
let kCFNumberFormatterCurrencyAccountingStyle = 10
let kCFNumberFormatterCurrencyISOCodeStyle = 8
let kCFNumberFormatterCurrencyPluralStyle = 9
let kCFNumberFormatterCurrencyStyle = 2
let kCFNumberFormatterDecimalStyle = 1
let kCFNumberFormatterNoStyle = 0
let kCFNumberFormatterOrdinalStyle = 6
let kCFNumberFormatterPadAfterPrefix = 1
let kCFNumberFormatterPadAfterSuffix = 3
let kCFNumberFormatterPadBeforePrefix = 0
let kCFNumberFormatterPadBeforeSuffix = 2
let kCFNumberFormatterParseIntegersOnly = 1
let kCFNumberFormatterPercentStyle = 3
let kCFNumberFormatterRoundCeiling = 0
let kCFNumberFormatterRoundDown = 2
let kCFNumberFormatterRoundFloor = 1
let kCFNumberFormatterRoundHalfDown = 5
let kCFNumberFormatterRoundHalfEven = 4
let kCFNumberFormatterRoundHalfUp = 6
let kCFNumberFormatterRoundUp = 3
let kCFNumberFormatterScientificStyle = 4
let kCFNumberFormatterSpellOutStyle = 5
let kCFNumberIntType = 9
let kCFNumberLongLongType = 11
let kCFNumberLongType = 10
let kCFNumberMaxType = 16
let kCFNumberNSIntegerType = 15
let kCFNumberSInt16Type = 2
let kCFNumberSInt32Type = 3
let kCFNumberSInt64Type = 4
let kCFNumberSInt8Type = 1
let kCFNumberShortType = 8
let kCFPropertyListBinaryFormat_v1_0 = 200
let kCFPropertyListImmutable = 0
let kCFPropertyListMutableContainers = 1
let kCFPropertyListMutableContainersAndLeaves = 2
let kCFPropertyListOpenStepFormat = 1
let kCFPropertyListReadCorruptError = 3840
let kCFPropertyListReadStreamError = 3842
let kCFPropertyListReadUnknownVersionError = 3841
let kCFPropertyListWriteStreamError = 3851
let kCFPropertyListXMLFormat_v1_0 = 100
let kCFRunLoopAfterWaiting = 64
let kCFRunLoopAllActivities = 268435455
let kCFRunLoopBeforeSources = 4
let kCFRunLoopBeforeTimers = 2
let kCFRunLoopBeforeWaiting = 32
let kCFRunLoopEntry = 1
let kCFRunLoopExit = 128
let kCFRunLoopRunFinished = 1
let kCFRunLoopRunHandledSource = 4
let kCFRunLoopRunStopped = 2
let kCFRunLoopRunTimedOut = 3
let kCFSocketAcceptCallBack = 2
let kCFSocketAutomaticallyReenableAcceptCallBack = 2
let kCFSocketAutomaticallyReenableDataCallBack = 3
let kCFSocketAutomaticallyReenableReadCallBack = 1
let kCFSocketAutomaticallyReenableWriteCallBack = 8
let kCFSocketCloseOnInvalidate = 128
let kCFSocketConnectCallBack = 4
let kCFSocketDataCallBack = 3
let kCFSocketError = -1
let kCFSocketLeaveErrors = 64
let kCFSocketNoCallBack = 0
let kCFSocketReadCallBack = 1
let kCFSocketSuccess = 0
let kCFSocketTimeout = -2
let kCFSocketWriteCallBack = 8
let kCFStreamErrorDomainCustom = -1
let kCFStreamErrorDomainMacOSStatus = 2
let kCFStreamErrorDomainPOSIX = 1
let kCFStreamEventCanAcceptBytes = 4
let kCFStreamEventEndEncountered = 16
let kCFStreamEventErrorOccurred = 8
let kCFStreamEventHasBytesAvailable = 2
let kCFStreamEventNone = 0
let kCFStreamEventOpenCompleted = 1
let kCFStreamStatusAtEnd = 5
let kCFStreamStatusClosed = 6
let kCFStreamStatusError = 7
let kCFStreamStatusNotOpen = 0
let kCFStreamStatusOpen = 2
let kCFStreamStatusOpening = 1
let kCFStreamStatusReading = 3
let kCFStreamStatusWriting = 4
let kCFStringEncodingANSEL = 1537
let kCFStringEncodingASCII = 1536
let kCFStringEncodingBig5 = 2563
let kCFStringEncodingBig5_E = 2569
let kCFStringEncodingBig5_HKSCS_1999 = 2566
let kCFStringEncodingCNS_11643_92_P1 = 1617
let kCFStringEncodingCNS_11643_92_P2 = 1618
let kCFStringEncodingCNS_11643_92_P3 = 1619
let kCFStringEncodingDOSArabic = 1049
let kCFStringEncodingDOSBalticRim = 1030
let kCFStringEncodingDOSCanadianFrench = 1048
let kCFStringEncodingDOSChineseSimplif = 1057
let kCFStringEncodingDOSChineseTrad = 1059
let kCFStringEncodingDOSCyrillic = 1043
let kCFStringEncodingDOSGreek = 1029
let kCFStringEncodingDOSGreek1 = 1041
let kCFStringEncodingDOSGreek2 = 1052
let kCFStringEncodingDOSHebrew = 1047
let kCFStringEncodingDOSIcelandic = 1046
let kCFStringEncodingDOSJapanese = 1056
let kCFStringEncodingDOSKorean = 1058
let kCFStringEncodingDOSLatin1 = 1040
let kCFStringEncodingDOSLatin2 = 1042
let kCFStringEncodingDOSLatinUS = 1024
let kCFStringEncodingDOSNordic = 1050
let kCFStringEncodingDOSPortuguese = 1045
let kCFStringEncodingDOSRussian = 1051
let kCFStringEncodingDOSThai = 1053
let kCFStringEncodingDOSTurkish = 1044
let kCFStringEncodingEBCDIC_CP037 = 3074
let kCFStringEncodingEBCDIC_US = 3073
let kCFStringEncodingEUC_CN = 2352
let kCFStringEncodingEUC_JP = 2336
let kCFStringEncodingEUC_KR = 2368
let kCFStringEncodingEUC_TW = 2353
let kCFStringEncodingGBK_95 = 1585
let kCFStringEncodingGB_18030_2000 = 1586
let kCFStringEncodingGB_2312_80 = 1584
let kCFStringEncodingHZ_GB_2312 = 2565
let kCFStringEncodingISOLatin1 = 513
let kCFStringEncodingISOLatin10 = 528
let kCFStringEncodingISOLatin2 = 514
let kCFStringEncodingISOLatin3 = 515
let kCFStringEncodingISOLatin4 = 516
let kCFStringEncodingISOLatin5 = 521
let kCFStringEncodingISOLatin6 = 522
let kCFStringEncodingISOLatin7 = 525
let kCFStringEncodingISOLatin8 = 526
let kCFStringEncodingISOLatin9 = 527
let kCFStringEncodingISOLatinArabic = 518
let kCFStringEncodingISOLatinCyrillic = 517
let kCFStringEncodingISOLatinGreek = 519
let kCFStringEncodingISOLatinHebrew = 520
let kCFStringEncodingISOLatinThai = 523
let kCFStringEncodingISO_2022_CN = 2096
let kCFStringEncodingISO_2022_CN_EXT = 2097
let kCFStringEncodingISO_2022_JP = 2080
let kCFStringEncodingISO_2022_JP_1 = 2082
let kCFStringEncodingISO_2022_JP_2 = 2081
let kCFStringEncodingISO_2022_JP_3 = 2083
let kCFStringEncodingISO_2022_KR = 2112
let kCFStringEncodingInvalidId = -1
let kCFStringEncodingJIS_C6226_78 = 1572
let kCFStringEncodingJIS_X0201_76 = 1568
let kCFStringEncodingJIS_X0208_83 = 1569
let kCFStringEncodingJIS_X0208_90 = 1570
let kCFStringEncodingJIS_X0212_90 = 1571
let kCFStringEncodingKOI8_R = 2562
let kCFStringEncodingKOI8_U = 2568
let kCFStringEncodingKSC_5601_87 = 1600
let kCFStringEncodingKSC_5601_92_Johab = 1601
let kCFStringEncodingMacArabic = 4
let kCFStringEncodingMacArmenian = 24
let kCFStringEncodingMacBengali = 13
let kCFStringEncodingMacBurmese = 19
let kCFStringEncodingMacCeltic = 39
let kCFStringEncodingMacCentralEurRoman = 29
let kCFStringEncodingMacChineseSimp = 25
let kCFStringEncodingMacChineseTrad = 2
let kCFStringEncodingMacCroatian = 36
let kCFStringEncodingMacCyrillic = 7
let kCFStringEncodingMacDevanagari = 9
let kCFStringEncodingMacDingbats = 34
let kCFStringEncodingMacEthiopic = 28
let kCFStringEncodingMacExtArabic = 31
let kCFStringEncodingMacFarsi = 140
let kCFStringEncodingMacGaelic = 40
let kCFStringEncodingMacGeorgian = 23
let kCFStringEncodingMacGreek = 6
let kCFStringEncodingMacGujarati = 11
let kCFStringEncodingMacGurmukhi = 10
let kCFStringEncodingMacHFS = 255
let kCFStringEncodingMacHebrew = 5
let kCFStringEncodingMacIcelandic = 37
let kCFStringEncodingMacInuit = 236
let kCFStringEncodingMacJapanese = 1
let kCFStringEncodingMacKannada = 16
let kCFStringEncodingMacKhmer = 20
let kCFStringEncodingMacKorean = 3
let kCFStringEncodingMacLaotian = 22
let kCFStringEncodingMacMalayalam = 17
let kCFStringEncodingMacMongolian = 27
let kCFStringEncodingMacOriya = 12
let kCFStringEncodingMacRoman = 0
let kCFStringEncodingMacRomanLatin1 = 2564
let kCFStringEncodingMacRomanian = 38
let kCFStringEncodingMacSinhalese = 18
let kCFStringEncodingMacSymbol = 33
let kCFStringEncodingMacTamil = 14
let kCFStringEncodingMacTelugu = 15
let kCFStringEncodingMacThai = 21
let kCFStringEncodingMacTibetan = 26
let kCFStringEncodingMacTurkish = 35
let kCFStringEncodingMacUkrainian = 152
let kCFStringEncodingMacVT100 = 252
let kCFStringEncodingMacVietnamese = 30
let kCFStringEncodingNextStepJapanese = 2818
let kCFStringEncodingNextStepLatin = 2817
let kCFStringEncodingNonLossyASCII = 3071
let kCFStringEncodingShiftJIS = 2561
let kCFStringEncodingShiftJIS_X0213 = 1576
let kCFStringEncodingShiftJIS_X0213_00 = 1576
let kCFStringEncodingShiftJIS_X0213_MenKuTen = 1577
let kCFStringEncodingUTF16 = 256
let kCFStringEncodingUTF16BE = 268435712
let kCFStringEncodingUTF16LE = 335544576
let kCFStringEncodingUTF32 = 201326848
let kCFStringEncodingUTF32BE = 402653440
let kCFStringEncodingUTF32LE = 469762304
let kCFStringEncodingUTF7 = 67109120
let kCFStringEncodingUTF7_IMAP = 2576
let kCFStringEncodingUTF8 = 134217984
let kCFStringEncodingUnicode = 256
let kCFStringEncodingVISCII = 2567
let kCFStringEncodingWindowsArabic = 1286
let kCFStringEncodingWindowsBalticRim = 1287
let kCFStringEncodingWindowsCyrillic = 1282
let kCFStringEncodingWindowsGreek = 1283
let kCFStringEncodingWindowsHebrew = 1285
let kCFStringEncodingWindowsKoreanJohab = 1296
let kCFStringEncodingWindowsLatin1 = 1280
let kCFStringEncodingWindowsLatin2 = 1281
let kCFStringEncodingWindowsLatin5 = 1284
let kCFStringEncodingWindowsVietnamese = 1288
let kCFStringNormalizationFormC = 2
let kCFStringNormalizationFormD = 0
let kCFStringNormalizationFormKC = 3
let kCFStringNormalizationFormKD = 1
let kCFStringTokenizerAttributeLanguage = 131072
let kCFStringTokenizerAttributeLatinTranscription = 65536
let kCFStringTokenizerTokenHasDerivedSubTokensMask = 4
let kCFStringTokenizerTokenHasHasNumbersMask = 8
let kCFStringTokenizerTokenHasNonLettersMask = 16
let kCFStringTokenizerTokenHasSubTokensMask = 2
let kCFStringTokenizerTokenIsCJWordMask = 32
let kCFStringTokenizerTokenNone = 0
let kCFStringTokenizerTokenNormal = 1
let kCFStringTokenizerUnitLineBreak = 3
let kCFStringTokenizerUnitParagraph = 2
let kCFStringTokenizerUnitSentence = 1
let kCFStringTokenizerUnitWord = 0
let kCFStringTokenizerUnitWordBoundary = 4
let kCFTimeZoneNameStyleDaylightSaving = 2
let kCFTimeZoneNameStyleGeneric = 4
let kCFTimeZoneNameStyleShortDaylightSaving = 3
let kCFTimeZoneNameStyleShortGeneric = 5
let kCFTimeZoneNameStyleShortStandard = 1
let kCFTimeZoneNameStyleStandard = 0
let kCFURLBookmarkCreationMinimalBookmarkMask = 512
let kCFURLBookmarkCreationPreferFileIDResolutionMask = 256
let kCFURLBookmarkCreationSecurityScopeAllowOnlyReadAccess = 4096
let kCFURLBookmarkCreationSuitableForBookmarkFile = 1024
let kCFURLBookmarkCreationWithSecurityScope = 2048
let kCFURLBookmarkCreationWithoutImplicitSecurityScope = 536870912
let kCFURLBookmarkResolutionWithSecurityScope = 1024
let kCFURLBookmarkResolutionWithoutImplicitStartAccessing = 32768
let kCFURLBookmarkResolutionWithoutMountingMask = 512
let kCFURLBookmarkResolutionWithoutUIMask = 256
let kCFURLComponentFragment = 12
let kCFURLComponentHost = 8
let kCFURLComponentNetLocation = 2
let kCFURLComponentParameterString = 10
let kCFURLComponentPassword = 6
let kCFURLComponentPath = 3
let kCFURLComponentPort = 9
let kCFURLComponentQuery = 11
let kCFURLComponentResourceSpecifier = 4
let kCFURLComponentScheme = 1
let kCFURLComponentUser = 5
let kCFURLComponentUserInfo = 7
let kCFURLEnumeratorDefaultBehavior = 0
let kCFURLEnumeratorDescendRecursively = 1
let kCFURLEnumeratorDirectoryPostOrderSuccess = 4
let kCFURLEnumeratorEnd = 2
let kCFURLEnumeratorError = 3
let kCFURLEnumeratorGenerateFileReferenceURLs = 4
let kCFURLEnumeratorGenerateRelativePathURLs = 64
let kCFURLEnumeratorIncludeDirectoriesPostOrder = 32
let kCFURLEnumeratorIncludeDirectoriesPreOrder = 16
let kCFURLEnumeratorSkipInvisibles = 2
let kCFURLEnumeratorSkipPackageContents = 8
let kCFURLEnumeratorSuccess = 1
let kCFURLHFSPathStyle = 1
let kCFURLImproperArgumentsError = -15
let kCFURLPOSIXPathStyle = 0
let kCFURLPropertyKeyUnavailableError = -17
let kCFURLRemoteHostUnavailableError = -14
let kCFURLResourceAccessViolationError = -13
let kCFURLResourceNotFoundError = -12
let kCFURLTimeoutError = -18
let kCFURLUnknownError = -10
let kCFURLUnknownPropertyKeyError = -16
let kCFURLUnknownSchemeError = -11
let kCFURLWindowsPathStyle = 2
let kCFUserNotificationAlternateResponse = 1
let kCFUserNotificationCancelResponse = 3
let kCFUserNotificationCautionAlertLevel = 2
let kCFUserNotificationDefaultResponse = 0
let kCFUserNotificationNoDefaultButtonFlag = 32
let kCFUserNotificationNoteAlertLevel = 1
let kCFUserNotificationOtherResponse = 2
let kCFUserNotificationPlainAlertLevel = 3
let kCFUserNotificationStopAlertLevel = 0
let kCFUserNotificationUseRadioButtonsFlag = 64
let kCFXMLEntityTypeCharacter = 4
let kCFXMLEntityTypeParameter = 0
let kCFXMLEntityTypeParsedExternal = 2
let kCFXMLEntityTypeParsedInternal = 1
let kCFXMLEntityTypeUnparsed = 3
let kCFXMLErrorElementlessDocument = 11
let kCFXMLErrorEncodingConversionFailure = 3
let kCFXMLErrorMalformedCDSect = 7
let kCFXMLErrorMalformedCharacterReference = 13
let kCFXMLErrorMalformedCloseTag = 8
let kCFXMLErrorMalformedComment = 12
let kCFXMLErrorMalformedDTD = 5
let kCFXMLErrorMalformedDocument = 10
let kCFXMLErrorMalformedName = 6
let kCFXMLErrorMalformedParsedCharacterData = 14
let kCFXMLErrorMalformedProcessingInstruction = 4
let kCFXMLErrorMalformedStartTag = 9
let kCFXMLErrorNoData = 15
let kCFXMLErrorUnexpectedEOF = 1
let kCFXMLErrorUnknownEncoding = 2
let kCFXMLNodeCurrentVersion = 1
let kCFXMLNodeTypeAttribute = 3
let kCFXMLNodeTypeAttributeListDeclaration = 15
let kCFXMLNodeTypeCDATASection = 7
let kCFXMLNodeTypeComment = 5
let kCFXMLNodeTypeDocument = 1
let kCFXMLNodeTypeDocumentFragment = 8
let kCFXMLNodeTypeDocumentType = 11
let kCFXMLNodeTypeElement = 2
let kCFXMLNodeTypeElementTypeDeclaration = 14
let kCFXMLNodeTypeEntity = 9
let kCFXMLNodeTypeEntityReference = 10
let kCFXMLNodeTypeNotation = 13
let kCFXMLNodeTypeProcessingInstruction = 4
let kCFXMLNodeTypeText = 6
let kCFXMLNodeTypeWhitespace = 12
let kCFXMLParserAddImpliedAttributes = 32
let kCFXMLParserAllOptions = 16777215
let kCFXMLParserNoOptions = 0
let kCFXMLParserReplacePhysicalEntities = 4
let kCFXMLParserResolveExternalEntities = 16
let kCFXMLParserSkipMetaData = 2
let kCFXMLParserSkipWhitespace = 8
let kCFXMLParserValidateDocument = 1
let kCFXMLStatusParseInProgress = -1
let kCFXMLStatusParseNotBegun = -2
let kCFXMLStatusParseSuccessful = 0
