(* auto-generated, do not modify *)

[@@@ocaml.warning "-33"]
open Runtime
open Objc

open CoreFoundation

let activityViewController imp = Define.method_spec ~cmd:(selector "activityViewController") ~typ:(returning (id)) ~enc:"@16@0:8" imp
let adaptivePresentationController imp = Define.method_spec ~cmd:(selector "adaptivePresentationController") ~typ:(returning (id)) ~enc:"@16@0:8" imp
let addOperationToServiceQueue' imp = Define.method_spec ~cmd:(selector "addOperationToServiceQueue:") ~typ:((ptr void) @-> returning (void)) ~enc:"v24@0:8@?16" imp
let additionalLeadingNavigationBarButtonItems imp = Define.method_spec ~cmd:(selector "additionalLeadingNavigationBarButtonItems") ~typ:(returning (id)) ~enc:"@16@0:8" imp
let additionalTrailingNavigationBarButtonItems imp = Define.method_spec ~cmd:(selector "additionalTrailingNavigationBarButtonItems") ~typ:(returning (id)) ~enc:"@16@0:8" imp
let allowedContentTypes imp = Define.method_spec ~cmd:(selector "allowedContentTypes") ~typ:(returning (id)) ~enc:"@16@0:8" imp
let allowsDocumentCreation imp = Define.method_spec ~cmd:(selector "allowsDocumentCreation") ~typ:(returning (bool)) ~enc:"c16@0:8" imp
let allowsPickingMultipleItems imp = Define.method_spec ~cmd:(selector "allowsPickingMultipleItems") ~typ:(returning (bool)) ~enc:"c16@0:8" imp
let applicationDidBecomeActive' imp = Define.method_spec ~cmd:(selector "applicationDidBecomeActive:") ~typ:(id @-> returning (void)) ~enc:"v24@0:8@16" imp
let backgroundColor imp = Define.method_spec ~cmd:(selector "backgroundColor") ~typ:(returning (id)) ~enc:"@16@0:8" imp
let backgroundTintColor imp = Define.method_spec ~cmd:(selector "backgroundTintColor") ~typ:(returning (id)) ~enc:"@16@0:8" imp
let badgeTintColor imp = Define.method_spec ~cmd:(selector "badgeTintColor") ~typ:(returning (id)) ~enc:"@16@0:8" imp
let becomeFirstResponder imp = Define.method_spec ~cmd:(selector "becomeFirstResponder") ~typ:(returning (bool)) ~enc:"c16@0:8" imp
let bridgedDocumentBrowserViewController imp = Define.method_spec ~cmd:(selector "bridgedDocumentBrowserViewController") ~typ:(returning (id)) ~enc:"@16@0:8" imp
let browserUserInterfaceStyle imp = Define.method_spec ~cmd:(selector "browserUserInterfaceStyle") ~typ:(returning (ullong)) ~enc:"Q16@0:8" imp
let canBecomeFirstResponder imp = Define.method_spec ~cmd:(selector "canBecomeFirstResponder") ~typ:(returning (bool)) ~enc:"c16@0:8" imp
let canPerformAction'withSender' imp = Define.method_spec ~cmd:(selector "canPerformAction:withSender:") ~typ:(_SEL @-> id @-> returning (bool)) ~enc:"c32@0:8:16@24" imp
let clearCurrentOpenInteraction imp = Define.method_spec ~cmd:(selector "clearCurrentOpenInteraction") ~typ:(returning (void)) ~enc:"v16@0:8" imp
let configuration imp = Define.method_spec ~cmd:(selector "configuration") ~typ:(returning (id)) ~enc:"@16@0:8" imp
let configurationForOpeningDocumentsWithContentTypes' imp = Define.method_spec ~cmd:(selector "configurationForOpeningDocumentsWithContentTypes:") ~typ:(id @-> returning (id)) ~enc:"@24@0:8@16" imp
let contentTypesForRecentDocuments imp = Define.method_spec ~cmd:(selector "contentTypesForRecentDocuments") ~typ:(returning (id)) ~enc:"@16@0:8" imp
let createButtonAspectRatio imp = Define.method_spec ~cmd:(selector "createButtonAspectRatio") ~typ:(returning (double)) ~enc:"d16@0:8" imp
let createButtonColor imp = Define.method_spec ~cmd:(selector "createButtonColor") ~typ:(returning (id)) ~enc:"@16@0:8" imp
let createButtonTitle imp = Define.method_spec ~cmd:(selector "createButtonTitle") ~typ:(returning (id)) ~enc:"@16@0:8" imp
let customActions imp = Define.method_spec ~cmd:(selector "customActions") ~typ:(returning (id)) ~enc:"@16@0:8" imp
let dealloc imp = Define.method_spec ~cmd:(selector "dealloc") ~typ:(returning (void)) ~enc:"v16@0:8" imp
let defaultDocumentAspectRatio imp = Define.method_spec ~cmd:(selector "defaultDocumentAspectRatio") ~typ:(returning (double)) ~enc:"d16@0:8" imp
let delegate imp = Define.method_spec ~cmd:(selector "delegate") ~typ:(returning (id)) ~enc:"@16@0:8" imp
let didCancel imp = Define.method_spec ~cmd:(selector "didCancel") ~typ:(returning (void)) ~enc:"v16@0:8" imp
let didImportDocumentAtURL'toDestinationURL' imp = Define.method_spec ~cmd:(selector "didImportDocumentAtURL:toDestinationURL:") ~typ:(id @-> id @-> returning (void)) ~enc:"v32@0:8@16@24" imp
let didMoveToSceneNotificationListener imp = Define.method_spec ~cmd:(selector "didMoveToSceneNotificationListener") ~typ:(returning (id)) ~enc:"@16@0:8" imp
let didPickDocumentsAtURLs' imp = Define.method_spec ~cmd:(selector "didPickDocumentsAtURLs:") ~typ:(id @-> returning (void)) ~enc:"v24@0:8@16" imp
let didRequestDocumentCreationWithHandler' imp = Define.method_spec ~cmd:(selector "didRequestDocumentCreationWithHandler:") ~typ:((ptr void) @-> returning (void)) ~enc:"v24@0:8@?16" imp
let didTapTryAgainInErrorViewController' imp = Define.method_spec ~cmd:(selector "didTapTryAgainInErrorViewController:") ~typ:(id @-> returning (void)) ~enc:"v24@0:8@16" imp
let dismiss imp = Define.method_spec ~cmd:(selector "dismiss") ~typ:(returning (void)) ~enc:"v16@0:8" imp
let dismissAllPresentedViewControllers'completion' imp = Define.method_spec ~cmd:(selector "dismissAllPresentedViewControllers:completion:") ~typ:(bool @-> (ptr void) @-> returning (void)) ~enc:"v28@0:8c16@?20" imp
let dismissalTransitionWillBeginNotificationListener imp = Define.method_spec ~cmd:(selector "dismissalTransitionWillBeginNotificationListener") ~typ:(returning (id)) ~enc:"@16@0:8" imp
let documentTypes imp = Define.method_spec ~cmd:(selector "documentTypes") ~typ:(returning (id)) ~enc:"@16@0:8" imp
let effectiveAppearanceDidChange' imp = Define.method_spec ~cmd:(selector "effectiveAppearanceDidChange:") ~typ:(id @-> returning (void)) ~enc:"v24@0:8@16" imp
let encodeWithCoder' imp = Define.method_spec ~cmd:(selector "encodeWithCoder:") ~typ:(id @-> returning (void)) ~enc:"v24@0:8@16" imp
let failedToImportDocumentAtURL'error' imp = Define.method_spec ~cmd:(selector "failedToImportDocumentAtURL:error:") ~typ:(id @-> id @-> returning (void)) ~enc:"v32@0:8@16@24" imp
let forwardHostSceneIdentifier' imp = Define.method_spec ~cmd:(selector "forwardHostSceneIdentifier:") ~typ:(id @-> returning (void)) ~enc:"v24@0:8@16" imp
let getTrackingViews'remoteButtons'fromBarButtons' imp = Define.method_spec ~cmd:(selector "getTrackingViews:remoteButtons:fromBarButtons:") ~typ:((ptr id) @-> (ptr id) @-> id @-> returning (void)) ~enc:"v40@0:8^@16^@24@32" imp
let importDocumentAtURL'byMoving'toCurrentBrowserLocationWithCompletion' imp = Define.method_spec ~cmd:(selector "importDocumentAtURL:byMoving:toCurrentBrowserLocationWithCompletion:") ~typ:(id @-> bool @-> (ptr void) @-> returning (void)) ~enc:"v36@0:8@16c24@?28" imp
let importDocumentAtURL'mode'toCurrentBrowserLocationWithCompletion' imp = Define.method_spec ~cmd:(selector "importDocumentAtURL:mode:toCurrentBrowserLocationWithCompletion:") ~typ:(id @-> ullong @-> (ptr void) @-> returning (void)) ~enc:"v40@0:8@16Q24@?32" imp
let importDocumentAtURL'nextToDocumentAtURL'mode'completionHandler' imp = Define.method_spec ~cmd:(selector "importDocumentAtURL:nextToDocumentAtURL:mode:completionHandler:") ~typ:(id @-> id @-> ullong @-> (ptr void) @-> returning (void)) ~enc:"v48@0:8@16@24Q32@?40" imp
let inBrowserTintColor imp = Define.method_spec ~cmd:(selector "inBrowserTintColor") ~typ:(returning (id)) ~enc:"@16@0:8" imp
let init imp = Define.method_spec ~cmd:(selector "init") ~typ:(returning (id)) ~enc:"@16@0:8" imp
let initForOpeningContentTypes' imp = Define.method_spec ~cmd:(selector "initForOpeningContentTypes:") ~typ:(id @-> returning (id)) ~enc:"@24@0:8@16" imp
let initForOpeningFilesWithContentTypes' imp = Define.method_spec ~cmd:(selector "initForOpeningFilesWithContentTypes:") ~typ:(id @-> returning (id)) ~enc:"@24@0:8@16" imp
let initWithCoder' imp = Define.method_spec ~cmd:(selector "initWithCoder:") ~typ:(id @-> returning (id)) ~enc:"@24@0:8@16" imp
let initWithConfiguration' imp = Define.method_spec ~cmd:(selector "initWithConfiguration:") ~typ:(id @-> returning (id)) ~enc:"@24@0:8@16" imp
let initializeBridgedDocumentBrowserIfNeeded imp = Define.method_spec ~cmd:(selector "initializeBridgedDocumentBrowserIfNeeded") ~typ:(returning (void)) ~enc:"v16@0:8" imp
let itemSubtitleColor imp = Define.method_spec ~cmd:(selector "itemSubtitleColor") ~typ:(returning (id)) ~enc:"@16@0:8" imp
let itemTitleColor imp = Define.method_spec ~cmd:(selector "itemTitleColor") ~typ:(returning (id)) ~enc:"@16@0:8" imp
let keyCommands imp = Define.method_spec ~cmd:(selector "keyCommands") ~typ:(returning (id)) ~enc:"@16@0:8" imp
let leadingBarButtonTrackingViews imp = Define.method_spec ~cmd:(selector "leadingBarButtonTrackingViews") ~typ:(returning (id)) ~enc:"@16@0:8" imp
let localizedCreateDocumentActionTitle imp = Define.method_spec ~cmd:(selector "localizedCreateDocumentActionTitle") ~typ:(returning (id)) ~enc:"@16@0:8" imp
let performKeyCommandNoOpOnHostSide' imp = Define.method_spec ~cmd:(selector "performKeyCommandNoOpOnHostSide:") ~typ:(id @-> returning (void)) ~enc:"v24@0:8@16" imp
let preferredStatusBarStyle imp = Define.method_spec ~cmd:(selector "preferredStatusBarStyle") ~typ:(returning (llong)) ~enc:"q16@0:8" imp
let prepareItems'forMode'usingBookmark'completionBlock' imp = Define.method_spec ~cmd:(selector "prepareItems:forMode:usingBookmark:completionBlock:") ~typ:(id @-> ullong @-> bool @-> (ptr void) @-> returning (void)) ~enc:"v44@0:8@16Q24c32@?36" imp
let prepareItems'usingBookmark'completionBlock' imp = Define.method_spec ~cmd:(selector "prepareItems:usingBookmark:completionBlock:") ~typ:(id @-> bool @-> (ptr void) @-> returning (void)) ~enc:"v36@0:8@16c24@?28" imp
let presentDocumentBrowserTimer imp = Define.method_spec ~cmd:(selector "presentDocumentBrowserTimer") ~typ:(returning (id)) ~enc:"@16@0:8" imp
let presentViewController'animated'completion' imp = Define.method_spec ~cmd:(selector "presentViewController:animated:completion:") ~typ:(id @-> bool @-> (ptr void) @-> returning (void)) ~enc:"v36@0:8@16c24@?28" imp
let presentationTransitionWillBeginNotificationListener imp = Define.method_spec ~cmd:(selector "presentationTransitionWillBeginNotificationListener") ~typ:(returning (id)) ~enc:"@16@0:8" imp
let recentDocumentsContentTypes imp = Define.method_spec ~cmd:(selector "recentDocumentsContentTypes") ~typ:(returning (id)) ~enc:"@16@0:8" imp
let recentDocumentsContentTypesFromInfoPlist imp = Define.method_spec ~cmd:(selector "recentDocumentsContentTypesFromInfoPlist") ~typ:(returning (id)) ~enc:"@16@0:8" imp
let registerSceneListenerForWindow' imp = Define.method_spec ~cmd:(selector "registerSceneListenerForWindow:") ~typ:(id @-> returning (void)) ~enc:"v24@0:8@16" imp
let remoteAdditionalLeadingNavigationBarButtonItems imp = Define.method_spec ~cmd:(selector "remoteAdditionalLeadingNavigationBarButtonItems") ~typ:(returning (id)) ~enc:"@16@0:8" imp
let remoteAdditionalTrailingNavigationBarButtonItems imp = Define.method_spec ~cmd:(selector "remoteAdditionalTrailingNavigationBarButtonItems") ~typ:(returning (id)) ~enc:"@16@0:8" imp
let remoteBarButtonForUUID' imp = Define.method_spec ~cmd:(selector "remoteBarButtonForUUID:") ~typ:(id @-> returning (id)) ~enc:"@24@0:8@16" imp
let remoteViewController imp = Define.method_spec ~cmd:(selector "remoteViewController") ~typ:(returning (id)) ~enc:"@16@0:8" imp
let remoteViewController'didTerminateViewServiceWithError' imp = Define.method_spec ~cmd:(selector "remoteViewController:didTerminateViewServiceWithError:") ~typ:(id @-> id @-> returning (void)) ~enc:"v32@0:8@16@24" imp
let revealDocumentAtURL'importIfNeeded'completion' imp = Define.method_spec ~cmd:(selector "revealDocumentAtURL:importIfNeeded:completion:") ~typ:(id @-> bool @-> (ptr void) @-> returning (void)) ~enc:"v36@0:8@16c24@?28" imp
let revealDocumentAtURL'shouldImport'completion' imp = Define.method_spec ~cmd:(selector "revealDocumentAtURL:shouldImport:completion:") ~typ:(id @-> bool @-> (ptr void) @-> returning (void)) ~enc:"v36@0:8@16c24@?28" imp
let serviceProxy imp = Define.method_spec ~cmd:(selector "serviceProxy") ~typ:(returning (id)) ~enc:"@16@0:8" imp
let serviceQueue imp = Define.method_spec ~cmd:(selector "serviceQueue") ~typ:(returning (id)) ~enc:"@16@0:8" imp
let setActivityViewController' imp = Define.method_spec ~cmd:(selector "setActivityViewController:") ~typ:(id @-> returning (void)) ~enc:"v24@0:8@16" imp
let setAdaptivePresentationController' imp = Define.method_spec ~cmd:(selector "setAdaptivePresentationController:") ~typ:(id @-> returning (void)) ~enc:"v24@0:8@16" imp
let setAdditionalLeadingNavigationBarButtonItems' imp = Define.method_spec ~cmd:(selector "setAdditionalLeadingNavigationBarButtonItems:") ~typ:(id @-> returning (void)) ~enc:"v24@0:8@16" imp
let setAdditionalToolbarButtonItems' imp = Define.method_spec ~cmd:(selector "setAdditionalToolbarButtonItems:") ~typ:(id @-> returning (void)) ~enc:"v24@0:8@16" imp
let setAdditionalTrailingNavigationBarButtonItems' imp = Define.method_spec ~cmd:(selector "setAdditionalTrailingNavigationBarButtonItems:") ~typ:(id @-> returning (void)) ~enc:"v24@0:8@16" imp
let setAllowsDocumentCreation' imp = Define.method_spec ~cmd:(selector "setAllowsDocumentCreation:") ~typ:(bool @-> returning (void)) ~enc:"v20@0:8c16" imp
let setAllowsPickingMultipleItems' imp = Define.method_spec ~cmd:(selector "setAllowsPickingMultipleItems:") ~typ:(bool @-> returning (void)) ~enc:"v20@0:8c16" imp
let setBackgroundColor' imp = Define.method_spec ~cmd:(selector "setBackgroundColor:") ~typ:(id @-> returning (void)) ~enc:"v24@0:8@16" imp
let setBackgroundTintColor' imp = Define.method_spec ~cmd:(selector "setBackgroundTintColor:") ~typ:(id @-> returning (void)) ~enc:"v24@0:8@16" imp
let setBadgeTintColor' imp = Define.method_spec ~cmd:(selector "setBadgeTintColor:") ~typ:(id @-> returning (void)) ~enc:"v24@0:8@16" imp
let setBridgedDocumentBrowserViewController' imp = Define.method_spec ~cmd:(selector "setBridgedDocumentBrowserViewController:") ~typ:(id @-> returning (void)) ~enc:"v24@0:8@16" imp
let setBrowserUserInterfaceStyle' imp = Define.method_spec ~cmd:(selector "setBrowserUserInterfaceStyle:") ~typ:(ullong @-> returning (void)) ~enc:"v24@0:8Q16" imp
let setConfiguration' imp = Define.method_spec ~cmd:(selector "setConfiguration:") ~typ:(id @-> returning (void)) ~enc:"v24@0:8@16" imp
let setCreateButtonAspectRatio' imp = Define.method_spec ~cmd:(selector "setCreateButtonAspectRatio:") ~typ:(double @-> returning (void)) ~enc:"v24@0:8d16" imp
let setCreateButtonColor' imp = Define.method_spec ~cmd:(selector "setCreateButtonColor:") ~typ:(id @-> returning (void)) ~enc:"v24@0:8@16" imp
let setCreateButtonTitle' imp = Define.method_spec ~cmd:(selector "setCreateButtonTitle:") ~typ:(id @-> returning (void)) ~enc:"v24@0:8@16" imp
let setCustomActions' imp = Define.method_spec ~cmd:(selector "setCustomActions:") ~typ:(id @-> returning (void)) ~enc:"v24@0:8@16" imp
let setDefaultDocumentAspectRatio' imp = Define.method_spec ~cmd:(selector "setDefaultDocumentAspectRatio:") ~typ:(double @-> returning (void)) ~enc:"v24@0:8d16" imp
let setDelegate' imp = Define.method_spec ~cmd:(selector "setDelegate:") ~typ:(id @-> returning (void)) ~enc:"v24@0:8@16" imp
let setDidMoveToSceneNotificationListener' imp = Define.method_spec ~cmd:(selector "setDidMoveToSceneNotificationListener:") ~typ:(id @-> returning (void)) ~enc:"v24@0:8@16" imp
let setDismissalTransitionWillBeginNotificationListener' imp = Define.method_spec ~cmd:(selector "setDismissalTransitionWillBeginNotificationListener:") ~typ:(id @-> returning (void)) ~enc:"v24@0:8@16" imp
let setDocumentTypes' imp = Define.method_spec ~cmd:(selector "setDocumentTypes:") ~typ:(id @-> returning (void)) ~enc:"v24@0:8@16" imp
let setEditing'animated' imp = Define.method_spec ~cmd:(selector "setEditing:animated:") ~typ:(bool @-> bool @-> returning (void)) ~enc:"v24@0:8c16c20" imp
let setInBrowserTintColor' imp = Define.method_spec ~cmd:(selector "setInBrowserTintColor:") ~typ:(id @-> returning (void)) ~enc:"v24@0:8@16" imp
let setItemSubtitleColor' imp = Define.method_spec ~cmd:(selector "setItemSubtitleColor:") ~typ:(id @-> returning (void)) ~enc:"v24@0:8@16" imp
let setItemTitleColor' imp = Define.method_spec ~cmd:(selector "setItemTitleColor:") ~typ:(id @-> returning (void)) ~enc:"v24@0:8@16" imp
let setLeadingBarButtonTrackingViews' imp = Define.method_spec ~cmd:(selector "setLeadingBarButtonTrackingViews:") ~typ:(id @-> returning (void)) ~enc:"v24@0:8@16" imp
let setLocalizedCreateDocumentActionTitle' imp = Define.method_spec ~cmd:(selector "setLocalizedCreateDocumentActionTitle:") ~typ:(id @-> returning (void)) ~enc:"v24@0:8@16" imp
let setPresentDocumentBrowserTimer' imp = Define.method_spec ~cmd:(selector "setPresentDocumentBrowserTimer:") ~typ:(id @-> returning (void)) ~enc:"v24@0:8@16" imp
let setPresentationTransitionWillBeginNotificationListener' imp = Define.method_spec ~cmd:(selector "setPresentationTransitionWillBeginNotificationListener:") ~typ:(id @-> returning (void)) ~enc:"v24@0:8@16" imp
let setRemoteAdditionalLeadingNavigationBarButtonItems' imp = Define.method_spec ~cmd:(selector "setRemoteAdditionalLeadingNavigationBarButtonItems:") ~typ:(id @-> returning (void)) ~enc:"v24@0:8@16" imp
let setRemoteAdditionalTrailingNavigationBarButtonItems' imp = Define.method_spec ~cmd:(selector "setRemoteAdditionalTrailingNavigationBarButtonItems:") ~typ:(id @-> returning (void)) ~enc:"v24@0:8@16" imp
let setRemoteViewController' imp = Define.method_spec ~cmd:(selector "setRemoteViewController:") ~typ:(id @-> returning (void)) ~enc:"v24@0:8@16" imp
let setServiceProxy' imp = Define.method_spec ~cmd:(selector "setServiceProxy:") ~typ:(id @-> returning (void)) ~enc:"v24@0:8@16" imp
let setServiceQueue' imp = Define.method_spec ~cmd:(selector "setServiceQueue:") ~typ:(id @-> returning (void)) ~enc:"v24@0:8@16" imp
let setShouldDelayRemoteViewController' imp = Define.method_spec ~cmd:(selector "setShouldDelayRemoteViewController:") ~typ:(bool @-> returning (void)) ~enc:"v20@0:8c16" imp
let setShouldPresentBridgedDocumentBrowser' imp = Define.method_spec ~cmd:(selector "setShouldPresentBridgedDocumentBrowser:") ~typ:(bool @-> returning (void)) ~enc:"v20@0:8c16" imp
let setShouldShowFileExtensions' imp = Define.method_spec ~cmd:(selector "setShouldShowFileExtensions:") ~typ:(bool @-> returning (void)) ~enc:"v20@0:8c16" imp
let setSortingBackgroundColor' imp = Define.method_spec ~cmd:(selector "setSortingBackgroundColor:") ~typ:(id @-> returning (void)) ~enc:"v24@0:8@16" imp
let setTrailingBarButtonTrackingViews' imp = Define.method_spec ~cmd:(selector "setTrailingBarButtonTrackingViews:") ~typ:(id @-> returning (void)) ~enc:"v24@0:8@16" imp
let setshouldShowFileExtensions' imp = Define.method_spec ~cmd:(selector "setshouldShowFileExtensions:") ~typ:(bool @-> returning (void)) ~enc:"v20@0:8c16" imp
let shouldDelayRemoteViewController imp = Define.method_spec ~cmd:(selector "shouldDelayRemoteViewController") ~typ:(returning (bool)) ~enc:"c16@0:8" imp
let shouldPresentBridgedDocumentBrowser imp = Define.method_spec ~cmd:(selector "shouldPresentBridgedDocumentBrowser") ~typ:(returning (bool)) ~enc:"c16@0:8" imp
let shouldShowFileExtensions imp = Define.method_spec ~cmd:(selector "shouldShowFileExtensions") ~typ:(returning (bool)) ~enc:"c16@0:8" imp
let sortingBackgroundColor imp = Define.method_spec ~cmd:(selector "sortingBackgroundColor") ~typ:(returning (id)) ~enc:"@16@0:8" imp
let supportsRemovableFileProvidersForConfiguration' imp = Define.method_spec ~cmd:(selector "supportsRemovableFileProvidersForConfiguration:") ~typ:(id @-> returning (bool)) ~enc:"c24@0:8@16" imp
let trackingViewForUUID' imp = Define.method_spec ~cmd:(selector "trackingViewForUUID:") ~typ:(id @-> returning (id)) ~enc:"@24@0:8@16" imp
let trailingBarButtonTrackingViews imp = Define.method_spec ~cmd:(selector "trailingBarButtonTrackingViews") ~typ:(returning (id)) ~enc:"@16@0:8" imp
let traitCollectionDidChange' imp = Define.method_spec ~cmd:(selector "traitCollectionDidChange:") ~typ:(id @-> returning (void)) ~enc:"v24@0:8@16" imp
let transitionControllerForDocumentAtURL' imp = Define.method_spec ~cmd:(selector "transitionControllerForDocumentAtURL:") ~typ:(id @-> returning (id)) ~enc:"@24@0:8@16" imp
let transitionControllerForDocumentURL' imp = Define.method_spec ~cmd:(selector "transitionControllerForDocumentURL:") ~typ:(id @-> returning (id)) ~enc:"@24@0:8@16" imp
let uinsCustomActionsFromCustomActions' imp = Define.method_spec ~cmd:(selector "uinsCustomActionsFromCustomActions:") ~typ:(id @-> returning (id)) ~enc:"@24@0:8@16" imp
let updateBackgroundColor imp = Define.method_spec ~cmd:(selector "updateBackgroundColor") ~typ:(returning (void)) ~enc:"v16@0:8" imp
let updateSceneSettingsForWindow' imp = Define.method_spec ~cmd:(selector "updateSceneSettingsForWindow:") ~typ:(id @-> returning (void)) ~enc:"v24@0:8@16" imp
let viewDidLoad imp = Define.method_spec ~cmd:(selector "viewDidLoad") ~typ:(returning (void)) ~enc:"v16@0:8" imp
let viewDidMoveToWindow'shouldAppearOrDisappear' imp = Define.method_spec ~cmd:(selector "viewDidMoveToWindow:shouldAppearOrDisappear:") ~typ:(id @-> bool @-> returning (void)) ~enc:"v28@0:8@16c24" imp
let viewWillTransitionToSize'withTransitionCoordinator' imp = Define.method_spec ~cmd:(selector "viewWillTransitionToSize:withTransitionCoordinator:") ~typ:(CGSize.t @-> id @-> returning (void)) ~enc:"v40@0:8{CGSize=dd}16@32" imp
