(* auto-generated, do not modify *)

[@@@ocaml.warning "-33"]
open Runtime
open Objc

open CoreFoundation

(** Apple docs: {{:https://developer.apple.com/documentation/cloudkit/ckasset?language=objc}CKAsset} *)

let self = get_class "CKAsset"

let _CKDescriptionPropertiesWithPublic x ~private_ ~shouldExpand self = msg_send ~self ~cmd:(selector "CKDescriptionPropertiesWithPublic:private:shouldExpand:") ~typ:(bool @-> bool @-> bool @-> returning id) x private_ shouldExpand
let _UUID self = msg_send ~self ~cmd:(selector "UUID") ~typ:(returning id)
let arrayIndex self = msg_send ~self ~cmd:(selector "arrayIndex") ~typ:(returning llong) |> LLong.to_int
let assetChunkerOptions self = msg_send ~self ~cmd:(selector "assetChunkerOptions") ~typ:(returning id)
let assetContent self = msg_send ~self ~cmd:(selector "assetContent") ~typ:(returning id)
let assetCopyInfo self = msg_send ~self ~cmd:(selector "assetCopyInfo") ~typ:(returning id)
let assetHandleUUID self = msg_send ~self ~cmd:(selector "assetHandleUUID") ~typ:(returning id)
let assetKey self = msg_send ~self ~cmd:(selector "assetKey") ~typ:(returning id)
let assetReference self = msg_send ~self ~cmd:(selector "assetReference") ~typ:(returning id)
let assetRereferenceInfo self = msg_send ~self ~cmd:(selector "assetRereferenceInfo") ~typ:(returning id)
let assetTransferOptions self = msg_send ~self ~cmd:(selector "assetTransferOptions") ~typ:(returning id)
let authToken self = msg_send ~self ~cmd:(selector "authToken") ~typ:(returning id)
let boundaryKey self = msg_send ~self ~cmd:(selector "boundaryKey") ~typ:(returning id)
let clearAssetKey self = msg_send ~self ~cmd:(selector "clearAssetKey") ~typ:(returning id)
let constructedAssetDownloadParameters self = msg_send ~self ~cmd:(selector "constructedAssetDownloadParameters") ~typ:(returning id)
let constructedAssetDownloadURL self = msg_send ~self ~cmd:(selector "constructedAssetDownloadURL") ~typ:(returning id)
let constructedAssetDownloadURLTemplate self = msg_send ~self ~cmd:(selector "constructedAssetDownloadURLTemplate") ~typ:(returning id)
let constructedAssetEstimatedSize self = msg_send ~self ~cmd:(selector "constructedAssetEstimatedSize") ~typ:(returning ullong) |> ULLong.to_int
let contentBaseURL self = msg_send ~self ~cmd:(selector "contentBaseURL") ~typ:(returning id)
let description self = msg_send ~self ~cmd:(selector "description") ~typ:(returning id)
let deviceID self = msg_send ~self ~cmd:(selector "deviceID") ~typ:(returning id)
let downloadBaseURL self = msg_send ~self ~cmd:(selector "downloadBaseURL") ~typ:(returning id)
let downloadPreauthorization self = msg_send ~self ~cmd:(selector "downloadPreauthorization") ~typ:(returning id)
let downloadTokenExpiration self = msg_send ~self ~cmd:(selector "downloadTokenExpiration") ~typ:(returning ullong) |> ULLong.to_int
let downloadURL self = msg_send ~self ~cmd:(selector "downloadURL") ~typ:(returning id)
let downloadURLExpiration self = msg_send ~self ~cmd:(selector "downloadURLExpiration") ~typ:(returning id)
let downloadURLTemplate self = msg_send ~self ~cmd:(selector "downloadURLTemplate") ~typ:(returning id)
let downloadURLWithFileName x self = msg_send ~self ~cmd:(selector "downloadURLWithFileName:") ~typ:(id @-> returning id) x
let downloaded self = msg_send ~self ~cmd:(selector "downloaded") ~typ:(returning bool)
let encodeWithCoder x self = msg_send ~self ~cmd:(selector "encodeWithCoder:") ~typ:(id @-> returning void) x
let fileHandle self = msg_send ~self ~cmd:(selector "fileHandle") ~typ:(returning id)
let fileID self = msg_send ~self ~cmd:(selector "fileID") ~typ:(returning id)
let fileURL self = msg_send ~self ~cmd:(selector "fileURL") ~typ:(returning id)
let generationCountToSave self = msg_send ~self ~cmd:(selector "generationCountToSave") ~typ:(returning id)
let hasSize self = msg_send ~self ~cmd:(selector "hasSize") ~typ:(returning bool)
let init self = msg_send ~self ~cmd:(selector "init") ~typ:(returning id)
let initWithAssetContent x ~itemTypeHint self = msg_send ~self ~cmd:(selector "initWithAssetContent:itemTypeHint:") ~typ:(id @-> id @-> returning id) x itemTypeHint
let initWithAssetReference x self = msg_send ~self ~cmd:(selector "initWithAssetReference:") ~typ:(id @-> returning id) x
let initWithCoder x self = msg_send ~self ~cmd:(selector "initWithCoder:") ~typ:(id @-> returning id) x
let initWithCopyInfo x ~fileURL self = msg_send ~self ~cmd:(selector "initWithCopyInfo:fileURL:") ~typ:(id @-> id @-> returning id) x fileURL
let initWithDeviceID x ~fileID ~generationID self = msg_send ~self ~cmd:(selector "initWithDeviceID:fileID:generationID:") ~typ:(id @-> id @-> id @-> returning id) x fileID generationID
let initWithFileDescriptor x self = msg_send ~self ~cmd:(selector "initWithFileDescriptor:") ~typ:(int @-> returning id) x
let initWithFileURL x self = msg_send ~self ~cmd:(selector "initWithFileURL:") ~typ:(id @-> returning id) x
let initWithFileURL1 x ~signature self = msg_send ~self ~cmd:(selector "initWithFileURL:signature:") ~typ:(id @-> id @-> returning id) x signature
let initWithFileURL2 x ~signature ~assetHandleUUID self = msg_send ~self ~cmd:(selector "initWithFileURL:signature:assetHandleUUID:") ~typ:(id @-> id @-> id @-> returning id) x signature assetHandleUUID
let isConstructedAsset self = msg_send ~self ~cmd:(selector "isConstructedAsset") ~typ:(returning bool)
let isRereferencedAssetUpload self = msg_send ~self ~cmd:(selector "isRereferencedAssetUpload") ~typ:(returning bool)
let itemTypeHint self = msg_send ~self ~cmd:(selector "itemTypeHint") ~typ:(returning id)
let nullableFileURL self = msg_send ~self ~cmd:(selector "nullableFileURL") ~typ:(returning id)
let openWithError x self = msg_send ~self ~cmd:(selector "openWithError:") ~typ:((ptr id) @-> returning id) x
let owner self = msg_send ~self ~cmd:(selector "owner") ~typ:(returning id)
let paddedFileSize self = msg_send ~self ~cmd:(selector "paddedFileSize") ~typ:(returning ullong) |> ULLong.to_int
let realPathURL self = msg_send ~self ~cmd:(selector "realPathURL") ~typ:(returning id)
let record self = msg_send ~self ~cmd:(selector "record") ~typ:(returning id)
let recordID self = msg_send ~self ~cmd:(selector "recordID") ~typ:(returning id)
let recordKey self = msg_send ~self ~cmd:(selector "recordKey") ~typ:(returning id)
let referenceSignature self = msg_send ~self ~cmd:(selector "referenceSignature") ~typ:(returning id)
let requestor self = msg_send ~self ~cmd:(selector "requestor") ~typ:(returning id)
let setArrayIndex x self = msg_send ~self ~cmd:(selector "setArrayIndex:") ~typ:(llong @-> returning void) (LLong.of_int x)
let setAssetChunkerOptions x self = msg_send ~self ~cmd:(selector "setAssetChunkerOptions:") ~typ:(id @-> returning void) x
let setAssetContent x self = msg_send ~self ~cmd:(selector "setAssetContent:") ~typ:(id @-> returning void) x
let setAssetCopyInfo x self = msg_send ~self ~cmd:(selector "setAssetCopyInfo:") ~typ:(id @-> returning void) x
let setAssetKey x self = msg_send ~self ~cmd:(selector "setAssetKey:") ~typ:(id @-> returning void) x
let setAssetReference x self = msg_send ~self ~cmd:(selector "setAssetReference:") ~typ:(id @-> returning void) x
let setAssetRereferenceInfo x self = msg_send ~self ~cmd:(selector "setAssetRereferenceInfo:") ~typ:(id @-> returning void) x
let setAssetTransferOptions x self = msg_send ~self ~cmd:(selector "setAssetTransferOptions:") ~typ:(id @-> returning void) x
let setAuthToken x self = msg_send ~self ~cmd:(selector "setAuthToken:") ~typ:(id @-> returning void) x
let setBoundaryKey x self = msg_send ~self ~cmd:(selector "setBoundaryKey:") ~typ:(id @-> returning void) x
let setClearAssetKey x self = msg_send ~self ~cmd:(selector "setClearAssetKey:") ~typ:(id @-> returning void) x
let setConstructedAssetDownloadParameters x self = msg_send ~self ~cmd:(selector "setConstructedAssetDownloadParameters:") ~typ:(id @-> returning void) x
let setConstructedAssetDownloadURL x self = msg_send ~self ~cmd:(selector "setConstructedAssetDownloadURL:") ~typ:(id @-> returning void) x
let setConstructedAssetDownloadURLTemplate x self = msg_send ~self ~cmd:(selector "setConstructedAssetDownloadURLTemplate:") ~typ:(id @-> returning void) x
let setConstructedAssetEstimatedSize x self = msg_send ~self ~cmd:(selector "setConstructedAssetEstimatedSize:") ~typ:(ullong @-> returning void) (ULLong.of_int x)
let setContentBaseURL x self = msg_send ~self ~cmd:(selector "setContentBaseURL:") ~typ:(id @-> returning void) x
let setDeviceID x self = msg_send ~self ~cmd:(selector "setDeviceID:") ~typ:(id @-> returning void) x
let setDownloadBaseURL x self = msg_send ~self ~cmd:(selector "setDownloadBaseURL:") ~typ:(id @-> returning void) x
let setDownloadPreauthorization x self = msg_send ~self ~cmd:(selector "setDownloadPreauthorization:") ~typ:(id @-> returning void) x
let setDownloadTokenExpiration x self = msg_send ~self ~cmd:(selector "setDownloadTokenExpiration:") ~typ:(ullong @-> returning void) (ULLong.of_int x)
let setDownloadURLExpiration x self = msg_send ~self ~cmd:(selector "setDownloadURLExpiration:") ~typ:(id @-> returning void) x
let setDownloadURLTemplate x self = msg_send ~self ~cmd:(selector "setDownloadURLTemplate:") ~typ:(id @-> returning void) x
let setDownloaded x self = msg_send ~self ~cmd:(selector "setDownloaded:") ~typ:(bool @-> returning void) x
let setFileHandle x self = msg_send ~self ~cmd:(selector "setFileHandle:") ~typ:(id @-> returning void) x
let setFileID x self = msg_send ~self ~cmd:(selector "setFileID:") ~typ:(id @-> returning void) x
let setFileURL x self = msg_send ~self ~cmd:(selector "setFileURL:") ~typ:(id @-> returning void) x
let setGenerationCountToSave x self = msg_send ~self ~cmd:(selector "setGenerationCountToSave:") ~typ:(id @-> returning void) x
let setHasSize x self = msg_send ~self ~cmd:(selector "setHasSize:") ~typ:(bool @-> returning void) x
let setItemTypeHint x self = msg_send ~self ~cmd:(selector "setItemTypeHint:") ~typ:(id @-> returning void) x
let setNullableFileURL x self = msg_send ~self ~cmd:(selector "setNullableFileURL:") ~typ:(id @-> returning void) x
let setOwner x self = msg_send ~self ~cmd:(selector "setOwner:") ~typ:(id @-> returning void) x
let setPaddedFileSize x self = msg_send ~self ~cmd:(selector "setPaddedFileSize:") ~typ:(ullong @-> returning void) (ULLong.of_int x)
let setRealPathURL x self = msg_send ~self ~cmd:(selector "setRealPathURL:") ~typ:(id @-> returning void) x
let setRecord x self = msg_send ~self ~cmd:(selector "setRecord:") ~typ:(id @-> returning void) x
let setRecordID x self = msg_send ~self ~cmd:(selector "setRecordID:") ~typ:(id @-> returning void) x
let setRecordKey x self = msg_send ~self ~cmd:(selector "setRecordKey:") ~typ:(id @-> returning void) x
let setReferenceSignature x self = msg_send ~self ~cmd:(selector "setReferenceSignature:") ~typ:(id @-> returning void) x
let setRequestor x self = msg_send ~self ~cmd:(selector "setRequestor:") ~typ:(id @-> returning void) x
let setShouldReadAssetContentUsingClientProxy x self = msg_send ~self ~cmd:(selector "setShouldReadAssetContentUsingClientProxy:") ~typ:(bool @-> returning void) x
let setShouldReadRawEncryptedData x self = msg_send ~self ~cmd:(selector "setShouldReadRawEncryptedData:") ~typ:(bool @-> returning void) x
let setSignature x self = msg_send ~self ~cmd:(selector "setSignature:") ~typ:(id @-> returning void) x
let setSize x self = msg_send ~self ~cmd:(selector "setSize:") ~typ:(ullong @-> returning void) (ULLong.of_int x)
let setStorageGroupingPolicy x self = msg_send ~self ~cmd:(selector "setStorageGroupingPolicy:") ~typ:(llong @-> returning void) (LLong.of_int x)
let setUUID x self = msg_send ~self ~cmd:(selector "setUUID:") ~typ:(id @-> returning void) x
let setUploadRank x self = msg_send ~self ~cmd:(selector "setUploadRank:") ~typ:(llong @-> returning void) (LLong.of_int x)
let setUploadReceipt x self = msg_send ~self ~cmd:(selector "setUploadReceipt:") ~typ:(id @-> returning void) x
let setUploadReceiptExpiration x self = msg_send ~self ~cmd:(selector "setUploadReceiptExpiration:") ~typ:(double @-> returning void) x
let setUploaded x self = msg_send ~self ~cmd:(selector "setUploaded:") ~typ:(bool @-> returning void) x
let setUsesAssetDownloadStagingManager x self = msg_send ~self ~cmd:(selector "setUsesAssetDownloadStagingManager:") ~typ:(bool @-> returning void) x
let setWasCached x self = msg_send ~self ~cmd:(selector "setWasCached:") ~typ:(bool @-> returning void) x
let setWrappedAssetKey x self = msg_send ~self ~cmd:(selector "setWrappedAssetKey:") ~typ:(id @-> returning void) x
let shouldReadAssetContentUsingClientProxy self = msg_send ~self ~cmd:(selector "shouldReadAssetContentUsingClientProxy") ~typ:(returning bool)
let shouldReadRawEncryptedData self = msg_send ~self ~cmd:(selector "shouldReadRawEncryptedData") ~typ:(returning bool)
let signature self = msg_send ~self ~cmd:(selector "signature") ~typ:(returning id)
let size self = msg_send ~self ~cmd:(selector "size") ~typ:(returning ullong) |> ULLong.to_int
let storageGroupingPolicy self = msg_send ~self ~cmd:(selector "storageGroupingPolicy") ~typ:(returning llong) |> LLong.to_int
let uploadRank self = msg_send ~self ~cmd:(selector "uploadRank") ~typ:(returning llong) |> LLong.to_int
let uploadReceipt self = msg_send ~self ~cmd:(selector "uploadReceipt") ~typ:(returning id)
let uploadReceiptExpiration self = msg_send ~self ~cmd:(selector "uploadReceiptExpiration") ~typ:(returning double)
let uploaded self = msg_send ~self ~cmd:(selector "uploaded") ~typ:(returning bool)
let usesAssetDownloadStagingManager self = msg_send ~self ~cmd:(selector "usesAssetDownloadStagingManager") ~typ:(returning bool)
let wasCached self = msg_send ~self ~cmd:(selector "wasCached") ~typ:(returning bool)
let wrappedAssetKey self = msg_send ~self ~cmd:(selector "wrappedAssetKey") ~typ:(returning id)