name: Prepare Release with Submodules

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name (e.g., v1.0.0)'
        required: true
      release_name:
        description: 'Release name/title'
        required: true
      release_body:
        description: 'Release notes/description'
        required: false

permissions:
  contents: write

jobs:
  build-release:
    name: Create Release Archive
    runs-on: macos-latest

    steps:
    - name: Checkout repo with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Set up tag and version variables
      run: |
        echo "RELEASE_TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
        echo "RELEASE_NAME=${{ github.event.inputs.release_name }}" >> $GITHUB_ENV
        echo "RELEASE_BODY=${{ github.event.inputs.release_body }}" >> $GITHUB_ENV

    - name: Create release archive including submodules
      run: |
        mkdir release-dir
        git archive --format=tar HEAD | tar -x -C release-dir
        for submodule in $(git config --file .gitmodules --get-regexp path | awk '{ print $2 }'); do
          mkdir -p release-dir/$submodule
          (cd $submodule && git archive --format=tar HEAD) | tar -x -C release-dir/$submodule
        done
        tar czf "${RELEASE_TAG}.tar.gz" -C release-dir .

    - name: Create GitHub release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.RELEASE_TAG }}
        name: ${{ env.RELEASE_NAME }}
        body: ${{ env.RELEASE_BODY }}
        files: ${{ env.RELEASE_TAG }}.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
